const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'};
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers});
const env=(k:string)=>Deno.env.get(k)||'';
async function user(req:Request){const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))throw Object.assign(new Error('Sign in required.'),{status:401});const r=await fetch(`${env('SUPABASE_URL')}/auth/v1/user`,{headers:{apikey:env('SUPABASE_ANON_KEY'),Authorization:auth}});if(!r.ok)throw Object.assign(new Error('Session expired. Sign in again.'),{status:401});return await r.json()}
async function rest(path:string,{method='GET',body,prefer='return=representation'}:{method?:string,body?:unknown,prefer?:string}={}){const r=await fetch(`${env('SUPABASE_URL')}/rest/v1/${path}`,{method,headers:{apikey:env('SUPABASE_SERVICE_ROLE_KEY'),Authorization:`Bearer ${env('SUPABASE_SERVICE_ROLE_KEY')}`,'Content-Type':'application/json',Prefer:prefer},body:body==null?undefined:JSON.stringify(body)});let t=await r.text(),j:any=null;if(t){try{j=JSON.parse(t)}catch{j=t}}if(!r.ok)throw Object.assign(new Error(j?.message||'Database request failed.'),{status:500});return j}
function outputText(j:any){if(typeof j?.output_text==='string')return j.output_text;for(const item of j?.output||[])for(const c of item?.content||[])if(c.type==='output_text'&&c.text)return c.text;return''}
function parseJson(t:string){let s=t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let a=s.indexOf('{'),b=s.lastIndexOf('}');if(a>=0&&b>a)s=s.slice(a,b+1);try{return JSON.parse(s)}catch{return{summary:t}}}
async function aiPlan(answers:any,plan:any){const key=env('OPENAI_API_KEY');if(!key)return null;const instructions=`You are the onboarding planner for Work + Gym Coach. Return JSON only. Improve the supplied deterministic plan without changing or violating its hard availability constraints. Never place workouts during work, commute, sleep, or blocked commitments. Respect workout duration, experience, limitations and equipment. Nutrition must use the person's familiar foods/cuisines first and respect restrictions, budget and cooking preferences. Do not prescribe extreme deficits. The deterministic calorie and protein values are starting targets; explain them as estimates. JSON shape exactly: {"summary":"...","training":{"rationale":"...","notes":["..."]},"nutrition":{"rationale":"...","sampleDay":[{"meal":"Breakfast","foods":["..."],"note":"..."}],"swapIdeas":["..."]},"schedule":{"rationale":"..."},"questionsToRevisit":["..."]}. No markdown.`;const input=`ONBOARDING ANSWERS:\n${JSON.stringify(answers)}\n\nDETERMINISTIC PLAN (hard constraints):\n${JSON.stringify(plan)}`;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:env('OPENAI_PLAN_MODEL')||'gpt-5.6-terra',instructions,input,max_output_tokens:1800})});let j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||'AI planning failed.'),{status:502});return parseJson(outputText(j))}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers});if(req.method!=='POST')return json(405,{ok:false,error:'Method not allowed'});try{const u=await user(req),body=await req.json().catch(()=>({})),answers=body.answers,deterministicPlan=body.deterministicPlan;if(!answers||!deterministicPlan)return json(400,{ok:false,error:'Onboarding answers and deterministic plan are required.'});await rest('onboarding_answers?on_conflict=user_id',{method:'POST',body:{user_id:u.id,answers,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});let ai=await aiPlan(answers,deterministicPlan),plan={...deterministicPlan,ai};await rest('user_plans',{method:'POST',body:{user_id:u.id,kind:'combined',plan,source:ai?'deterministic+ai':'deterministic',active:true},prefer:'return=minimal'});await rest('profiles?on_conflict=user_id',{method:'POST',body:{user_id:u.id,display_name:answers?.basics?.name||'',profile:{goal:answers?.basics?.goal,training:answers?.training,work:answers?.work,nutrition:answers?.nutrition},onboarding_complete:true,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'});return json(200,{ok:true,plan})}catch(e){return json((e as any)?.status||500,{ok:false,error:(e as Error)?.message||'Unexpected server error'})}});
