// Diary UI ------------------------------------------------------------------
const MEALS=['Breakfast','Lunch','Dinner','Snacks'];
function renderDiary(){let k=$('diaryDate')?.value||dkey(),t=target(k),a=totals(k),left=Math.round(t.cal-a.cal);if(!$('calRemaining'))return;$('calRemaining').textContent=left;$('calGoal').textContent=t.cal;$('calFood').textContent=Math.round(a.cal);$('calLeftSmall').textContent=left;let ms=[['Protein',a.p,t.p,'g'],['Carbs',a.c,t.c,'g'],['Fat',a.f,t.f,'g'],['Fiber',a.fiber,t.fiber,'g'],['Sodium',a.sodium,t.sodium,'mg'],['Sat fat',a.satFat,t.satFat,'g']];$('macroGrid').innerHTML=ms.map(([n,v,g,u])=>`<div class="macroLine"><label><span>${n}</span><span>${Math.round(v)} / ${Math.round(g)} ${u}</span></label><div class="track"><i style="width:${Math.min(100,g?v/g*100:0)}%"></i></div></div>`).join('');let dist=MEALS.map(m=>({m,p:mealTotals(k,m).p}));$('proteinDistribution').textContent=`Protein distribution: ${dist.map(x=>`${x.m} ${Math.round(x.p)}g`).join(' · ')}. Aim to spread protein across 3–4 meals when practical.`;
 let entries=diary(k),html='';for(const meal of MEALS){let ar=entries.filter(x=>x.meal===meal),sum=ar.reduce((z,x)=>z+foodTotals(x).cal,0);html+=`<section class="meal"><div class="mealHead"><h3>${meal} <small>${Math.round(sum)} kcal</small></h3><div class="mealActions"><button data-save-recipe="${meal}">Save meal</button><button data-add-food="${meal}">+ Food</button></div></div>${ar.length?ar.map(x=>{let q=foodTotals(x);return`<button class="foodRow" data-food-id="${esc(x.id)}" aria-label="Edit ${esc(x.name)}"><div><div class="foodName">${esc(x.name)}</div><div class="foodSub">${Math.round(x.grams)} g · P ${q.p.toFixed(1)} · C ${q.c.toFixed(1)} · F ${q.f.toFixed(1)}${x.source?` · ${esc(x.source)}`:''}</div></div><div class="foodCal">${Math.round(q.cal)}</div></button>`}).join(''):'<div class="emptyMeal">No foods logged</div>'}</section>`}$('mealList').innerHTML=html;$$('[data-add-food]').forEach(b=>b.onclick=()=>openFood(b.dataset.addFood));$$('[data-food-id]').forEach(b=>b.onclick=()=>editFoodEntry(b.dataset.foodId));$$('[data-save-recipe]').forEach(b=>b.onclick=()=>saveMealRecipe(k,b.dataset.saveRecipe));let water=+(localStorage.getItem(K.water+k)||0);$('waterText').textContent=`${water} / ${t.water} oz`}
function saveMealRecipe(k,meal){let items=diary(k).filter(x=>x.meal===meal);if(!items.length)return toast('No foods in this meal');let name=prompt('Recipe name:',meal+' meal');if(!name)return;let r=jget(K.recipes,[]);r.unshift({id:uid('recipe'),name,items:structuredClone(items),createdAt:new Date().toISOString()});jset(K.recipes,r.slice(0,100));toast('Recipe saved')}

function openFood(meal='Breakfast'){foodState={editId:null,base:null,meal};clearFoodForm();$('foodMeal').value=meal;openModal('foodDialog');foodTab('search');renderRecentFoods();renderSavedFoods();renderRecipes()}
function clearFoodForm(){['foodName','foodGrams','foodCal','foodProtein','foodCarbs','foodFat','foodFiber','foodSatFat','foodSodium'].forEach(id=>{if($(id))$(id).value=''});$('foodGrams').value=100;$('saveToMyFoods').checked=false;$('deleteFoodEntry').classList.add('hidden');$('foodSourceCard').innerHTML=''}
function foodTab(t){$$('#foodTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.tabPane').forEach(p=>p.classList.toggle('active',p.id==='foodPane-'+t));if(t!=='scan')stopBarcode()}
function myFoods(){return jget(K.foods,[])}function recentFoods(){return jget(K.recent,[])}
function recipes(){return jget(K.recipes,[])}
function setFoodBase(p){foodState.base=p;$('foodName').value=p.name||'';$('foodGrams').value=p.defaultGrams||100;updateFoodTotalsFromBase();$('foodSourceCard').innerHTML=`<div class="sourceCard"><b>${esc(p.name)}</b>${p.brand?` · ${esc(p.brand)}`:''}<br>Source: ${esc(p.source||'Manual')} · values normalized per 100 g${p.defaultGrams?` · default ${Math.round(p.defaultGrams)} g`:''}</div>`;let r=recentFoods().filter(x=>x.code!==p.code||x.name!==p.name);r.unshift(p);jset(K.recent,r.slice(0,20))}
function updateFoodTotalsFromBase(){if(!foodState.base)return;let g=+$('#foodGrams').value||100,q=g/100,p=foodState.base.per100;$('#foodCal').value=(p.cal*q).toFixed(1);$('#foodProtein').value=(p.p*q).toFixed(1);$('#foodCarbs').value=(p.c*q).toFixed(1);$('#foodFat').value=(p.f*q).toFixed(1);$('#foodFiber').value=(p.fiber*q).toFixed(1);$('#foodSatFat').value=(p.satFat*q).toFixed(1);$('#foodSodium').value=(p.sodium*q).toFixed(0)}
function per100FromForm(){let g=Math.max(.1,+$('#foodGrams').value||100),q=100/g;return{cal:(+$('#foodCal').value||0)*q,p:(+$('#foodProtein').value||0)*q,c:(+$('#foodCarbs').value||0)*q,f:(+$('#foodFat').value||0)*q,fiber:(+$('#foodFiber').value||0)*q,satFat:(+$('#foodSatFat').value||0)*q,sodium:(+$('#foodSodium').value||0)*q}}
function saveFoodEntry(){let k=$('diaryDate').value,a=diary(k),x={id:foodState.editId||uid('food'),name:$('#foodName').value.trim()||'Food',meal:$('#foodMeal').value,grams:Math.max(.1,+$('#foodGrams').value||100),per100:per100FromForm(),source:foodState.base?.source||'Manual',code:foodState.base?.code||''};if(foodState.editId)a=a.map(z=>z.id===foodState.editId?x:z);else a.push(x);saveDiary(k,a);if($('#saveToMyFoods').checked){let f=myFoods().filter(z=>z.name.toLowerCase()!==x.name.toLowerCase());f.unshift({name:x.name,brand:'',code:x.code,source:x.source,defaultGrams:x.grams,per100:x.per100});jset(K.foods,f.slice(0,300))}closeModal('foodDialog')}
function editFoodEntry(id){let x=diary($('diaryDate').value).find(z=>z.id===id);if(!x)return;foodState={editId:id,base:{name:x.name,source:x.source||'Saved entry',code:x.code||'',defaultGrams:x.grams,per100:x.per100},meal:x.meal};openModal('foodDialog');foodTab('manual');$('#foodName').value=x.name;$('#foodMeal').value=x.meal;$('#foodGrams').value=x.grams;let t=foodTotals(x);$('#foodCal').value=t.cal.toFixed(1);$('#foodProtein').value=t.p.toFixed(1);$('#foodCarbs').value=t.c.toFixed(1);$('#foodFat').value=t.f.toFixed(1);$('#foodFiber').value=t.fiber.toFixed(1);$('#foodSatFat').value=t.satFat.toFixed(1);$('#foodSodium').value=t.sodium.toFixed(0);$('#deleteFoodEntry').classList.remove('hidden');$('#foodSourceCard').innerHTML=`<div class="sourceCard">Editing saved entry · ${Math.round(x.grams)} g. Values remain normalized internally, so changing grams does not double-scale.</div>`}
function deleteFoodEntry(){if(!foodState.editId)return;let k=$('diaryDate').value;saveDiary(k,diary(k).filter(x=>x.id!==foodState.editId));closeModal('foodDialog')}
function normalizeOFF(p){let n=p.nutriments||{},num=k=>+n[k+'_100g']||0,grams=+p.serving_quantity||parseFloat(String(p.serving_size||'').match(/[\d.]+/)?.[0])||100;return{name:p.product_name||p.generic_name||'Unnamed food',brand:p.brands||'',code:p.code||'',source:'Open Food Facts',defaultGrams:grams,per100:{cal:num('energy-kcal')||(+n.energy_100g||0)/4.184,p:num('proteins'),c:num('carbohydrates'),f:num('fat'),fiber:num('fiber'),satFat:num('saturated-fat'),sodium:num('sodium')*1000},img:p.image_front_small_url||''}}
function foodResult(p){let q=p.per100.cal*(p.defaultGrams||100)/100;return`<button class="result" data-result-code="${esc(p.code||'')}" data-result-name="${esc(p.name)}"><span>${p.img?`<img src="${esc(p.img)}" alt="">`:'<span class="ph">◉</span>'}</span><span><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${Math.round(p.defaultGrams||100)} g · ${esc(p.source)}</small></span><strong>${Math.round(q)} kcal</strong></button>`}
let lastSearchProducts=[];
async function searchFood(){let q=$('foodSearchInput').value.trim();if(!q)return;$('foodSearchResults').innerHTML='<p class="muted">Searching Open Food Facts…</p>';try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',u=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=24&fields=${fields}`,r=await fetch(u),j=await r.json();lastSearchProducts=(j.products||[]).map(normalizeOFF).filter(x=>x.name);$('foodSearchResults').innerHTML=lastSearchProducts.length?lastSearchProducts.map(foodResult).join(''):'<p class="muted">No matching foods found. Try a simpler name or Manual.</p>';bindFoodResults()}catch{$('foodSearchResults').innerHTML='<p class="muted">Food search failed. Check your internet connection.</p>'}}
function bindFoodResults(){$$('#foodSearchResults .result').forEach((b,i)=>b.onclick=()=>setFoodBase(lastSearchProducts[i]))}
async function lookupBarcode(code){code=String(code||'').replace(/\D/g,'');if(!code)return setBarcodeStatus('Enter a UPC/EAN barcode.');setBarcodeStatus('Looking up '+code+' in Open Food Facts…');try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=${fields}`),j=await r.json();if(j.status===1&&j.product){setFoodBase(normalizeOFF({...j.product,code}));setBarcodeStatus('✓ Product found. Review the serving and nutrition values.');stopBarcode()}else setBarcodeStatus('✓ Barcode decoded, but no exact Open Food Facts product was found. Search by product name or use Manual.')}catch{setBarcodeStatus('Barcode lookup failed. Check your internet connection.') }}
function setBarcodeStatus(t){$('#barcodeStatus').textContent=t}
const SCANNER_URL='https://cdn.jsdelivr.net/gh/mebjas/html5-qrcode@d505e505022cbb6680e6c8babd964e3be9a2d586/minified/html5-qrcode.min.js';
async function ensureScanner(){if(window.Html5Qrcode)return true;return new Promise(resolve=>{let s=document.createElement('script');s.src=SCANNER_URL;s.onload=()=>resolve(!!window.Html5Qrcode);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
let nativeBarcodeStream=null,nativeBarcodeTimer=null;
async function nativeBarcodeDetector(){if(!('BarcodeDetector' in window))return null;try{let wanted=['ean_13','ean_8','upc_a','upc_e'];let supported=BarcodeDetector.getSupportedFormats?await BarcodeDetector.getSupportedFormats():wanted,formats=wanted.filter(x=>supported.includes(x));return new BarcodeDetector(formats.length?{formats}:undefined)}catch{return null}}
async function startBarcode(){await stopBarcode();if(!navigator.mediaDevices?.getUserMedia){setBarcodeStatus('Live camera is blocked in this in-app browser. Open the planner in Safari or the Home Screen app, then retry. Photo barcode scanning can still be used here.');return}let native=await nativeBarcodeDetector();if(native){try{let v=document.createElement('video');v.playsInline=true;v.muted=true;v.style.width='100%';v.style.maxHeight='260px';v.style.objectFit='cover';$('#barcodeReader').appendChild(v);nativeBarcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=nativeBarcodeStream;await v.play();setBarcodeStatus('Camera ready. Center the full UPC/EAN barcode and hold steady.');nativeBarcodeTimer=setInterval(async()=>{try{let r=await native.detect(v),code=r?.[0]?.rawValue;if(code){await stopBarcode();lookupBarcode(code)}}catch{}},300);return}catch{await stopBarcode()}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load. Check internet and retry.');return}try{barcodeScanner=new Html5Qrcode('barcodeReader');await barcodeScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:140},formatsToSupport:window.Html5QrcodeSupportedFormats?[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]:undefined},txt=>lookupBarcode(txt),()=>{});setBarcodeStatus('Camera ready. Center the full barcode in the box and hold steady.')}catch(e){setBarcodeStatus('Live scan could not start. Use Safari/Home Screen or scan a barcode photo.') }}
async function stopBarcode(){if(nativeBarcodeTimer){clearInterval(nativeBarcodeTimer);nativeBarcodeTimer=null}if(nativeBarcodeStream){nativeBarcodeStream.getTracks().forEach(t=>t.stop());nativeBarcodeStream=null}if(barcodeScanner){try{if(barcodeScanner.isScanning)await barcodeScanner.stop();await barcodeScanner.clear()}catch{}barcodeScanner=null}if($('#barcodeReader'))$('#barcodeReader').innerHTML=''}
async function scanBarcodePhoto(file){if(!file)return;await stopBarcode();setBarcodeStatus('Reading barcode from photo…');let native=await nativeBarcodeDetector();if(native){try{let bmp=await createImageBitmap(file),r=await native.detect(bmp),code=r?.[0]?.rawValue;bmp.close?.();if(code){$('#barcodePhoto').value='';return lookupBarcode(code)}}catch{}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load.');$('#barcodePhoto').value='';return}try{barcodeScanner=new Html5Qrcode('barcodeReader');let txt=await barcodeScanner.scanFile(file,true);await lookupBarcode(txt)}catch{setBarcodeStatus('No UPC/EAN barcode could be read. Retake the photo closer, sharp, and with the entire barcode visible.')}finally{try{await barcodeScanner?.clear()}catch{}barcodeScanner=null;$('#barcodePhoto').value=''}}
function renderRecentFoods(){let a=recentFoods();$('#recentFoods').innerHTML=a.slice(0,12).map((x,i)=>`<button data-recent="${i}">${esc(x.name)}</button>`).join('');$$('[data-recent]').forEach(b=>b.onclick=()=>setFoodBase(a[+b.dataset.recent]))}
function renderSavedFoods(){let q=($('#savedFoodSearch')?.value||'').toLowerCase(),a=myFoods().filter(x=>!q||x.name.toLowerCase().includes(q));$('#savedFoodResults').innerHTML=a.length?a.map((x,i)=>`<button class="result" data-saved="${i}"><span class="ph">★</span><span><b>${esc(x.name)}</b><small>${esc(x.source||'Saved')} · ${Math.round(x.defaultGrams||100)} g</small></span><strong>${Math.round(x.per100.cal*(x.defaultGrams||100)/100)} kcal</strong></button>`).join(''):'<p class="muted">No saved foods yet.</p>';$$('[data-saved]').forEach(b=>b.onclick=()=>setFoodBase(a[+b.dataset.saved]))}
function renderRecipes(){let a=recipes();$('#recipeResults').innerHTML=a.length?a.map((r,i)=>`<button class="result" data-recipe="${i}"><span class="ph">🥣</span><span><b>${esc(r.name)}</b><small>${r.items.length} foods · one-tap log</small></span><strong>${Math.round(r.items.reduce((z,x)=>z+foodTotals(x).cal,0))} kcal</strong></button>`).join(''):'<p class="muted">No saved recipes yet.</p>';$$('[data-recipe]').forEach(b=>b.onclick=()=>{let r=a[+b.dataset.recipe],k=$('diaryDate').value,meal=foodState.meal||'Breakfast',items=r.items.map(x=>({...structuredClone(x),id:uid('food'),meal}));saveDiary(k,[...diary(k),...items]);closeModal('foodDialog');toast('Recipe logged')})}
