// Init ----------------------------------------------------------------------
function init(){migrateLegacy();freezePastSnapshots();let now=new Date();calView=new Date(now.getFullYear(),now.getMonth(),1);selectedDate=dkey();$('#diaryDate').value=dkey();$('#checkDate').value=dkey();renderAll();
 $$('.bottomNav button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('#todayQuick').onclick=()=>{let n=new Date();calView=new Date(n.getFullYear(),n.getMonth(),1);selectedDate=dkey();page('calendar');renderCalendar()};$('#calPrev').onclick=()=>{calView.setMonth(calView.getMonth()-1);renderCalendar()};$('#calNext').onclick=()=>{calView.setMonth(calView.getMonth()+1);renderCalendar()};$('#diaryPrev').onclick=()=>{let k=addDays($('#diaryDate').value,-1);$('#diaryDate').value=k;renderDiary()};$('#diaryNext').onclick=()=>{let k=addDays($('#diaryDate').value,1);$('#diaryDate').value=k;renderDiary()};$('#diaryDate').onchange=renderDiary;$('#waterPlus').onclick=()=>{let k=$('#diaryDate').value;localStorage.setItem(K.water+k,String(+(localStorage.getItem(K.water+k)||0)+8));renderDiary()};$('#waterMinus').onclick=()=>{let k=$('#diaryDate').value;localStorage.setItem(K.water+k,String(Math.max(0,+(localStorage.getItem(K.water+k)||0)-8)));renderDiary()};
 $('#saveCheckin').onclick=()=>{let k=$('#checkDate').value,b=bodyLog();b[k]={weight:+$('#checkWeight').value||null,waist:+$('#checkWaist').value||null,bf:+$('#checkBf').value||null};saveBodyLog(b);renderProgress();toast('Check-in saved')};$('#weightRange').onchange=renderWeightChart;
 $$('[data-open]').forEach(b=>b.onclick=()=>{let t=b.dataset.open;if(t==='profile'){fillProfileForm();openModal('profileDialog')}if(t==='bellevue')openBellevue();if(t==='nutrition'){fillNutritionForm();openModal('nutritionDialog')}if(t==='backup')openModal('backupDialog');if(t==='about')openModal('aboutDialog')});$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener('keydown',e=>{let m=$$('.modal.open').at(-1);if(e.key==='Escape'&&m){closeModal(m.id);return}if(e.key==='Tab'&&m){let f=[...m.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(x=>x.offsetParent!==null);if(!f.length)return;let first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
 $('#useFrancis').onclick=()=>{seedFrancis();fillProfileForm()};$('#useCustom').onclick=()=>{jset(K.profile,blankProfile());fillProfileForm()};$('#resetFrancis').onclick=()=>{jset(K.profile,francisProfile());fillProfileForm()};$('#saveProfile').onclick=saveProfileForm;
 $('#bMonth').onchange=e=>loadBDraft(e.target.value);$('#bPhoto').onchange=e=>{bPhotoFile=e.target.files[0]||null;if(bPhotoFile){let u=URL.createObjectURL(bPhotoFile);$('#bPhotoPreview').src=u;$('#bPhotoPreview').classList.remove('hidden')}};$('#bRotate').onclick=()=>{bRotation=(bRotation+90)%360;$('#bPhotoPreview').style.transform=`rotate(${bRotation}deg)`};$('#bScan').onclick=scanSchedulePhoto;$('#bCopyPrev').onclick=()=>{let ym=$('#bMonth').value,d=date(ym+'-15');d.setMonth(d.getMonth()-1);let prev=variableMonth(ymk(d));if(!prev)return toast('Previous month not saved');let days=daysInMonth(ym);for(let i=1;i<=days;i++)bDraft[i]=prev[i]||'?';renderBReview()};$('#bResetUnknown').onclick=()=>{for(const k of Object.keys(bDraft||{}))bDraft[k]='?';renderBReview()};$('#bDelete').onclick=()=>{if(confirm('Delete this saved month?')){localStorage.removeItem(K.bellevue+$('#bMonth').value);loadBDraft($('#bMonth').value);renderAll()}};$('#bDiscard').onclick=()=>closeModal('bellevueDialog');$('#cancelBellevue').onclick=()=>closeModal('bellevueDialog');$('#bSave').onclick=saveBMonth;
 $('#saveNutrition').onclick=saveNutritionForm;$('#applyCalorieRec').onclick=applyCalorieRecommendation;
 $('#exportData').onclick=exportBackup;$('#importFile').onchange=e=>importBackup(e.target.files[0]);$('#deleteAllData').onclick=deleteAllData;
 $$('#foodTabs button').forEach(b=>b.onclick=()=>foodTab(b.dataset.tab));$('#foodSearchBtn').onclick=searchFood;$('#foodSearchInput').onkeydown=e=>{if(e.key==='Enter')searchFood()};$('#foodGrams').oninput=()=>{if(foodState.base)updateFoodTotalsFromBase()};$('#saveFoodEntry').onclick=saveFoodEntry;$('#deleteFoodEntry').onclick=deleteFoodEntry;$('#savedFoodSearch').oninput=renderSavedFoods;$('#startBarcode').onclick=startBarcode;$('#stopBarcode').onclick=stopBarcode;$('#barcodePhoto').onchange=e=>scanBarcodePhoto(e.target.files[0]);$('#barcodeLookup').onclick=()=>lookupBarcode($('#barcodeManual').value);$('#barcodeManual').onkeydown=e=>{if(e.key==='Enter')lookupBarcode(e.target.value)};
 if(!profile()){fillProfileForm();openModal('profileDialog')}setupPWA()}

document.addEventListener('DOMContentLoaded',init);
