// Nutrition / diary ---------------------------------------------------------
function nutritionDefaults(){return{gymCal:2200,restCal:2000,protein:150,fat:70,fiber:30,sodium:2300,satFat:20,water:96,goalWeight:0,goalBf:0,planStart:dkey()}}
function nutrition(){return{...nutritionDefaults(),...jget(K.nutrition,{})}}
function saveNutritionObj(x){jset(K.nutrition,x)}
function target(k){let n=nutrition(),past=k<=dkey(),gym=!!completedOn(k)||(past?!!snapshots()[k]?.planned:isScheduled(k)),cal=gym?+n.gymCal:+n.restCal,p=+n.protein,f=+n.fat,c=Math.max(0,Math.round((cal-p*4-f*9)/4));return{cal,p,c,f,fiber:+n.fiber,sodium:+n.sodium,satFat:+n.satFat,water:+n.water,gym}}
function diary(k){return jget(K.diary+k,[])}function saveDiary(k,a){jset(K.diary+k,a);renderDiary()}
function foodTotals(x){let q=(+x.grams||0)/100,p=x.per100||{};return{cal:(+p.cal||0)*q,p:(+p.p||0)*q,c:(+p.c||0)*q,f:(+p.f||0)*q,fiber:(+p.fiber||0)*q,satFat:(+p.satFat||0)*q,sodium:(+p.sodium||0)*q}}
function totals(k){return diary(k).reduce((a,x)=>{let t=foodTotals(x);for(const z of Object.keys(a))a[z]+=t[z]||0;return a},{cal:0,p:0,c:0,f:0,fiber:0,satFat:0,sodium:0})}
function mealTotals(k,meal){return diary(k).filter(x=>x.meal===meal).reduce((a,x)=>{let t=foodTotals(x);a.cal+=t.cal;a.p+=t.p;return a},{cal:0,p:0})}
function bodyLog(){return jget(K.body,{})}function saveBodyLog(x){jset(K.body,x)}
function loggedDates(){let out=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(K.diary)&&diary(k.slice(K.diary.length)).length)out.push(k.slice(K.diary.length))}return out.sort()}
function adherenceFor(start,end){let dates=[],ok=0;for(let k=start;k<=end;k=addDays(k,1)){let t=totals(k).cal;if(t>0){dates.push(k);let g=target(k).cal;if(Math.abs(t-g)/g<=.10)ok++}}return{logged:dates.length,onTarget:ok,rate:dates.length?ok/dates.length:0}}
function weightValues(start,end){let b=bodyLog(),a=[];for(let k=start;k<=end;k=addDays(k,1))if(+b[k]?.weight)a.push(+b[k].weight);return a}
function avgWeight(start,end){let a=weightValues(start,end);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function latestMetricBefore(metric,before,days=21){let b=bodyLog(),best=null;for(const [k,x] of Object.entries(b)){if(k<=before&&diffDays(before,k)<=days&&+x[metric]&&(best==null||k>best.k))best={k,v:+x[metric]}}return best}
function bodyRecommendation(){let today=dkey(),curStart=addDays(today,-6),prevStart=addDays(today,-13),prevEnd=addDays(today,-7),curA=adherenceFor(curStart,today),prevA=adherenceFor(prevStart,prevEnd),cw=avgWeight(curStart,today),pw=avgWeight(prevStart,prevEnd),curW=weightValues(curStart,today),prevW=weightValues(prevStart,prevEnd),loggedEnough=curA.logged>=5&&prevA.logged>=5&&curW.length>=3&&prevW.length>=3&&cw&&pw,ad=(curA.rate+prevA.rate)/2,loss=loggedEnough?(pw-cw)/pw*100:null,waistNow=latestMetricBefore('waist',today,10),waistPrev=latestMetricBefore('waist',prevEnd,14),text='Log at least 5 calorie days and 3+ morning weights in each of two consecutive weeks before changing calories.',delta=0;
 if(loggedEnough){if(waistNow&&waistPrev&&waistPrev.v-waistNow.v>=.25&&Math.abs(loss)<.15){text='Weight is fairly stable but waist is down at least 0.25 in. Hold calories — body composition is improving.'}else if(ad<.8){text=`Logging/on-target adherence is ${Math.round(ad*100)}%. Hold calories and improve consistency before changing the target.`}else if(loss<.15){text='Weight loss is below the target range with good adherence. Reduce gym-day and recovery calories by 100.';delta=-100}else if(loss>.75){text='Weight is falling faster than 0.75% per week. Add 100 calories to gym-day and recovery targets.';delta=100}else{text='Weight trend is in the target range. Keep calories unchanged.'}}
 return{text,delta,adherence:ad,loss,cw,pw,curA,prevA}}
