// Variable work schedule editor / OCR --------------------------------------
function openBellevue(){let ym=dkey().slice(0,7);$('#bMonth').value=ym;loadBDraft(ym);openModal('bellevueDialog')}
function loadBDraft(ym){let saved=variableMonth(ym),days=daysInMonth(ym);bDraft={};for(let i=1;i<=days;i++)bDraft[i]=saved?.[i]||'?';renderBReview();renderSavedMonths();bPhotoFile=null;bRotation=0;$('#bPhotoPreview').classList.add('hidden');$('#bScanStatus').textContent='Missing days are UNKNOWN and are never treated as days off. Review every code before saving.'}
function renderBReview(){if(!bDraft)return;$('#bReview').innerHTML=Object.entries(bDraft).map(([n,c])=>`<button data-bday="${n}" class="${c==='?'?'q':c.toLowerCase()}">${n}<br>${c}</button>`).join('');$$('[data-bday]').forEach(b=>b.onclick=()=>{let n=+b.dataset.bday,seq=['?','X','D','H'],cur=bDraft[n]||'?';bDraft[n]=seq[(seq.indexOf(cur)+1)%seq.length];renderBReview()})}
function saveBMonth(){let ym=$('#bMonth').value;if(!ym||!bDraft)return;jset(K.bellevue+ym,bDraft);closeModal('bellevueDialog');renderAll();toast('Schedule month saved')}
function renderSavedMonths(){let a=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(K.bellevue))a.push(k.slice(K.bellevue.length))}a.sort();$('#savedMonths').innerHTML=a.map(ym=>`<button data-savedmonth="${ym}">${ym}</button>`).join('');$$('[data-savedmonth]').forEach(b=>b.onclick=()=>{$('#bMonth').value=b.dataset.savedmonth;loadBDraft(b.dataset.savedmonth)})}
async function rotatedPhotoBlob(){if(!bPhotoFile||!bRotation)return bPhotoFile;let bmp=await createImageBitmap(bPhotoFile),c=document.createElement('canvas'),ctx=c.getContext('2d'),r=bRotation%360;if(r===90||r===270){c.width=bmp.height;c.height=bmp.width}else{c.width=bmp.width;c.height=bmp.height}ctx.translate(c.width/2,c.height/2);ctx.rotate(r*Math.PI/180);ctx.drawImage(bmp,-bmp.width/2,-bmp.height/2);return new Promise(res=>c.toBlob(res,'image/jpeg',.92))}
async function loadTesseract(){if(window.Tesseract)return true;return new Promise(resolve=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=()=>resolve(!!window.Tesseract);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function scanSchedulePhoto(){if(!bPhotoFile)return $('#bScanStatus').textContent='Choose a schedule photo first.';if(!(await loadTesseract()))return $('#bScanStatus').textContent='OCR assistant could not load. Use the manual review grid.';$('#bScan').disabled=true;$('#bScanStatus').textContent='Scanning photo locally in this browser. The photo is not saved…';try{let blob=await rotatedPhotoBlob(),res=await Tesseract.recognize(blob,'eng',{logger:m=>{if(m.status==='recognizing text')$('#bScanStatus').textContent=`Scanning… ${Math.round((m.progress||0)*100)}%`}}),words=res.data.words||[],name=(profile()?.name||'').toLowerCase().split(/\s+/)[0],hit=words.find(w=>name&&String(w.text).toLowerCase().includes(name)),symbols=[];if(hit){let cy=(hit.bbox.y0+hit.bbox.y1)/2,h=Math.max(18,hit.bbox.y1-hit.bbox.y0);symbols=words.filter(w=>{let y=(w.bbox.y0+w.bbox.y1)/2,t=String(w.text).trim().toUpperCase().replace(/[^XDH]/g,'');return Math.abs(y-cy)<h*1.2&&/^[XDH]$/.test(t)&&w.bbox.x0>hit.bbox.x1}).sort((a,b)=>a.bbox.x0-b.bbox.x0).map(w=>String(w.text).trim().toUpperCase().replace(/[^XDH]/g,''))}let days=daysInMonth($('#bMonth').value);if(symbols.length>=Math.min(days-3,20)){for(let i=1;i<=days;i++)if(symbols[i-1])bDraft[i]=symbols[i-1];renderBReview();$('#bScanStatus').textContent=`Best-effort scan found ${symbols.length} work/off symbols in ${esc(profile()?.name||'the selected')} row. Review every date before Save.`}else $('#bScanStatus').textContent=`OCR found the name row but only ${symbols.length} clear X/D/H symbols. No automatic overwrite was made. Use the review grid.`}catch(e){$('#bScanStatus').textContent='OCR could not reliably read this photo. Use the review grid; the photo is not stored.'}finally{$('#bScan').disabled=false}}
