// Training ------------------------------------------------------------------
function trainingDatesAround(){let today=dkey(),start=addDays(today,-90),end=addDays(today,120),a=suggestedTrainingDates(start,end),h=history().filter(x=>x.date>=start&&x.date<=end).map(x=>x.date),o=Object.entries(overrides()).filter(([,v])=>v.action==='train').map(([k])=>k);return [...new Set([...a,...h,...o])].sort()}
function initialTrainingDate(){let today=dkey(),dates=trainingDatesAround();if(completedOn(today)||dates.includes(today))return today;return dates.find(k=>k>today)||today}
function prevTraining(k){let a=trainingDatesAround().filter(x=>x<k);return a[a.length-1]||k}function nextTraining(k){return trainingDatesAround().find(x=>x>k)||k}
function openTrainingDate(k){trainingDate=k;page('training');renderTraining()}
function sessionDraft(k,wi){let ds=drafts();if(ds[k]&&ds[k].workoutIndex===wi)return ds[k];let done=completedOn(k);if(done)return structuredClone(done);let w=WORKOUTS[wi];let ex=w.ex.map(meta=>{let last=exposures(meta.name,k)[0],guess=last?.ex?.sets?.find(s=>+s.w)?.w||'';return{name:meta.name,sets:Array.from({length:meta.sets},()=>({w:guess,r:'',rir:''}))}});return{id:uid('session'),date:k,workoutIndex:wi,completed:false,exercises:ex}}
function exposures(name,before='9999-12-31'){return history().filter(s=>s.completed&&s.date<before).sort((a,b)=>b.date.localeCompare(a.date)).map(s=>({session:s,ex:s.exercises.find(e=>e.name===name)})).filter(x=>x.ex)}
function e1rm(ex){return Math.max(0,...(ex?.sets||[]).map(s=>(+s.w||0)*(1+(+s.r||0)/30)))}
function sessionVolume(s){return(s.exercises||[]).reduce((sum,e)=>sum+(e.sets||[]).reduce((a,z)=>a+(+z.w||0)*(+z.r||0),0),0)}
function avgRIR(ex){let a=(ex.sets||[]).filter(s=>s.rir!==''&&s.rir!=null&&!Number.isNaN(+s.rir));return a.length?a.reduce((z,s)=>z+(+s.rir),0)/a.length:null}
function exerciseAdvice(meta,current,before){let sets=(current?.sets||[]).filter(s=>+s.r>0),min=sets.length?Math.min(...sets.map(s=>+s.r)):0,rir=avgRIR(current),maxW=Math.max(0,...sets.map(s=>+s.w||0)),prev=exposures(meta.name,before),p1=prev[0]?.ex,p2=prev[1]?.ex;
 if(sets.length<meta.sets)return `Complete all ${meta.sets} working sets before increasing load.`;
 let curE=e1rm(current),p1e=e1rm(p1),p2e=e1rm(p2);
 if(p1&&p2&&curE>0&&p1e>0&&p2e>0&&curE<p1e*.96&&p1e<p2e*.97&&(rir==null||rir<=1))return 'Fatigue flag: performance has declined across 3 distinct exposures. Reduce load 5–10% or remove one set next time, then rebuild.';
 if(rir!=null&&rir<.75)return 'Effort was too close to failure overall. Hold the load next time and aim for about 1–2 RIR on compounds.';
 if(min>=meta.hi&&(rir==null||rir>=1)){if(meta.inc>0)return `Progress: add ${meta.inc} lb next time and restart near ${meta.lo} reps.`;return 'Progress by making the movement harder or adding reps with clean form.'}
 if(min>=meta.lo)return `Keep ${maxW||'the same'}${maxW?' lb':''} and add about 1 rep where possible until every set reaches ${meta.hi}.`;
 return `Repeat or reduce the load 5–10% until every set reaches at least ${meta.lo} reps with controlled form.`}
function collectTrainingInputs(k,wi){let s=sessionDraft(k,wi),w=WORKOUTS[wi];s.exercises=w.ex.map((meta,ei)=>({name:meta.name,sets:Array.from({length:meta.sets},(_,si)=>({w:$(`[data-e="${ei}"][data-s="${si}"][data-f="w"]`)?.value||'',r:$(`[data-e="${ei}"][data-s="${si}"][data-f="r"]`)?.value||'',rir:$(`[data-e="${ei}"][data-s="${si}"][data-f="rir"]`)?.value||''}))}));return s}
function saveTrainingDraft(){if(!trainingDate)return;let wi=completedOn(trainingDate)?.workoutIndex??projectedWorkoutIndex(trainingDate),s=collectTrainingInputs(trainingDate,wi),d=drafts();d[trainingDate]=s;saveDrafts(d)}
function completeTraining(){let wi=completedOn(trainingDate)?.workoutIndex??projectedWorkoutIndex(trainingDate),s=collectTrainingInputs(trainingDate,wi);s.completed=true;s.completedAt=new Date().toISOString();let h=history().filter(x=>x.date!==trainingDate);h.push(s);saveHistory(h.sort((a,b)=>a.date.localeCompare(b.date)));let d=drafts();delete d[trainingDate];saveDrafts(d);freezePastSnapshots();toast('Workout saved + analyzed');renderAll();renderTraining()}
function trainingAdherence(){freezePastSnapshots();let s=snapshots(),today=dkey(),start=addDays(today,-27),planned=Object.keys(s).filter(k=>k>=start&&k<=today&&s[k].planned),done=history().filter(x=>x.completed&&x.date>=start&&x.date<=today);return{planned:planned.length,done:done.length,rate:planned.length?Math.round(done.length/planned.length*100):0}}
function weeklyTrainingStats(){let h=history().filter(x=>x.completed),weeks=[];for(let w=5;w>=0;w--){let end=addDays(dkey(),-w*7),start=addDays(end,-6),ss=h.filter(x=>x.date>=start&&x.date<=end),vol=ss.reduce((a,s)=>a+sessionVolume(s),0),hard=ss.reduce((a,s)=>a+s.exercises.reduce((q,e)=>q+e.sets.filter(z=>+z.r>0&&(z.rir===''||+z.rir<=3)).length,0),0);weeks.push({label:fmt(end,{month:'short',day:'numeric'}),vol,hard})}return weeks}
function renderTraining(){let root=$('trainingRoot');if(!root)return;if(!profile()){root.innerHTML='<div class="card"><p>Set up a profile first.</p></div>';return}if(!trainingDate)trainingDate=initialTrainingDate();let comp=completedOn(trainingDate),scheduled=isScheduled(trainingDate)||overrides()[trainingDate]?.action==='train',wi=comp?.workoutIndex??projectedWorkoutIndex(trainingDate),w=WORKOUTS[wi],s=sessionDraft(trainingDate,wi),adh=trainingAdherence(),today=dkey(),isToday=trainingDate===today,status=comp?'COMPLETED':scheduled?'SCHEDULED':'MANUAL / UNSCHEDULED';
 let exhtml=s.exercises.map((ex,ei)=>{let meta=w.ex[ei],prevObj=exposures(meta.name,trainingDate)[0],prev=prevObj?.ex,lastTxt=prev?prev.sets.filter(z=>+z.r).map(z=>`${z.w||'BW'}×${z.r}${z.rir!==''&&z.rir!=null?` @${z.rir}RIR`:''}`).join(' · '):'No prior exposure',advice=comp?exerciseAdvice(meta,ex,trainingDate):(prevObj?exerciseAdvice(meta,prevObj.ex,prevObj.session.date):'Complete this exercise to start progression coaching.');return `<article class="exerciseCard"><div class="exerciseHead"><div><h3>${esc(meta.name)}</h3><p>${meta.sets}×${meta.lo}–${meta.hi} · ${meta.inc?`+${meta.inc} lb progression`:'bodyweight progression'} · compounds generally 1–2 RIR</p></div><button class="historyBtn" data-history="${ei}">History</button></div><div class="foodSub"><b>Last:</b> ${esc(lastTxt)}</div><div class="setHead"><span>Set</span><span>Weight</span><span>Reps</span><span>RIR</span></div>${ex.sets.map((z,si)=>`<div class="setRow"><b>${si+1}</b><input data-e="${ei}" data-s="${si}" data-f="w" type="number" step="2.5" inputmode="decimal" value="${esc(z.w)}" aria-label="${esc(meta.name)} set ${si+1} weight"><input data-e="${ei}" data-s="${si}" data-f="r" type="number" inputmode="numeric" value="${esc(z.r)}" aria-label="${esc(meta.name)} set ${si+1} reps"><input data-e="${ei}" data-s="${si}" data-f="rir" type="number" step="0.5" min="0" max="5" inputmode="decimal" value="${esc(z.rir)}" aria-label="${esc(meta.name)} set ${si+1} reps in reserve"></div>`).join('')}<div class="exerciseAdvice"><b>Coach:</b> ${esc(advice)}</div><div id="hist-${ei}" class="historyPanel hidden">${historyRows(meta.name,trainingDate)}</div></article>`}).join('');
 root.innerHTML=`<div class="trainNav"><button id="trainPrev" aria-label="Previous training day">‹</button><div><small>${status}</small><h2 id="trainingHeading">${fmt(trainingDate)}</h2><p>${w.name} · ${w.focus} · ${workText(trainingDate)}</p></div><button id="trainNext" aria-label="Next training day">›</button></div><div class="trainTools"><button id="trainToday">Today</button>${!isToday&&!comp?'<button id="moveWorkout">Move workout</button>':''}${!comp?'<button id="skipWorkout">Skip this date</button>':''}${!isScheduled(today)&&!completedOn(today)?'<button id="trainTodayManual">Train today</button>':''}</div><div class="coachCard"><h3>Progress Coach</h3><p>${overallTrainingCoach(adh)}</p></div><div class="trainStats"><div><b>${adh.done}</b><small>sessions / 4 wk</small></div><div><b>${adh.rate}%</b><small>adherence</small></div><div><b>${Math.round(sessionVolume(s)).toLocaleString()}</b><small>session volume</small></div><div><b>${recentPRCount()}</b><small>recent e1RM PRs</small></div></div><div id="trainingSwipe">${exhtml}</div><div class="trainActionGrid"><button id="saveTrain">Save draft</button><button id="completeTrain" class="primary">${comp?'Update completed workout':'Complete workout'}</button></div><div class="trainingChartWrap"><h3>Estimated strength trend</h3><select id="exerciseChartSelect" class="trainingSelect">${allExerciseNames().map(n=>`<option ${n===w.ex[0].name?'selected':''}>${esc(n)}</option>`).join('')}</select><svg id="strengthChart" class="chart" viewBox="0 0 640 220"></svg></div><div class="trainingChartWrap"><h3>Weekly training load</h3><svg id="volumeChart" class="chart" viewBox="0 0 640 220"></svg></div>`;
 bindTraining();renderStrengthChart($('#exerciseChartSelect').value);renderVolumeChart()}
function overallTrainingCoach(adh){let h=history(),msg=h.length?`You have ${h.length} completed sessions saved. `:'Complete your first workout to establish a baseline. ';if(adh.planned)msg+=`4-week adherence is ${adh.rate}%. `;let wk=weeklyTrainingStats(),last=wk[wk.length-1],prev=wk[wk.length-2];if(prev?.vol&&last?.vol<prev.vol*.8)msg+='Recent volume is down more than 20%; check recovery, missed sets, or schedule load. ';else if(prev?.vol&&last?.vol>prev.vol*1.2)msg+='Recent volume is rising quickly; keep sleep and recovery high. ';msg+='Progression decisions use reps, load, RIR and distinct prior exposures.';return msg}
function historyRows(name,before){let a=exposures(name,before).slice(0,8);if(!a.length)return'<p class="muted">No completed history yet.</p>';return a.map(x=>`<div class="histRow"><span>${fmt(x.session.date,{month:'short',day:'numeric'})}</span><b>${x.ex.sets.filter(z=>+z.r).map(z=>`${z.w||'BW'}×${z.r}`).join(' · ')}</b><small>e1RM ${e1rm(x.ex)?e1rm(x.ex).toFixed(0):'—'}</small></div>`).join('')}
function bindTraining(){
 $('#trainPrev').onclick=()=>{autoSaveTraining();trainingDate=prevTraining(trainingDate);renderTraining()};$('#trainNext').onclick=()=>{autoSaveTraining();trainingDate=nextTraining(trainingDate);renderTraining()};$('#trainToday').onclick=()=>{autoSaveTraining();trainingDate=initialTrainingDate();renderTraining()};$('#saveTrain').onclick=()=>{saveTrainingDraft();toast('Draft saved')};$('#completeTrain').onclick=completeTraining;
 let sk=$('#skipWorkout');if(sk)sk.onclick=()=>{let o=overrides();o[trainingDate]={action:'skip',createdAt:new Date().toISOString()};saveOverrides(o);let d=drafts();delete d[trainingDate];saveDrafts(d);toast('Date skipped; workout rotation did not advance');trainingDate=nextTraining(trainingDate);renderAll();renderTraining()};
 let mv=$('#moveWorkout');if(mv)mv.onclick=()=>{let to=prompt('Move this workout to date (YYYY-MM-DD):',addDays(trainingDate,1));if(!/^\d{4}-\d{2}-\d{2}$/.test(to||''))return;let o=overrides();o[trainingDate]={action:'skip',movedTo:to};o[to]={action:'train',movedFrom:trainingDate};saveOverrides(o);toast('Workout moved');trainingDate=to;renderAll();renderTraining()};
 let tt=$('#trainTodayManual');if(tt)tt.onclick=()=>{let o=overrides();o[dkey()]={action:'train',createdAt:new Date().toISOString()};saveOverrides(o);trainingDate=dkey();renderAll();renderTraining()};
 $$('[data-history]').forEach(b=>b.onclick=()=>$('#hist-'+b.dataset.history).classList.toggle('hidden'));$('#exerciseChartSelect').onchange=e=>renderStrengthChart(e.target.value);
 $('#trainingSwipe').addEventListener('input',debounce(autoSaveTraining,250));let sx=null,blocked=false;$('#trainingSwipe').addEventListener('touchstart',e=>{blocked=!!e.target.closest('input,button,select,textarea');if(!blocked)sx=e.changedTouches[0].clientX},{passive:true});$('#trainingSwipe').addEventListener('touchend',e=>{if(blocked||sx==null){sx=null;return}let dx=e.changedTouches[0].clientX-sx;sx=null;if(Math.abs(dx)<65)return;autoSaveTraining();trainingDate=dx<0?nextTraining(trainingDate):prevTraining(trainingDate);renderTraining()},{passive:true})}
function autoSaveTraining(){try{saveTrainingDraft()}catch{}}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function allExerciseNames(){return [...new Set(WORKOUTS.flatMap(w=>w.ex.map(e=>e.name)))]}
function renderStrengthChart(name){let svg=$('#strengthChart');if(!svg)return;let a=history().filter(s=>s.completed).map(s=>({date:s.date,ex:s.exercises.find(e=>e.name===name)})).filter(x=>x.ex&&e1rm(x.ex)>0).slice(-10);drawLineChart(svg,a.map(x=>({label:fmt(x.date,{month:'short',day:'numeric'}),v:e1rm(x.ex)})),'lb')}
function renderVolumeChart(){let svg=$('#volumeChart');if(!svg)return;let a=weeklyTrainingStats(),max=Math.max(1,...a.map(x=>x.vol)),bw=70,g=30;svg.innerHTML=a.map((x,i)=>{let bh=x.vol/max*145,xx=35+i*(bw+g),yy=175-bh;return`<rect x="${xx}" y="${yy}" width="${bw}" height="${bh}" rx="6" fill="#2563eb"/><text x="${xx+bw/2}" y="195" text-anchor="middle" fill="#667085" font-size="16">${esc(x.label)}</text><text x="${xx+bw/2}" y="${Math.max(18,yy-5)}" text-anchor="middle" fill="#667085" font-size="14">${Math.round(x.vol/1000)}k · ${x.hard} sets</text>`}).join('')}
function drawLineChart(svg,pts,unit=''){if(!pts.length){svg.innerHTML='<text x="320" y="110" text-anchor="middle" fill="#667085" font-size="18">No data yet</text>';return}let vals=pts.map(x=>x.v),lo=Math.min(...vals)*.96,hi=Math.max(...vals)*1.04;if(hi===lo){hi+=1;lo-=1}let X=i=>35+(pts.length===1?280:i/(pts.length-1)*570),Y=v=>20+(hi-v)/(hi-lo)*150;svg.innerHTML=`<polyline fill="none" stroke="#2563eb" stroke-width="4" points="${pts.map((p,i)=>`${X(i)},${Y(p.v)}`).join(' ')}"/>`+pts.map((p,i)=>`<circle cx="${X(i)}" cy="${Y(p.v)}" r="5" fill="#2563eb"/><text x="${X(i)}" y="205" text-anchor="middle" fill="#667085" font-size="13">${esc(p.label)}</text><text x="${X(i)}" y="${Math.max(15,Y(p.v)-9)}" text-anchor="middle" fill="#667085" font-size="13">${Math.round(p.v)}${unit}</text>`).join('')}
function recentPRCount(){let h=history();if(h.length<2)return 0;let cur=h[h.length-1],past=h.slice(0,-1),n=0;for(const ex of cur.exercises){let old=Math.max(0,...past.map(s=>e1rm(s.exercises.find(e=>e.name===ex.name))));if(e1rm(ex)>old&&e1rm(ex)>0)n++}return n}
