const SUPABASE_URL=()=>process.env.SUPABASE_URL;
const ANON=()=>process.env.SUPABASE_ANON_KEY;
const SERVICE=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function cors(req,res){const origin=req.headers.origin||'*',allow=(process.env.CORS_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);let chosen=allow.length?(allow.includes(origin)?origin:'null'):origin;res.setHeader('Access-Control-Allow-Origin',chosen||'*');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization, Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS'){res.statusCode=204;res.end();return true}return false}
function envReady(){return !!(SUPABASE_URL()&&ANON()&&SERVICE())}
async function verifyUser(req){if(!envReady())throw Object.assign(new Error('Cloud backend is not configured.'),{status:503});const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer '))throw Object.assign(new Error('Sign in required.'),{status:401});const r=await fetch(`${SUPABASE_URL()}/auth/v1/user`,{headers:{apikey:ANON(),Authorization:auth}});if(!r.ok)throw Object.assign(new Error('Session expired. Sign in again.'),{status:401});return await r.json()}
async function serviceFetch(path,{method='GET',body,prefer='return=representation'}={}){const r=await fetch(`${SUPABASE_URL()}/rest/v1/${path}`,{method,headers:{apikey:SERVICE(),Authorization:`Bearer ${SERVICE()}`,'Content-Type':'application/json',Prefer:prefer},body:body==null?undefined:JSON.stringify(body)});let data=null;const text=await r.text();if(text){try{data=JSON.parse(text)}catch{data=text}}if(!r.ok){const e=new Error(data?.message||data?.error||`Database request failed (${r.status})`);e.status=500;throw e}return data}
async function getState(userId){let a=await serviceFetch(`user_state?user_id=eq.${encodeURIComponent(userId)}&select=state,schema_version,updated_at`);return a?.[0]||null}
async function saveState(userId,state){let rows=await serviceFetch('user_state?on_conflict=user_id',{method:'POST',body:{user_id:userId,state,schema_version:18,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=representation'});return rows?.[0]||null}
async function saveOnboarding(userId,answers){await serviceFetch('onboarding_answers?on_conflict=user_id',{method:'POST',body:{user_id:userId,answers,updated_at:new Date().toISOString()},prefer:'resolution=merge-duplicates,return=minimal'})}
async function savePlan(userId,plan){await serviceFetch('user_plans',{method:'POST',body:{user_id:userId,kind:'combined',plan,source:'deterministic+ai',active:true},prefer:'return=minimal'})}
async function countAI(userId){const limit=Math.max(1,Math.min(1000,+(process.env.AI_DAILY_LIMIT||40)||40));const used=await serviceFetch('rpc/count_ai_request',{method:'POST',body:{target_user_id:userId,daily_limit:limit},prefer:'return=representation'});if(used==null)throw Object.assign(new Error('Daily AI coach limit reached. Try again tomorrow.'),{status:429});return{used:+used,limit}}
function extractOutputText(j){if(typeof j?.output_text==='string')return j.output_text;for(const item of j?.output||[])for(const c of item?.content||[])if(c.type==='output_text'&&c.text)return c.text;return''}
async function openAI({instructions,text,imageDataUrl,model}){if(!process.env.OPENAI_API_KEY)throw Object.assign(new Error('AI coach is not configured yet.'),{status:503});const content=[{type:'input_text',text:String(text||'')}];if(imageDataUrl)content.push({type:'input_image',image_url:imageDataUrl,detail:'high'});const body={model:model||process.env.OPENAI_MODEL||'gpt-5.6-terra',instructions,input:[{role:'user',content}],max_output_tokens:1800};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw Object.assign(new Error(j?.error?.message||'AI request failed.'),{status:r.status>=400&&r.status<500?r.status:502});return{raw:j,text:extractOutputText(j)}}
function cleanJsonText(text){let t=String(text||'').trim();t=t.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)t=t.slice(a,b+1);return t}
function parseAIJson(text,fallback=null){try{return JSON.parse(cleanJsonText(text))}catch{return fallback}}
function errorResponse(res,e){json(res,e.status||500,{ok:false,error:e.message||'Unexpected server error'})}
module.exports={json,cors,envReady,verifyUser,serviceFetch,getState,saveState,saveOnboarding,savePlan,countAI,openAI,parseAIJson,errorResponse,SUPABASE_URL,ANON,SERVICE};
