// App state -----------------------------------------------------------------
let calView=new Date(),selectedDate=dkey(),trainingDate=null,foodState={editId:null,base:null,meal:'Breakfast'},bDraft=null,bConfidence={},bPhotoFile=null,bRotation=0,barcodeScanner=null,lastFocus=null;

function renderAll(){renderHeader();renderTodayDashboard?.();renderHealthSummary?.();renderCalendar();renderDiary();renderProgress();renderMore();if(document.querySelector('#page-training.active'))renderTraining()}
function renderHeader(){let p=profile(),jobs=[];if(p?.fixed?.enabled)jobs.push(p.fixed.name||'Fixed job');if(p?.variable?.enabled)jobs.push(p.variable.name||'Variable job');$('profileLine').textContent=p?`${p.name||'Profile'}${jobs.length?' · '+jobs.join(' + '):''}`:'Set up your profile';$('variableJobMenu').textContent=(p?.variable?.name||'Variable schedule')+' schedule'}

// Calendar ------------------------------------------------------------------
function renderCalendar(){let y=calView.getFullYear(),m=calView.getMonth(),ym=`${y}-${String(m+1).padStart(2,'0')}`;$('calendarHeading').textContent=new Date(y,m,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});let days=new Date(y,m+1,0).getDate(),first=(new Date(y,m,1).getDay()+6)%7,h='';for(let i=0;i<first;i++)h+='<button class="calDay empty" aria-hidden="true"></button>';
 for(let n=1;n<=days;n++){let k=`${ym}-${String(n).padStart(2,'0')}`,s=workState(k),comp=completedOn(k),gym=!!comp||isScheduled(k),ow=fixedOffWeekend(k),t=target(k),classes=['calDay'];if(s.kind==='both')classes.push('both');if(ow)classes.push('offwk');if(s.kind==='unknown')classes.push('unknown');if(k===selectedDate)classes.push('selected');if(k===dkey())classes.push('today');let dots=`<span class="dayDots"><i class="dot ${s.kind==='both'?'red':'gray'}"></i>${gym?'<i class="dot green"></i>':''}${ow?'<i class="dot yellow"></i>':''}</span>`;let tr=gym?(comp?WORKOUTS[comp.workoutIndex].name:WORKOUTS[projectedWorkoutIndex(k)].name):'No planned lifting',aria=`${fmt(k)}. Work: ${workText(k)}. Training: ${tr}. ${t.cal} calories.${s.kind==='unknown'?' Variable work schedule unknown.':''}`;h+=`<button class="${classes.join(' ')}" data-date="${k}" role="gridcell" aria-label="${esc(aria)}"><span class="dayNum">${n}</span>${dots}<span class="dayKcal">${t.cal}</span>${s.kind==='unknown'?'<span class="unknownMark">?</span>':''}</button>`}
 $('calendarGrid').innerHTML=h;$$('.calDay[data-date]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.date;renderCalendar()});renderDayCard()}
function renderDayCard(){let k=selectedDate,s=workState(k),comp=completedOn(k),scheduled=isScheduled(k),wi=comp?comp.workoutIndex:(scheduled?projectedWorkoutIndex(k):null),t=target(k),unknown=s.kind==='unknown';let tr=wi!=null?WORKOUTS[wi].name:'Recovery / no planned lifting';let badges=`<div class="dayPills"><span class="pill ${unknown?'warn':''}">${esc(workText(k))}</span><span class="pill ${wi!=null?'good':''}">${esc(tr)}</span><span class="pill">${t.cal} kcal · ${t.p}g protein</span></div>`;let action=wi!=null?`<button class="primary wideBtn openWorkout" data-openwork="${k}">Open workout</button>`:(!unknown?`<button class="secondary wideBtn openWorkout" data-traintoday="${k}">Train on this day</button>`:'');$('dayCard').innerHTML=`<h2>${fmt(k)}</h2>${badges}${unknown?`<p><b>${esc(profile()?.variable?.name||'Variable job')} is UNKNOWN.</b> This date is excluded from automatic gym scheduling until the work code is reviewed.</p>`:''}${comp?'<p>This completed workout is frozen in history. Future schedule changes will not rewrite it.</p>':''}${action}`;let ow=$('[data-openwork]');if(ow)ow.onclick=()=>openTrainingDate(k);let td=$('[data-traintoday]');if(td)td.onclick=()=>{let o=overrides();o[k]={action:'train',createdAt:new Date().toISOString()};saveOverrides(o);renderCalendar();openTrainingDate(k)}}
