// Optional private cloud sync (WebDAV-compatible HTTPS endpoint) ------------
function cloudSettings(){return{url:'',username:'',auto:false,...jget(K.sync,{})}}
function saveCloudSettings(x){jset(K.sync,x)}
function cloudSecret(){return sessionStorage.getItem('wgp-cloud-secret')||''}
function cloudPassword(){return sessionStorage.getItem('wgp-cloud-password')||''}
function cloudHeaders(user,pass){let h={'Content-Type':'application/json'};if(user||pass)h.Authorization='Basic '+btoa(unescape(encodeURIComponent(`${user}:${pass}`)));return h}
function normalizeCloudURL(u){u=String(u||'').trim();if(!/^https:\/\//i.test(u))throw Error('Use a full HTTPS WebDAV file URL.');return u}
async function cloudPush(silent=false){if(!await window.WGC18?.ensureHealthConsent?.({interactive:!silent,purpose:'encrypted_webdav_sync'})){if(silent)return false;throw Error('Encrypted WebDAV sync remains off. Your planner is still available on this device.')}let s=cloudSettings(),url=normalizeCloudURL($('#cloudUrl')?.value||s.url),user=$('#cloudUser')?.value||s.username,pass=$('#cloudPassword')?.value||cloudPassword(),secret=$('#cloudPassphrase')?.value||cloudSecret();if(!secret||secret.length<6)throw Error('Enter an encryption passphrase (6+ characters).');sessionStorage.setItem('wgp-cloud-secret',secret);sessionStorage.setItem('wgp-cloud-password',pass);let blob=await encryptedBackupBlob(secret),r=await fetch(url,{method:'PUT',headers:cloudHeaders(user,pass),body:blob});if(!r.ok)throw Error(`Cloud upload failed (${r.status}). Check the WebDAV URL, credentials, and CORS settings.`);saveCloudSettings({url,username:user,auto:!!$('#cloudAuto')?.checked,lastPush:new Date().toISOString()});if(!silent)$('#cloudStatus').textContent='Encrypted cloud backup uploaded successfully.';return true}
async function cloudPull(){if(!await window.WGC18?.ensureHealthConsent?.({interactive:true,purpose:'encrypted_webdav_sync'}))throw Error('Encrypted WebDAV restore remains off. Your local planner was not changed.');let s=cloudSettings(),url=normalizeCloudURL($('#cloudUrl')?.value||s.url),user=$('#cloudUser')?.value||s.username,pass=$('#cloudPassword')?.value||cloudPassword(),secret=$('#cloudPassphrase')?.value||cloudSecret();if(!secret)throw Error('Enter the encryption passphrase used by the remote backup.');sessionStorage.setItem('wgp-cloud-secret',secret);sessionStorage.setItem('wgp-cloud-password',pass);let r=await fetch(url,{headers:cloudHeaders(user,pass),cache:'no-store'});if(!r.ok)throw Error(`Cloud download failed (${r.status}).`);let file=new File([await r.blob()],'cloud-backup.wgp.json',{type:'application/json'}),pack=await decodeImportedPack(file,secret);if(!pack?.data)throw Error('Remote file is not a valid Work + Workout backup.');createRecoverySnapshot('before-cloud-pull');for(const [k,v] of Object.entries(pack.data))if(k.startsWith(PREFIX))localStorage.setItem(k,String(v));saveCloudSettings({...s,url,username:user,lastPull:new Date().toISOString(),auto:!!$('#cloudAuto')?.checked});$('#cloudStatus').textContent=`Cloud backup from ${new Date(pack.exportedAt||Date.now()).toLocaleString()} restored. Reloading…`;setTimeout(()=>location.reload(),800)}
function renderCloudSettings(){let s=cloudSettings();$('#cloudUrl').value=s.url||'';$('#cloudUser').value=s.username||'';$('#cloudAuto').checked=!!s.auto;$('#cloudStatus').textContent=s.lastPush?`Last upload: ${new Date(s.lastPush).toLocaleString()}`:'Your data is encrypted before it leaves the browser. Credentials are kept only for this browser session unless your password manager fills them.'}
async function handleCloudPush(){try{await cloudPush()}catch(e){$('#cloudStatus').textContent=e.message}}
async function handleCloudPull(){try{await cloudPull()}catch(e){$('#cloudStatus').textContent=e.message}}
function setupCloudAutoSync(){document.addEventListener('visibilitychange',()=>{let s=cloudSettings();if(document.visibilityState==='hidden'&&s.auto&&cloudSecret()&&s.url)cloudPush(true).catch(e=>recordDiagnostic('cloud-sync',e))})}
