// Adaptive coaching ----------------------------------------------------------
const MUSCLE_MAP={
 'Hack Squat':['quads','glutes'],'Romanian Deadlift':['hamstrings','glutes'],'Leg Press':['quads','glutes'],'Seated Leg Curl':['hamstrings'],'Leg Extension':['quads'],'Standing Calf Raise':['calves'],'Cable Crunch':['abs'],
 'Incline Dumbbell Press':['chest','triceps'],'Chest-Supported Row':['back','biceps'],'Lat Pulldown':['back','biceps'],'Machine Chest Press':['chest','triceps'],'Cable Lateral Raise':['delts'],'Rope Triceps Pressdown':['triceps'],'Preacher Curl':['biceps'],
 'Smith Machine Squat':['quads','glutes'],'Hip Thrust':['glutes'],'Bulgarian Split Squat':['quads','glutes'],'Lying Leg Curl':['hamstrings'],'Seated Calf Raise':['calves'],'Hanging Knee Raise':['abs'],
 'Flat Bench / Machine Press':['chest','triceps'],'Neutral-Grip Lat Pulldown':['back','biceps'],'Seated DB Shoulder Press':['delts','triceps'],'Seated Cable Row':['back','biceps'],'Incline Cable Fly':['chest'],'Lateral Raise':['delts'],'Incline DB Curl':['biceps'],'Overhead Cable Triceps Extension':['triceps']
};
function phaseInfo(k=dkey()){let start=nutrition()?.planStart||k,week=clamp(Math.floor(diffDays(k,start)/7)+1,1,12);if(week<=3)return{week,name:'Foundation',rir:'2–3 RIR',setMult:1};if(week===4)return{week,name:'Consolidation',rir:'2–3 RIR',setMult:.85};if(week<=7)return{week,name:'Build',rir:'1–2 RIR',setMult:1};if(week===8)return{week,name:'Recovery check',rir:'2–3 RIR',setMult:.85};if(week<=11)return{week,name:'Intensification',rir:'1–2 RIR',setMult:1};return{week,name:'Deload / assessment',rir:'3–4 RIR',setMult:.6}}
function decliningExercises(before=dkey(),lookbackDays=35){let cutoff=addDays(before,-lookbackDays),names=allExerciseNames?allExerciseNames():WORKOUTS.flatMap(w=>w.ex.map(e=>e.name));let flags=[];for(const name of names){let exps=exposures(name,addDays(before,1)).filter(x=>x.session.date>=cutoff).slice(0,3);if(exps.length<3)continue;let a=e1rm(exps[0].ex),b=e1rm(exps[1].ex),c=e1rm(exps[2].ex),rir=avgRIR(exps[0].ex);if(a>0&&b>0&&c>0&&a<b*.97&&b<c*.98&&(rir==null||rir<=1.5))flags.push(name)}return flags}
function fatigueIndex(k=dkey()){let r=recoveryReadiness(k),decl=decliningExercises(k),score=100-r.score+Math.min(25,decl.length*8),h=workoutHistory().filter(s=>s.completed&&s.date>=addDays(k,-9)&&s.date<=k);if(h.length>=4)score+=8;let ws=workState(k);if(ws.kind==='both')score+=12;if(ws.kind==='unknown')score+=8;return{score:clamp(Math.round(score),0,100),declining:decl,readiness:r}}
function autoDeloadNeeded(k=dkey()){let p=phaseInfo(k),f=fatigueIndex(k);return p.week===12||f.score>=58||f.declining.length>=2}
function prescribedSets(meta,k=dkey()){let phase=phaseInfo(k),profileData=profile()||{},m=phase.setMult,minutes=clamp(+profileData.trainingDuration||60,30,90);if(minutes<=30)m*=.72;else if(minutes<=45)m*=.86;if(profileData.trainingExperience==='beginner')m*=.82;else if(profileData.trainingExperience==='advanced'&&minutes>=60)m*=1.08;if(autoDeloadNeeded(k))m=Math.min(m,.65);return Math.max(1,Math.round(meta.sets*m))}
function prescribedRIR(k=dkey()){if(autoDeloadNeeded(k))return'3–4';let p=phaseInfo(k);return p.name==='Foundation'?'2–3':'1–2'}
function globalTrainingPrescription(k=dkey()){let p=phaseInfo(k),f=fatigueIndex(k),deload=autoDeloadNeeded(k),txt=`Week ${p.week}: ${p.name}. `;if(deload){txt+=`Fatigue management is active${f.declining.length?` (${f.declining.length} exercises are trending down)`:''}. Reduce working sets about 30–40%, keep 3–4 RIR, and avoid grinders.`}else if(f.readiness.score<65){txt+=`Readiness is ${f.readiness.band.toLowerCase()}. Keep the workout but stop sets around 2 RIR and do not force load increases.`}else{txt+=`Readiness is ${f.readiness.band.toLowerCase()}. Use normal progression and ${prescribedRIR(k)} RIR on most working sets.`}return{phase:p,fatigue:f,deload,text:txt}}
function weeklyMuscleSets(end=dkey(),days=7){let start=addDays(end,-days+1),out={};for(const s of workoutHistory().filter(x=>x.completed&&x.date>=start&&x.date<=end)){for(const e of s.exercises||[]){let groups=MUSCLE_MAP[e.name]||['other'],hard=(e.sets||[]).filter(z=>+z.r>0&&(z.rir===''||z.rir==null||+z.rir<=3)).length;for(const g of groups)out[g]=(out[g]||0)+hard}}return out}
function muscleSetCoach(){let x=weeklyMuscleSets(),priority=['chest','back','quads','hamstrings','glutes','delts','biceps','triceps'],rows=priority.map(k=>({k,v:x[k]||0}));let low=rows.filter(z=>z.v>0&&z.v<6),high=rows.filter(z=>z.v>18);if(high.length)return`High weekly set count detected for ${high.map(x=>x.k).join(', ')}. Consider holding volume instead of adding sets.`;if(low.length)return`Current completed-week volume is light for ${low.map(x=>x.k).join(', ')}; first check missed sessions before adding volume.`;return'Weekly hard-set distribution is within a reasonable hypertrophy range for the muscle groups you trained.'}
function muscleSetHTML(){let x=weeklyMuscleSets(),keys=['chest','back','quads','hamstrings','glutes','delts','biceps','triceps','calves','abs'];return`<div class="muscleSetGrid">${keys.map(k=>{let v=x[k]||0,p=Math.min(100,v/18*100);return`<div><label><span>${k}</span><b>${v}</b></label><div class="miniTrack"><i style="width:${p}%"></i></div></div>`}).join('')}</div>`}
