// Backup/import/recovery/diagnostics ----------------------------------------
const LEGACY_EXPORT_PREFIXES=['bellevue-','b-','food-diary-','water-','nutrition-log-','training-draft-v14-'];
const LEGACY_EXPORT_KEYS=['training-history-v14','nutrition-settings','my-foods','recent-foods'];
function plannerDataObject(){let data={};for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(PREFIX)||LEGACY_EXPORT_KEYS.includes(k)||LEGACY_EXPORT_PREFIXES.some(p=>k?.startsWith(p)))data[k]=localStorage.getItem(k)}return data}
function backupPackage(){return{app:'Work + Workout',version:APP_VERSION,exportedAt:new Date().toISOString(),origin:location.origin,data:plannerDataObject()}}
function downloadBlob(blob,name){let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportBackup(){downloadBlob(new Blob([JSON.stringify(backupPackage(),null,2)],{type:'application/json'}),`work-gym-planner-backup-${dkey()}.json`)}
function b64(a){return btoa(String.fromCharCode(...new Uint8Array(a)))}function unb64(s){let x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a.buffer}
async function cryptoKey(pass,salt){let enc=new TextEncoder(),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptedBackupBlob(pass){if(!pass||pass.length<6)throw Error('Use a passphrase with at least 6 characters.');let enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(pass,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(backupPackage()))),pack={format:'wgp-encrypted-v1',salt:b64(salt),iv:b64(iv),cipher:b64(cipher)};return new Blob([JSON.stringify(pack)],{type:'application/json'})}
async function exportEncryptedBackup(){let pass=$('#backupPass')?.value||'';try{let blob=await encryptedBackupBlob(pass);downloadBlob(blob,`work-gym-planner-secure-${dkey()}.wgp.json`);$('#backupStatus').textContent='Encrypted backup created. Keep the passphrase separate from the file.'}catch(e){$('#backupStatus').textContent=e.message}}
async function shareEncryptedBackup(){let pass=$('#backupPass')?.value||'';try{let blob=await encryptedBackupBlob(pass),file=new File([blob],`work-gym-planner-secure-${dkey()}.wgp.json`,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Work + Workout backup',files:[file]});$('#backupStatus').textContent='Backup opened in the iOS share sheet. You can save it to iCloud Drive or another private location.'}else{downloadBlob(blob,file.name);$('#backupStatus').textContent='Encrypted backup downloaded because file sharing is not supported here.'}}catch(e){if(e.name!=='AbortError')$('#backupStatus').textContent=e.message}}
async function decodeImportedPack(file,pass=''){let raw=JSON.parse(await file.text());if(raw?.format==='wgp-encrypted-v1'){if(!pass)throw Error('Enter the backup passphrase first.');let salt=new Uint8Array(unb64(raw.salt)),iv=new Uint8Array(unb64(raw.iv)),key=await cryptoKey(pass,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,unb64(raw.cipher));return JSON.parse(new TextDecoder().decode(plain))}return raw}
async function importBackup(file){if(!file)return;try{let pack=await decodeImportedPack(file,$('#backupPass')?.value||'');if(!pack?.data||typeof pack.data!=='object')throw Error('That file is not a valid planner backup.');createRecoverySnapshot('before-import');let count=0;for(const [k,v] of Object.entries(pack.data)){if(k.startsWith(PREFIX)||LEGACY_EXPORT_KEYS.includes(k)||LEGACY_EXPORT_PREFIXES.some(p=>k.startsWith(p))){localStorage.setItem(k,String(v));count++}}localStorage.removeItem(K.migrated);migrateLegacy();$('#importStatus').textContent=`Imported ${count} data records. Reloading…`;setTimeout(()=>location.reload(),700)}catch(e){$('#importStatus').textContent=e.message||'That file is not a valid Work + Workout backup.'}}
function deleteAllData(){if($('#deleteConfirm').value!=='DELETE')return toast('Type DELETE first');createRecoverySnapshot('before-delete');let keys=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(PREFIX)&&k!==K.recovery)keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));location.reload()}
function createRecoverySnapshot(reason='auto'){try{let day=dkey(),arr=jget(K.recovery,[]);if(reason==='auto'&&arr[0]?.date===day)return;let snapshot={date:day,at:new Date().toISOString(),reason,data:plannerDataObject()};arr.unshift(snapshot);jset(K.recovery,arr.slice(0,3))}catch(e){recordDiagnostic('snapshot',e)}}
function restoreRecoverySnapshot(){let arr=jget(K.recovery,[]),s=arr[0];if(!s)return toast('No recovery snapshot available');if(!confirm(`Restore the ${s.reason} snapshot from ${new Date(s.at).toLocaleString()}?`))return;for(const [k,v] of Object.entries(s.data||{}))localStorage.setItem(k,String(v));location.reload()}
function diagnostics(){return jget(K.diagnostics,[])}
function recordDiagnostic(type,err){try{let a=diagnostics(),msg=String(err?.message||err||'Unknown error'),stack=String(err?.stack||'').slice(0,1000);a.unshift({at:new Date().toISOString(),type,msg,stack,version:APP_VERSION,path:location.pathname});jset(K.diagnostics,a.slice(0,30))}catch{}}
function exportDiagnostics(){let payload={version:APP_VERSION,at:new Date().toISOString(),userAgent:navigator.userAgent,diagnostics:diagnostics(),storageKeys:Object.keys(plannerDataObject())};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`work-gym-diagnostics-${dkey()}.json`)}
window.addEventListener('error',e=>recordDiagnostic('error',e.error||e.message));window.addEventListener('unhandledrejection',e=>recordDiagnostic('promise',e.reason));
