// Backup/import/recovery/diagnostics ----------------------------------------
const LEGACY_EXPORT_PREFIXES=['bellevue-','b-','food-diary-','water-','nutrition-log-','training-draft-v14-'];
const LEGACY_EXPORT_KEYS=['training-history-v14','nutrition-settings','my-foods','recent-foods'];
function backupDataOnly(data){let result={};for(const [key,value] of Object.entries(data||{})){if(key===K.recovery||key===K.diagnostics||key===K.sync||key===PREFIX+'sync-settings'||key===PREFIX+'ai-chat-local-v18')continue;if(window.WGC23Core?window.WGC23Core.isPlannerKey(key,PREFIX):(key.startsWith(PREFIX)||LEGACY_EXPORT_KEYS.includes(key)||LEGACY_EXPORT_PREFIXES.some(p=>key.startsWith(p))))result[key]=String(value)}return result}
function plannerDataObject(){let data={};for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k)data[k]=localStorage.getItem(k)}return backupDataOnly(data)}
function backupPackage(){return{app:'Work + Workout',version:APP_VERSION,exportedAt:new Date().toISOString(),origin:location.origin,data:plannerDataObject()}}
function downloadBlob(blob,name){let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportBackup(){downloadBlob(new Blob([JSON.stringify(backupPackage(),null,2)],{type:'application/json'}),`work-gym-planner-backup-${dkey()}.json`)}
function b64(a){let bytes=new Uint8Array(a),binary='';for(let offset=0;offset<bytes.length;offset+=32768)binary+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(binary)}function unb64(s){let x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a.buffer}
async function cryptoKey(pass,salt){let enc=new TextEncoder(),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptedBackupBlob(pass){if(!pass||pass.length<12)throw Error('Use a memorable passphrase with at least 12 characters.');let enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await cryptoKey(pass,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(backupPackage()))),pack={format:'wgp-encrypted-v1',salt:b64(salt),iv:b64(iv),cipher:b64(cipher)};return new Blob([JSON.stringify(pack)],{type:'application/json'})}
async function exportEncryptedBackup(){let pass=$('#backupPass')?.value||'';try{let blob=await encryptedBackupBlob(pass);downloadBlob(blob,`work-gym-planner-secure-${dkey()}.wgp.json`);$('#backupStatus').textContent='Encrypted backup created. Keep the passphrase separate from the file.'}catch(e){$('#backupStatus').textContent=e.message}}
async function shareEncryptedBackup(){let pass=$('#backupPass')?.value||'';try{let blob=await encryptedBackupBlob(pass),file=new File([blob],`work-gym-planner-secure-${dkey()}.wgp.json`,{type:'application/json'});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:'Work + Workout backup',files:[file]});$('#backupStatus').textContent='Choose a private location for your backup. Keep the passphrase separate from the file.'}else{downloadBlob(blob,file.name);$('#backupStatus').textContent='Encrypted backup downloaded because file sharing is not supported here.'}}catch(e){if(e.name!=='AbortError')$('#backupStatus').textContent=e.message}}
async function decodeImportedPack(file,pass=''){if(file.size>20*1024*1024)throw Error('This backup is too large. Choose a file under 20 MB.');let raw=JSON.parse(await file.text());if(raw?.format==='wgp-encrypted-v1'){if(!pass)throw Error('Enter the backup passphrase first.');try{let salt=new Uint8Array(unb64(raw.salt)),iv=new Uint8Array(unb64(raw.iv));if(salt.length!==16||iv.length!==12)throw Error();let key=await cryptoKey(pass,salt),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,unb64(raw.cipher));return JSON.parse(new TextDecoder().decode(plain))}catch{throw Error('The passphrase did not unlock this backup, or the file is damaged. Your data has not changed.')}}return raw}
// Synchronous writes either complete or restore the previous values. In
// particular, a full device must never leave a half-imported planner behind.
function applyPlannerData(data,{replace=false}={}){
 return window.WGC23Core.applyPlannerStorage(localStorage,data,{prefix:PREFIX,replace});
}
async function importBackup(file){if(!file)return;try{let pack=await decodeImportedPack(file,$('#backupPass')?.value||'');if(!pack?.data||typeof pack.data!=='object'||Array.isArray(pack.data))throw Error('That file is not a valid planner backup.');createRecoverySnapshot('before-import');let count=applyPlannerData(pack.data);localStorage.removeItem(K.migrated);migrateLegacy();$('#importStatus').textContent=`Imported ${count} data records. Reloading…`;setTimeout(()=>location.reload(),700)}catch(e){$('#importStatus').textContent=e.name==='QuotaExceededError'?'There is not enough space to restore this backup. Your previous data was kept.':e.message||'That file is not a valid Work + Workout backup.'}}
function deleteAllData(){if($('#deleteConfirm').value!=='DELETE')return toast('Type DELETE first');createRecoverySnapshot('before-delete');let keys=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(PREFIX)&&k!==K.recovery)keys.push(k)}keys.forEach(k=>localStorage.removeItem(k));location.reload()}
function compactRecoverySnapshots(){try{const raw=localStorage.getItem(K.recovery);if(!raw)return[];const stored=JSON.parse(raw);if(!Array.isArray(stored))return[];const clean=stored.slice(0,3).map(snapshot=>({...snapshot,data:backupDataOnly(snapshot?.data)})),text=JSON.stringify(clean);if(text!==raw)localStorage.setItem(K.recovery,text);return clean}catch{return[]}}
function createRecoverySnapshot(reason='auto'){try{let day=dkey(),arr=compactRecoverySnapshots();if(reason==='auto'&&arr[0]?.date===day)return;let snapshot={date:day,at:new Date().toISOString(),reason,data:plannerDataObject()};arr.unshift(snapshot);localStorage.setItem(K.recovery,JSON.stringify(arr.slice(0,3)));return true}catch(e){recordDiagnostic('snapshot',e);return false}}
function restoreRecoverySnapshot(){let arr=jget(K.recovery,[]),s=arr[0];if(!s)return toast('No recovery snapshot available');if(!confirm(`Restore the ${s.reason} snapshot from ${new Date(s.at).toLocaleString()}?`))return;try{applyPlannerData(s.data||{});location.reload()}catch{toast('Not enough device space to restore. Your previous data was kept.')}}
// Shrink legacy nested snapshots before account startup tries to save a copy.
compactRecoverySnapshots();
function diagnostics(){return jget(K.diagnostics,[])}
function recordDiagnostic(type,err){try{let a=diagnostics(),msg=String(err?.message||err||'Unknown error'),stack=String(err?.stack||'').slice(0,1000);a.unshift({at:new Date().toISOString(),type,msg,stack,version:APP_VERSION,path:location.pathname});jset(K.diagnostics,a.slice(0,30))}catch{}}
function exportDiagnostics(){let payload={version:APP_VERSION,at:new Date().toISOString(),userAgent:navigator.userAgent,diagnostics:diagnostics(),storageKeys:Object.keys(plannerDataObject())};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`work-gym-diagnostics-${dkey()}.json`)}
window.addEventListener('error',e=>recordDiagnostic('error',e.error||e.message));window.addEventListener('unhandledrejection',e=>recordDiagnostic('promise',e.reason));
