// Diary UI ------------------------------------------------------------------
const MEALS=['Breakfast','Lunch','Dinner','Snacks'];
function renderDiary(){let k=$('diaryDate')?.value||dkey(),t=target(k),a=totals(k),left=Math.round(t.cal-a.cal);if(!$('calRemaining'))return;const set=(id,v)=>{const el=$(id);if(el)el.textContent=v};set('calRemaining',left);set('calGoal',t.cal.toLocaleString());set('calFood',Math.round(a.cal).toLocaleString());set('calLeftSmall',left);let ms=[['Protein',a.p,t.p,'g','mProtein'],['Carbs',a.c,t.c,'g','mCarbs'],['Fat',a.f,t.f,'g','mFat'],['Fiber',a.fiber,t.fiber,'g','mMinor'],['Sodium',a.sodium,t.sodium,'mg','mMinor'],['Sat fat',a.satFat,t.satFat,'g','mMinor']];$('macroGrid').innerHTML=ms.map(([n,v,g,u,cls])=>`<div class="macroLine ${cls}"><label><span>${n}</span><span>${Math.round(v)} / ${Math.round(g)} ${u}</span></label><div class="track"><i style="width:${Math.min(100,g?v/g*100:0)}%"></i></div></div>`).join('');let dist=MEALS.map(m=>({m,p:mealTotals(k,m).p}));$('proteinDistribution').textContent=`Protein distribution: ${dist.map(x=>`${x.m} ${Math.round(x.p)}g`).join(' · ')}. Aim to spread protein across 3–4 meals when practical.`;
 let entries=diary(k),html='';for(const meal of MEALS){let ar=entries.filter(x=>x.meal===meal),sum=ar.reduce((z,x)=>z+foodTotals(x).cal,0),protein=ar.reduce((z,x)=>z+foodTotals(x).p,0),count=`${ar.length} ${ar.length===1?'item':'items'}`;html+=`<section class="meal"><div class="mealHead"><h3>${meal}<small>${count} · ${Math.round(sum)} kcal · ${Math.round(protein)}g protein</small></h3><div class="mealActions"><button data-save-recipe="${meal}">Save meal</button><button data-add-food="${meal}">+ Add foods</button></div></div>${ar.length?ar.map(x=>{let q=foodTotals(x);return`<button class="foodRow" data-food-id="${esc(x.id)}" aria-label="Edit ${esc(x.name)}"><div><div class="foodName">${esc(x.name)}</div><div class="foodSub">${Math.round(x.grams)} g · P ${q.p.toFixed(1)} · C ${q.c.toFixed(1)} · F ${q.f.toFixed(1)}${x.source?` · ${esc(x.source)}`:''}</div></div><div class="foodCal">${Math.round(q.cal)}<small>kcal</small></div></button>`}).join(''):'<div class="emptyMeal">No foods yet. Add everything you ate to this meal.</div>'}</section>`}$('mealList').innerHTML=html;$$('[data-add-food]').forEach(b=>b.onclick=()=>openFood(b.dataset.addFood));$$('[data-food-id]').forEach(b=>b.onclick=()=>editFoodEntry(b.dataset.foodId));$$('[data-save-recipe]').forEach(b=>b.onclick=()=>saveMealRecipe(k,b.dataset.saveRecipe));let water=+(localStorage.getItem(K.water+k)||0);$('waterText').textContent=`${water} / ${t.water} oz`}
function saveMealRecipe(k,meal){let items=diary(k).filter(x=>x.meal===meal);if(!items.length)return toast('No foods in this meal');let name=prompt('Recipe name:',meal+' meal');if(!name)return;let r=jget(K.recipes,[]);r.unshift({id:uid('recipe'),name,items:structuredClone(items),createdAt:new Date().toISOString()});jset(K.recipes,r.slice(0,100));toast('Recipe saved')}

// Food modal/search/scanner -------------------------------------------------
function openFood(meal='Breakfast'){foodState={editId:null,base:null,meal,batch:[]};clearFoodForm();$('foodMeal').value=meal;$('foodTitle').textContent='Add foods';$('#foodDialog [data-close="foodDialog"]').textContent='Cancel';openModal('foodDialog');foodTab('search');renderRecentFoods();renderSavedFoods();renderRecipes();renderFoodBatch()}
function clearFoodForm(){['foodName','foodGrams','foodCal','foodProtein','foodCarbs','foodFat','foodFiber','foodSatFat','foodSodium'].forEach(id=>{if($(id))$(id).value=''});$('foodGrams').value=100;$('saveToMyFoods').checked=false;$('deleteFoodEntry').classList.add('hidden');$('foodSourceCard').innerHTML='';foodState.base=null;renderFoodBatch()}
function foodTab(t){$$('#foodTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.tabPane').forEach(p=>p.classList.toggle('active',p.id==='foodPane-'+t));if(t!=='scan')stopBarcode()}
function myFoods(){return jget(K.foods,[])}function recentFoods(){return jget(K.recent,[])}
function recipes(){return jget(K.recipes,[])}
function setFoodBase(p){foodState.base=p;$('foodName').value=p.name||'';$('foodGrams').value=p.defaultGrams||100;updateFoodTotalsFromBase();$('foodSourceCard').innerHTML=`<div class="sourceCard"><b>${esc(p.name)}</b>${p.brand?` · ${esc(p.brand)}`:''}<br>Source: ${esc(p.source||'Manual')} · values normalized per 100 g${p.defaultGrams?` · default ${Math.round(p.defaultGrams)} g`:''}</div>`;rememberRecentFood(p);renderFoodBatch()}
function rememberRecentFood(p){let r=recentFoods().filter(x=>x.code!==p.code||x.name!==p.name);r.unshift(p);jset(K.recent,r.slice(0,20))}
function updateFoodTotalsFromBase(){if(!foodState.base)return;let g=+$('#foodGrams').value||100,q=g/100,p=foodState.base.per100;$('#foodCal').value=(p.cal*q).toFixed(1);$('#foodProtein').value=(p.p*q).toFixed(1);$('#foodCarbs').value=(p.c*q).toFixed(1);$('#foodFat').value=(p.f*q).toFixed(1);$('#foodFiber').value=(p.fiber*q).toFixed(1);$('#foodSatFat').value=(p.satFat*q).toFixed(1);$('#foodSodium').value=(p.sodium*q).toFixed(0)}
function per100FromForm(){let g=Math.max(.1,+$('#foodGrams').value||100),q=100/g;return{cal:(+$('#foodCal').value||0)*q,p:(+$('#foodProtein').value||0)*q,c:(+$('#foodCarbs').value||0)*q,f:(+$('#foodFat').value||0)*q,fiber:(+$('#foodFiber').value||0)*q,satFat:(+$('#foodSatFat').value||0)*q,sodium:(+$('#foodSodium').value||0)*q}}
function foodDraftFromForm(){let name=$('#foodName').value.trim();if(!name)return null;return{id:foodState.editId||uid('food'),name,meal:$('#foodMeal').value,grams:Math.max(.1,+$('#foodGrams').value||100),per100:per100FromForm(),source:foodState.base?.source||'Manual',code:foodState.base?.code||'',saveToFoods:$('#saveToMyFoods').checked}}
function foodDraftFromProduct(p){let grams=Math.max(.1,+p.defaultGrams||100);return{id:uid('food'),name:p.name||'Food',meal:foodState.meal||'Breakfast',grams,per100:{...(p.per100||{})},source:p.source||'Saved',code:p.code||'',saveToFoods:false}}
function savePersonalFood(x){if(!x.saveToFoods)return;let f=myFoods().filter(z=>z.name.toLowerCase()!==x.name.toLowerCase());f.unshift({name:x.name,brand:'',code:x.code,source:x.source,defaultGrams:x.grams,per100:x.per100});jset(K.foods,f.slice(0,300))}
function diaryFood(x){let {saveToFoods,...entry}=x;return entry}
function sameFoodDraft(a,b){if(!a||!b)return false;return(a.code&&b.code?a.code===b.code:a.name.trim().toLowerCase()===b.name.trim().toLowerCase())&&+a.grams===+b.grams}
function pendingFoodDrafts(){let batch=[...(foodState.batch||[])],form=foodDraftFromForm();if(form&&!batch.some(x=>sameFoodDraft(x,form)))batch.push(form);return batch}
function queueFoodProduct(p){if(foodState.editId||!p)return;let x=foodDraftFromProduct(p);foodState.batch=[...(foodState.batch||[]),x];rememberRecentFood(p);renderFoodBatch()}
function queueFoodEntry(){if(foodState.editId)return saveFoodEntry();let x=foodDraftFromForm();if(!x)return toast('Choose or enter a food first');foodState.batch=[...(foodState.batch||[]),x];clearFoodForm();foodTab('search');$('#foodSearchInput')?.focus();renderFoodBatch()}
function removeQueuedFood(id){foodState.batch=(foodState.batch||[]).filter(x=>x.id!==id);renderFoodBatch()}
function changeFoodMeal(meal){foodState.meal=meal||'Breakfast';foodState.batch=(foodState.batch||[]).map(x=>({...x,meal:foodState.meal}));renderFoodBatch()}
function renderFoodBatch(){let tray=$('foodBatchTray'),commit=$('saveFoodEntry'),queue=$('queueFoodEntry'),context=$('foodMealContext');if(!tray||!commit||!queue)return;let editing=!!foodState.editId,meal=$('foodMeal')?.value||foodState.meal||'Breakfast',batch=foodState.batch||[],pending=editing?[]:pendingFoodDrafts(),sum=pending.reduce((z,x)=>z+foodTotals(x).cal,0);foodState.meal=meal;if(context)context.textContent=editing?'Update this diary item':`Building ${meal} · ${pending.length} selected`;tray.hidden=editing||!batch.length;tray.innerHTML=batch.length?`<div class="foodBatchHead"><span><b>${batch.length} ${batch.length===1?'food':'foods'} ready</b><small>${Math.round(batch.reduce((z,x)=>z+foodTotals(x).cal,0))} kcal in ${meal}</small></span><button type="button" data-clear-food-batch>Clear</button></div><div class="foodBatchItems">${batch.map(x=>{let q=foodTotals(x);return`<div><span><b>${esc(x.name)}</b><small>${Math.round(x.grams)} g · ${Math.round(q.cal)} kcal · ${Math.round(q.p)}g protein</small></span><button type="button" data-remove-food-batch="${esc(x.id)}" aria-label="Remove ${esc(x.name)}">×</button></div>`}).join('')}</div>`:'';$$('[data-remove-food-batch]').forEach(b=>b.onclick=()=>removeQueuedFood(b.dataset.removeFoodBatch));let clear=$('[data-clear-food-batch]');if(clear)clear.onclick=()=>{foodState.batch=[];renderFoodBatch()};queue.classList.toggle('hidden',editing);queue.textContent='Add & keep adding';commit.textContent=editing?'Save changes':pending.length?`Add ${pending.length} ${pending.length===1?'food':'foods'} to ${meal}`:`Add to ${meal}`;commit.dataset.pendingCount=String(pending.length);commit.dataset.pendingCalories=String(Math.round(sum))}
function discardFoodDraft(){foodState={editId:null,base:null,meal:'Breakfast',batch:[]};clearFoodForm()}
function saveFoodEntry(){let k=$('diaryDate').value,a=diary(k),x=foodDraftFromForm();if(foodState.editId){if(!x)return toast('Food name is required');savePersonalFood(x);saveDiary(k,a.map(z=>z.id===foodState.editId?diaryFood(x):z));closeModal('foodDialog');return}let pending=pendingFoodDrafts();if(!pending.length)return toast('Choose or enter at least one food');pending.forEach(savePersonalFood);saveDiary(k,[...a,...pending.map(diaryFood)]);let meal=foodState.meal||pending[0].meal,count=pending.length;closeModal('foodDialog');toast(`${count} ${count===1?'food':'foods'} added to ${meal}`)}
function editFoodEntry(id){let x=diary($('diaryDate').value).find(z=>z.id===id);if(!x)return;foodState={editId:id,base:{name:x.name,source:x.source||'Saved entry',code:x.code||'',defaultGrams:x.grams,per100:x.per100},meal:x.meal,batch:[]};openModal('foodDialog');foodTab('manual');$('foodTitle').textContent='Edit food';$('#foodDialog [data-close="foodDialog"]').textContent='Cancel';$('#foodName').value=x.name;$('#foodMeal').value=x.meal;$('#foodGrams').value=x.grams;let t=foodTotals(x);$('#foodCal').value=t.cal.toFixed(1);$('#foodProtein').value=t.p.toFixed(1);$('#foodCarbs').value=t.c.toFixed(1);$('#foodFat').value=t.f.toFixed(1);$('#foodFiber').value=t.fiber.toFixed(1);$('#foodSatFat').value=t.satFat.toFixed(1);$('#foodSodium').value=t.sodium.toFixed(0);$('#deleteFoodEntry').classList.remove('hidden');$('#foodSourceCard').innerHTML=`<div class="sourceCard">Editing saved entry · ${Math.round(x.grams)} g. Values remain normalized internally, so changing grams does not double-scale.</div>`;renderFoodBatch()}
function deleteFoodEntry(){if(!foodState.editId)return;let k=$('diaryDate').value;saveDiary(k,diary(k).filter(x=>x.id!==foodState.editId));closeModal('foodDialog')}

const BUILTIN_FOODS=[
 {name:'Chicken breast, cooked',source:'Built-in generic food',defaultGrams:170,per100:{cal:165,p:31,c:0,f:3.6,fiber:0,satFat:1,sodium:74}},
 {name:'White rice, cooked',source:'Built-in generic food',defaultGrams:158,per100:{cal:130,p:2.7,c:28.2,f:.3,fiber:.4,satFat:.08,sodium:1}},
 {name:'Brown rice, cooked',source:'Built-in generic food',defaultGrams:195,per100:{cal:123,p:2.7,c:25.6,f:1,fiber:1.6,satFat:.26,sodium:4}},
 {name:'Whole egg',source:'Built-in generic food',defaultGrams:50,per100:{cal:143,p:12.6,c:.7,f:9.5,fiber:0,satFat:3.1,sodium:142}},
 {name:'Egg whites',source:'Built-in generic food',defaultGrams:100,per100:{cal:52,p:10.9,c:.7,f:.2,fiber:0,satFat:0,sodium:166}},
 {name:'Greek yogurt, nonfat plain',source:'Built-in generic food',defaultGrams:170,per100:{cal:59,p:10.3,c:3.6,f:.4,fiber:0,satFat:.1,sodium:36}},
 {name:'Oats, dry',source:'Built-in generic food',defaultGrams:40,per100:{cal:379,p:13.2,c:67.7,f:6.5,fiber:10.1,satFat:1.2,sodium:6}},
 {name:'Banana',source:'Built-in generic food',defaultGrams:118,per100:{cal:89,p:1.1,c:22.8,f:.3,fiber:2.6,satFat:.1,sodium:1}},
 {name:'Apple',source:'Built-in generic food',defaultGrams:182,per100:{cal:52,p:.3,c:13.8,f:.2,fiber:2.4,satFat:.03,sodium:1}},
 {name:'Salmon, cooked',source:'Built-in generic food',defaultGrams:170,per100:{cal:206,p:22.1,c:0,f:12.4,fiber:0,satFat:3.1,sodium:59}},
 {name:'Ground turkey 93% lean, cooked',source:'Built-in generic food',defaultGrams:113,per100:{cal:203,p:27.4,c:0,f:10.4,fiber:0,satFat:2.8,sodium:92}},
 {name:'Sweet potato, baked',source:'Built-in generic food',defaultGrams:180,per100:{cal:90,p:2,c:20.7,f:.15,fiber:3.3,satFat:.03,sodium:36}},
 {name:'Broccoli, cooked',source:'Built-in generic food',defaultGrams:156,per100:{cal:35,p:2.4,c:7.2,f:.4,fiber:3.3,satFat:.08,sodium:41}},
 {name:'Avocado',source:'Built-in generic food',defaultGrams:100,per100:{cal:160,p:2,c:8.5,f:14.7,fiber:6.7,satFat:2.1,sodium:7}},
 {name:'Whey protein powder',source:'Built-in generic food',defaultGrams:32,per100:{cal:375,p:75,c:12.5,f:6.3,fiber:0,satFat:3.1,sodium:500}}
].map(x=>({...x,brand:'',code:'',img:''}));
function builtinFoodMatches(q){q=q.toLowerCase();let terms=q.split(/\s+/).filter(Boolean);return BUILTIN_FOODS.filter(x=>terms.every(t=>x.name.toLowerCase().includes(t))).slice(0,8)}
