function normalizeOFF(p){let n=p.nutriments||{},num=k=>+n[k+'_100g']||0,grams=+p.serving_quantity||parseFloat(String(p.serving_size||'').match(/[\d.]+/)?.[0])||100;return{name:p.product_name||p.generic_name||'Unnamed food',brand:p.brands||'',code:p.code||'',source:'Open Food Facts',defaultGrams:grams,per100:{cal:num('energy-kcal')||(+n.energy_100g||0)/4.184,p:num('proteins'),c:num('carbohydrates'),f:num('fat'),fiber:num('fiber'),satFat:num('saturated-fat'),sodium:num('sodium')*1000},img:p.image_front_small_url||''}}
function foodResult(p,index=0){let grams=p.defaultGrams||100,q=p.per100.cal*grams/100;return`<div class="foodResultRow"><button type="button" class="foodResultSelect" data-result-index="${index}"><span>${p.img?`<img src="${esc(p.img)}" alt="">`:'<span class="ph">◉</span>'}</span><span><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${Math.round(grams)} g · ${esc(p.source)}</small></span><strong>${Math.round(q)} kcal</strong></button><button type="button" class="foodQuickAdd" data-quick-add-index="${index}" aria-label="Quick add ${esc(p.name)}">+</button></div>`}
let lastSearchProducts=[],foodSearchRequest=0,foodSearchTimer=null,mealScanImageDataUrl='';
function clearFoodSearch({restore=true}={}){foodSearchRequest++;clearTimeout(foodSearchTimer);lastSearchProducts=[];let input=$('foodSearchInput'),results=$('foodSearchResults'),clear=$('clearFoodSearch');if(input)input.value='';if(results){results.innerHTML='';results.hidden=true}if(clear)clear.hidden=true;if(restore&&$('#foodDialog')?.classList.contains('open')&&!foodState.editId)foodTab(foodState.libraryTab||'history')}
function showFoodSearchResults(){stopBarcode();$('foodEntryEditor').hidden=true;$$('#foodDialog [data-food-pane]').forEach(p=>{p.hidden=true;p.classList.remove('active')});$('foodSearchResults').hidden=false;$('clearFoodSearch').hidden=false;renderFoodBatch()}
async function searchFood(){let input=$('foodSearchInput'),q=input.value.trim();if(!q)return clearFoodSearch();let request=++foodSearchRequest;showFoodSearchResults();let built=[...myFoods().filter(x=>x.name?.toLowerCase().includes(q.toLowerCase())).slice(0,5),...builtinFoodMatches(q)],seen=new Set;built=built.filter(x=>{let key=String(x.code||x.name).toLowerCase();if(seen.has(key))return false;seen.add(key);return true});lastSearchProducts=built;$('foodSearchResults').innerHTML=built.length?'<p class="foodSearchStatus">Matches available now · checking packaged foods…</p>'+built.map(foodResult).join(''):'<p class="foodSearchStatus">Searching packaged foods…</p>';bindFoodResults();try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',u=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=20&fields=${fields}`,r=await fetch(u),j=await r.json();if(request!==foodSearchRequest||input.value.trim()!==q)return;let off=(j.products||[]).map(normalizeOFF).filter(x=>x.name&&x.per100.cal>0).filter(x=>{let key=String(x.code||x.name).toLowerCase();if(seen.has(key))return false;seen.add(key);return true});lastSearchProducts=[...built,...off];$('foodSearchResults').innerHTML=lastSearchProducts.length?lastSearchProducts.map(foodResult).join(''):'<p class="muted">No matching foods found. Try a simpler name or Quick add.</p>';bindFoodResults()}catch{if(request!==foodSearchRequest||input.value.trim()!==q)return;lastSearchProducts=built;$('foodSearchResults').innerHTML=built.length?built.map(foodResult).join('')+'<p class="foodSearchStatus">Packaged-food search is offline; these foods are still available.</p>':'<p class="muted">Food search failed. Check your connection or use Quick add.</p>';bindFoodResults()}}
function bindFoodResults(){$$('#foodSearchResults [data-result-index]').forEach(b=>b.onclick=()=>setFoodBase(lastSearchProducts[+b.dataset.resultIndex]));$$('#foodSearchResults [data-quick-add-index]').forEach(b=>b.onclick=()=>queueFoodProduct(lastSearchProducts[+b.dataset.quickAddIndex]))}
async function lookupBarcode(code){code=String(code||'').replace(/\D/g,'');if(!code)return setBarcodeStatus('Enter a UPC/EAN barcode.');setBarcodeStatus('Looking up '+code+' in Open Food Facts…');try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=${fields}`),j=await r.json();if(j.status===1&&j.product){setFoodBase(normalizeOFF({...j.product,code}));setBarcodeStatus('✓ Product found. Review the serving and nutrition values.');stopBarcode()}else setBarcodeStatus('✓ Barcode decoded, but no exact Open Food Facts product was found. Search by product name or use Manual.')}catch{setBarcodeStatus('Barcode lookup failed. Check your internet connection.') }}
function setBarcodeStatus(t){$('#barcodeStatus').textContent=t}
const SCANNER_URL='/work-gym-planner-v16/vendor/html5-qrcode/html5-qrcode.min.js';
async function ensureScanner(){if(window.Html5Qrcode)return true;return new Promise(resolve=>{let s=document.createElement('script');s.src=SCANNER_URL;s.onload=()=>resolve(!!window.Html5Qrcode);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
let nativeBarcodeStream=null,nativeBarcodeTimer=null;
async function nativeBarcodeDetector(){if(!('BarcodeDetector' in window))return null;try{let wanted=['ean_13','ean_8','upc_a','upc_e'];let supported=BarcodeDetector.getSupportedFormats?await BarcodeDetector.getSupportedFormats():wanted,formats=wanted.filter(x=>supported.includes(x));return new BarcodeDetector(formats.length?{formats}:undefined)}catch{return null}}
async function startBarcode(){await stopBarcode();if(!navigator.mediaDevices?.getUserMedia){setBarcodeStatus('Live camera is blocked in this in-app browser. Open the planner in Safari or the Home Screen app, then retry. Photo barcode scanning can still be used here.');return}let native=await nativeBarcodeDetector();if(native){try{let v=document.createElement('video');v.playsInline=true;v.muted=true;v.style.width='100%';v.style.maxHeight='260px';v.style.objectFit='cover';$('#barcodeReader').appendChild(v);nativeBarcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=nativeBarcodeStream;await v.play();setBarcodeStatus('Camera ready. Center the full UPC/EAN barcode and hold steady.');nativeBarcodeTimer=setInterval(async()=>{try{let r=await native.detect(v),code=r?.[0]?.rawValue;if(code){await stopBarcode();lookupBarcode(code)}}catch{}},300);return}catch{await stopBarcode()}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load. Check internet and retry.');return}try{barcodeScanner=new Html5Qrcode('barcodeReader');await barcodeScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:140},formatsToSupport:window.Html5QrcodeSupportedFormats?[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]:undefined},txt=>lookupBarcode(txt),()=>{});setBarcodeStatus('Camera ready. Center the full barcode in the box and hold steady.')}catch(e){setBarcodeStatus('Live scan could not start. Use Safari/Home Screen or scan a barcode photo.') }}
async function stopBarcode(){if(nativeBarcodeTimer){clearInterval(nativeBarcodeTimer);nativeBarcodeTimer=null}if(nativeBarcodeStream){nativeBarcodeStream.getTracks().forEach(t=>t.stop());nativeBarcodeStream=null}if(barcodeScanner){try{if(barcodeScanner.isScanning)await barcodeScanner.stop();await barcodeScanner.clear()}catch{}barcodeScanner=null}if($('#barcodeReader'))$('#barcodeReader').innerHTML=''}
async function scanBarcodePhoto(file){if(!file)return;await stopBarcode();setBarcodeStatus('Reading barcode from photo…');let native=await nativeBarcodeDetector();if(native){try{let bmp=await createImageBitmap(file),r=await native.detect(bmp),code=r?.[0]?.rawValue;bmp.close?.();if(code){$('#barcodePhoto').value='';return lookupBarcode(code)}}catch{}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load.');$('#barcodePhoto').value='';return}try{barcodeScanner=new Html5Qrcode('barcodeReader');let txt=await barcodeScanner.scanFile(file,true);await lookupBarcode(txt)}catch{setBarcodeStatus('No UPC/EAN barcode could be read. Retake the photo closer, sharp, and with the entire barcode visible.')}finally{try{await barcodeScanner?.clear()}catch{}barcodeScanner=null;$('#barcodePhoto').value=''}}
function renderRecentFoods(){renderNutritionLibrary()}
function renderSavedFoods(){let host=$('savedFoodResults');if(!host)return;let q=($('#savedFoodSearch')?.value||'').toLowerCase(),a=myFoods().filter(x=>!q||x.name.toLowerCase().includes(q));host.innerHTML=a.length?a.map((x,i)=>`<article class="nutritionLibraryCard"><div class="nutritionLibraryIcon">F</div><button type="button" class="nutritionLibrarySelect" data-saved="${i}"><small>${esc(x.source||'Saved food')}</small><b>${esc(x.name)}</b><p>${Math.round(x.defaultGrams||100)} g · ${Math.round(x.per100.cal*(x.defaultGrams||100)/100)} kcal</p></button><button type="button" class="nutritionLibraryAdd" data-saved-add="${i}" aria-label="Add ${esc(x.name)}">+</button></article>`).join(''):nutritionEmpty('No saved foods','Choose “Save/update in My Foods” when logging a food.');$$('[data-saved]').forEach(b=>b.onclick=()=>setFoodBase(a[+b.dataset.saved]));$$('[data-saved-add]').forEach(b=>b.onclick=()=>queueFoodProduct(a[+b.dataset.savedAdd]))}
function renderRecipes(){let host=$('recipeResults');if(!host)return;let a=recipes();host.innerHTML=a.length?a.map((r,i)=>{let q=nutritionMealSummary(r.items||[]);return`<article class="nutritionLibraryCard"><div class="nutritionLibraryIcon">R</div><div><small>${esc(r.items?.[0]?.meal||'Meal')} recipe</small><b>${esc(r.name)}</b><p>${r.items.length} foods · ${Math.round(q.cal)} kcal · ${Math.round(q.p)}g protein</p></div><button type="button" class="nutritionLibraryAdd" data-recipe="${i}" aria-label="Add ${esc(r.name)}">+</button></article>`}).join(''):nutritionEmpty('No recipes saved','Use “Save meal” on the diary to create a reusable recipe.');$$('[data-recipe]').forEach(b=>b.onclick=()=>{let r=a[+b.dataset.recipe];stageFoodItems(r.items,r.name)})}

function mealScanFileData(file){return new Promise((resolve,reject)=>{let reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('Could not read this photo.'));reader.readAsDataURL(file)})}
async function prepareMealScan(file){resetMealScan();if(!file)return;if(!/^image\/(?:jpeg|png|webp)$/i.test(file.type||''))return setMealScanStatus('Use a JPG, PNG or WebP photo.',true);if(file.size>12_000_000)return setMealScanStatus('Choose a meal photo under 12 MB.',true);try{let raw=await mealScanFileData(file),img=new Image;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(Error('This image could not be opened.'));img.src=raw});let scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);mealScanImageDataUrl=canvas.toDataURL('image/jpeg',.84);$('mealScanPreview').innerHTML=`<img src="${mealScanImageDataUrl}" alt="Meal photo ready to analyze">`;$('mealScanPreview').hidden=false;$('analyzeMealPhoto').disabled=false;setMealScanStatus('Photo ready. AI estimates can be wrong; review every food before saving.')}catch(e){setMealScanStatus(e.message||'Could not prepare this photo.',true)}}
function setMealScanStatus(message,error=false){let el=$('mealScanStatus');if(!el)return;el.textContent=message;el.classList.toggle('error',error)}
function resetMealScan(){mealScanImageDataUrl='';let input=$('mealScanPhoto'),preview=$('mealScanPreview'),button=$('analyzeMealPhoto');if(input)input.value='';if(preview){preview.innerHTML='';preview.hidden=true}if(button){button.disabled=true;button.textContent='Analyze meal photo'}if($('mealScanStatus'))setMealScanStatus('The photo is sent to OpenAI for this analysis only and is not saved by Work + Workout.')}
async function analyzeMealPhoto(){if(!mealScanImageDataUrl)return setMealScanStatus('Take or choose a meal photo first.',true);let A=window.WGC18;if(!A?.session)return setMealScanStatus('Sign in to use Meal Scan.',true);let button=$('analyzeMealPhoto');button.disabled=true;button.textContent='Analyzing…';setMealScanStatus('Identifying the visible foods and estimating portions…');try{if(typeof A.ensureHealthConsent!=='function'||!await A.ensureHealthConsent({interactive:true,purpose:'meal_scan_ai'}))throw Error('Meal Scan remains off until you allow its one-time photo analysis.');let j=await A.authedFetch('meal-scan',{method:'POST',body:JSON.stringify({imageDataUrl:mealScanImageDataUrl})}),products=(j.items||[]).map(x=>({name:x.name,brand:'',code:'',source:'AI meal scan estimate',defaultGrams:x.defaultGrams,per100:x.per100,img:''}));if(!products.length)throw Error('No foods could be identified confidently. Try a clearer overhead photo.');stageFoodItems(products.map(foodDraftFromProduct),'Meal Scan');let count=products.length;resetMealScan();foodTab('history');toast(`${count} estimated ${count===1?'food':'foods'} ready to review`)}catch(e){setMealScanStatus(e.message||'Meal Scan could not analyze this photo.',true);button.disabled=false;button.textContent='Try again'}}
