// Diary UI ------------------------------------------------------------------
const MEALS=['Breakfast','Lunch','Dinner','Snacks'];
function renderDiary(){let k=$('diaryDate')?.value||dkey(),t=target(k),a=totals(k),left=Math.round(t.cal-a.cal);if(!$('calRemaining'))return;$('calRemaining').textContent=left;$('calGoal').textContent=t.cal;$('calFood').textContent=Math.round(a.cal);$('calLeftSmall').textContent=left;let ms=[['Protein',a.p,t.p,'g'],['Carbs',a.c,t.c,'g'],['Fat',a.f,t.f,'g'],['Fiber',a.fiber,t.fiber,'g'],['Sodium',a.sodium,t.sodium,'mg'],['Sat fat',a.satFat,t.satFat,'g']];$('macroGrid').innerHTML=ms.map(([n,v,g,u])=>`<div class="macroLine"><label><span>${n}</span><span>${Math.round(v)} / ${Math.round(g)} ${u}</span></label><div class="track"><i style="width:${Math.min(100,g?v/g*100:0)}%"></i></div></div>`).join('');let dist=MEALS.map(m=>({m,p:mealTotals(k,m).p}));$('proteinDistribution').textContent=`Protein distribution: ${dist.map(x=>`${x.m} ${Math.round(x.p)}g`).join(' · ')}. Aim to spread protein across 3–4 meals when practical.`;
 let entries=diary(k),html='';for(const meal of MEALS){let ar=entries.filter(x=>x.meal===meal),sum=ar.reduce((z,x)=>z+foodTotals(x).cal,0);html+=`<section class="meal"><div class="mealHead"><h3>${meal} <small>${Math.round(sum)} kcal</small></h3><div class="mealActions"><button data-save-recipe="${meal}">Save meal</button><button data-add-food="${meal}">+ Food</button></div></div>${ar.length?ar.map(x=>{let q=foodTotals(x);return`<button class="foodRow" data-food-id="${esc(x.id)}" aria-label="Edit ${esc(x.name)}"><div><div class="foodName">${esc(x.name)}</div><div class="foodSub">${Math.round(x.grams)} g · P ${q.p.toFixed(1)} · C ${q.c.toFixed(1)} · F ${q.f.toFixed(1)}${x.source?` · ${esc(x.source)}`:''}</div></div><div class="foodCal">${Math.round(q.cal)}</div></button>`}).join(''):'<div class="emptyMeal">No foods logged</div>'}</section>`}$('mealList').innerHTML=html;$$('[data-add-food]').forEach(b=>b.onclick=()=>openFood(b.dataset.addFood));$$('[data-food-id]').forEach(b=>b.onclick=()=>editFoodEntry(b.dataset.foodId));$$('[data-save-recipe]').forEach(b=>b.onclick=()=>saveMealRecipe(k,b.dataset.saveRecipe));let water=+(localStorage.getItem(K.water+k)||0);$('waterText').textContent=`${water} / ${t.water} oz`}
function saveMealRecipe(k,meal){let items=diary(k).filter(x=>x.meal===meal);if(!items.length)return toast('No foods in this meal');let name=prompt('Recipe name:',meal+' meal');if(!name)return;let r=jget(K.recipes,[]);r.unshift({id:uid('recipe'),name,items:structuredClone(items),createdAt:new Date().toISOString()});jset(K.recipes,r.slice(0,100));toast('Recipe saved')}

// Food modal/search/scanner -------------------------------------------------
function openFood(meal='Breakfast'){foodState={editId:null,base:null,meal};clearFoodForm();$('foodMeal').value=meal;openModal('foodDialog');foodTab('search');renderRecentFoods();renderSavedFoods();renderRecipes()}
function clearFoodForm(){['foodName','foodGrams','foodCal','foodProtein','foodCarbs','foodFat','foodFiber','foodSatFat','foodSodium'].forEach(id=>{if($(id))$(id).value=''});$('foodGrams').value=100;$('saveToMyFoods').checked=false;$('deleteFoodEntry').classList.add('hidden');$('foodSourceCard').innerHTML=''}
function foodTab(t){$$('#foodTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.tabPane').forEach(p=>p.classList.toggle('active',p.id==='foodPane-'+t));if(t!=='scan')stopBarcode()}
function myFoods(){return jget(K.foods,[])}function recentFoods(){return jget(K.recent,[])}
function recipes(){return jget(K.recipes,[])}
function setFoodBase(p){foodState.base=p;$('foodName').value=p.name||'';$('foodGrams').value=p.defaultGrams||100;updateFoodTotalsFromBase();$('foodSourceCard').innerHTML=`<div class="sourceCard"><b>${esc(p.name)}</b>${p.brand?` · ${esc(p.brand)}`:''}<br>Source: ${esc(p.source||'Manual')} · values normalized per 100 g${p.defaultGrams?` · default ${Math.round(p.defaultGrams)} g`:''}</div>`;let r=recentFoods().filter(x=>x.code!==p.code||x.name!==p.name);r.unshift(p);jset(K.recent,r.slice(0,20))}
function updateFoodTotalsFromBase(){if(!foodState.base)return;let g=+$('#foodGrams').value||100,q=g/100,p=foodState.base.per100;$('#foodCal').value=(p.cal*q).toFixed(1);$('#foodProtein').value=(p.p*q).toFixed(1);$('#foodCarbs').value=(p.c*q).toFixed(1);$('#foodFat').value=(p.f*q).toFixed(1);$('#foodFiber').value=(p.fiber*q).toFixed(1);$('#foodSatFat').value=(p.satFat*q).toFixed(1);$('#foodSodium').value=(p.sodium*q).toFixed(0)}
function per100FromForm(){let g=Math.max(.1,+$('#foodGrams').value||100),q=100/g;return{cal:(+$('#foodCal').value||0)*q,p:(+$('#foodProtein').value||0)*q,c:(+$('#foodCarbs').value||0)*q,f:(+$('#foodFat').value||0)*q,fiber:(+$('#foodFiber').value||0)*q,satFat:(+$('#foodSatFat').value||0)*q,sodium:(+$('#foodSodium').value||0)*q}}
function saveFoodEntry(){let k=$('diaryDate').value,a=diary(k),x={id:foodState.editId||uid('food'),name:$('#foodName').value.trim()||'Food',meal:$('#foodMeal').value,grams:Math.max(.1,+$('#foodGrams').value||100),per100:per100FromForm(),source:foodState.base?.source||'Manual',code:foodState.base?.code||''};if(foodState.editId)a=a.map(z=>z.id===foodState.editId?x:z);else a.push(x);saveDiary(k,a);if($('#saveToMyFoods').checked){let f=myFoods().filter(z=>z.name.toLowerCase()!==x.name.toLowerCase());f.unshift({name:x.name,brand:'',code:x.code,source:x.source,defaultGrams:x.grams,per100:x.per100});jset(K.foods,f.slice(0,300))}closeModal('foodDialog')}
function editFoodEntry(id){let x=diary($('diaryDate').value).find(z=>z.id===id);if(!x)return;foodState={editId:id,base:{name:x.name,source:x.source||'Saved entry',code:x.code||'',defaultGrams:x.grams,per100:x.per100},meal:x.meal};openModal('foodDialog');foodTab('manual');$('#foodName').value=x.name;$('#foodMeal').value=x.meal;$('#foodGrams').value=x.grams;let t=foodTotals(x);$('#foodCal').value=t.cal.toFixed(1);$('#foodProtein').value=t.p.toFixed(1);$('#foodCarbs').value=t.c.toFixed(1);$('#foodFat').value=t.f.toFixed(1);$('#foodFiber').value=t.fiber.toFixed(1);$('#foodSatFat').value=t.satFat.toFixed(1);$('#foodSodium').value=t.sodium.toFixed(0);$('#deleteFoodEntry').classList.remove('hidden');$('#foodSourceCard').innerHTML=`<div class="sourceCard">Editing saved entry · ${Math.round(x.grams)} g. Values remain normalized internally, so changing grams does not double-scale.</div>`}
function deleteFoodEntry(){if(!foodState.editId)return;let k=$('diaryDate').value;saveDiary(k,diary(k).filter(x=>x.id!==foodState.editId));closeModal('foodDialog')}

const BUILTIN_FOODS=[
 {name:'Chicken breast, cooked',source:'Built-in generic food',defaultGrams:170,per100:{cal:165,p:31,c:0,f:3.6,fiber:0,satFat:1,sodium:74}},
 {name:'White rice, cooked',source:'Built-in generic food',defaultGrams:158,per100:{cal:130,p:2.7,c:28.2,f:.3,fiber:.4,satFat:.08,sodium:1}},
 {name:'Brown rice, cooked',source:'Built-in generic food',defaultGrams:195,per100:{cal:123,p:2.7,c:25.6,f:1,fiber:1.6,satFat:.26,sodium:4}},
 {name:'Whole egg',source:'Built-in generic food',defaultGrams:50,per100:{cal:143,p:12.6,c:.7,f:9.5,fiber:0,satFat:3.1,sodium:142}},
 {name:'Egg whites',source:'Built-in generic food',defaultGrams:100,per100:{cal:52,p:10.9,c:.7,f:.2,fiber:0,satFat:0,sodium:166}},
 {name:'Greek yogurt, nonfat plain',source:'Built-in generic food',defaultGrams:170,per100:{cal:59,p:10.3,c:3.6,f:.4,fiber:0,satFat:.1,sodium:36}},
 {name:'Oats, dry',source:'Built-in generic food',defaultGrams:40,per100:{cal:379,p:13.2,c:67.7,f:6.5,fiber:10.1,satFat:1.2,sodium:6}},
 {name:'Banana',source:'Built-in generic food',defaultGrams:118,per100:{cal:89,p:1.1,c:22.8,f:.3,fiber:2.6,satFat:.1,sodium:1}},
 {name:'Apple',source:'Built-in generic food',defaultGrams:182,per100:{cal:52,p:.3,c:13.8,f:.2,fiber:2.4,satFat:.03,sodium:1}},
 {name:'Salmon, cooked',source:'Built-in generic food',defaultGrams:170,per100:{cal:206,p:22.1,c:0,f:12.4,fiber:0,satFat:3.1,sodium:59}},
 {name:'Ground turkey 93% lean, cooked',source:'Built-in generic food',defaultGrams:113,per100:{cal:203,p:27.4,c:0,f:10.4,fiber:0,satFat:2.8,sodium:92}},
 {name:'Sweet potato, baked',source:'Built-in generic food',defaultGrams:180,per100:{cal:90,p:2,c:20.7,f:.15,fiber:3.3,satFat:.03,sodium:36}},
 {name:'Broccoli, cooked',source:'Built-in generic food',defaultGrams:156,per100:{cal:35,p:2.4,c:7.2,f:.4,fiber:3.3,satFat:.08,sodium:41}},
 {name:'Avocado',source:'Built-in generic food',defaultGrams:100,per100:{cal:160,p:2,c:8.5,f:14.7,fiber:6.7,satFat:2.1,sodium:7}},
 {name:'Whey protein powder',source:'Built-in generic food',defaultGrams:32,per100:{cal:375,p:75,c:12.5,f:6.3,fiber:0,satFat:3.1,sodium:500}}
].map(x=>({...x,brand:'',code:'',img:''}));
function builtinFoodMatches(q){q=q.toLowerCase();let terms=q.split(/\s+/).filter(Boolean);return BUILTIN_FOODS.filter(x=>terms.every(t=>x.name.toLowerCase().includes(t))).slice(0,8)}
