function normalizeOFF(p){let n=p.nutriments||{},num=k=>+n[k+'_100g']||0,grams=+p.serving_quantity||parseFloat(String(p.serving_size||'').match(/[\d.]+/)?.[0])||100;return{name:p.product_name||p.generic_name||'Unnamed food',brand:p.brands||'',code:p.code||'',source:'Open Food Facts',defaultGrams:grams,per100:{cal:num('energy-kcal')||(+n.energy_100g||0)/4.184,p:num('proteins'),c:num('carbohydrates'),f:num('fat'),fiber:num('fiber'),satFat:num('saturated-fat'),sodium:num('sodium')*1000},img:p.image_front_small_url||''}}
function foodResult(p){let q=p.per100.cal*(p.defaultGrams||100)/100;return`<button class="result" data-result-code="${esc(p.code||'')}" data-result-name="${esc(p.name)}"><span>${p.img?`<img src="${esc(p.img)}" alt="">`:'<span class="ph">◉</span>'}</span><span><b>${esc(p.name)}</b><small>${esc(p.brand)} · ${Math.round(p.defaultGrams||100)} g · ${esc(p.source)}</small></span><strong>${Math.round(q)} kcal</strong></button>`}
let lastSearchProducts=[];
async function searchFood(){let q=$('foodSearchInput').value.trim();if(!q)return;let built=builtinFoodMatches(q);$('foodSearchResults').innerHTML=built.length?'<p class="muted">Generic foods shown first. Searching packaged foods…</p>'+built.map(foodResult).join(''):'<p class="muted">Searching packaged foods…</p>';try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',u=`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(q)}&search_simple=1&action=process&json=1&page_size=20&fields=${fields}`,r=await fetch(u),j=await r.json();let off=(j.products||[]).map(normalizeOFF).filter(x=>x.name&&x.per100.cal>0);lastSearchProducts=[...built,...off];$('foodSearchResults').innerHTML=lastSearchProducts.length?lastSearchProducts.map(foodResult).join(''):'<p class="muted">No matching foods found. Try a simpler name or Manual.</p>';bindFoodResults()}catch{lastSearchProducts=built;$('foodSearchResults').innerHTML=built.length?built.map(foodResult).join('')+'<p class="muted">Packaged-food search is offline; generic foods are still available.</p>':'<p class="muted">Food search failed. Check your internet connection or use Manual.</p>';bindFoodResults()}}
function bindFoodResults(){$$('#foodSearchResults .result').forEach((b,i)=>b.onclick=()=>setFoodBase(lastSearchProducts[i]))}
async function lookupBarcode(code){code=String(code||'').replace(/\D/g,'');if(!code)return setBarcodeStatus('Enter a UPC/EAN barcode.');setBarcodeStatus('Looking up '+code+' in Open Food Facts…');try{let fields='code,product_name,generic_name,brands,nutriments,serving_size,serving_quantity,image_front_small_url',r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=${fields}`),j=await r.json();if(j.status===1&&j.product){setFoodBase(normalizeOFF({...j.product,code}));setBarcodeStatus('✓ Product found. Review the serving and nutrition values.');stopBarcode()}else setBarcodeStatus('✓ Barcode decoded, but no exact Open Food Facts product was found. Search by product name or use Manual.')}catch{setBarcodeStatus('Barcode lookup failed. Check your internet connection.') }}
function setBarcodeStatus(t){$('#barcodeStatus').textContent=t}
const SCANNER_URL='/work-gym-planner-v16/vendor/html5-qrcode/html5-qrcode.min.js';
async function ensureScanner(){if(window.Html5Qrcode)return true;return new Promise(resolve=>{let s=document.createElement('script');s.src=SCANNER_URL;s.onload=()=>resolve(!!window.Html5Qrcode);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
let nativeBarcodeStream=null,nativeBarcodeTimer=null;
async function nativeBarcodeDetector(){if(!('BarcodeDetector' in window))return null;try{let wanted=['ean_13','ean_8','upc_a','upc_e'];let supported=BarcodeDetector.getSupportedFormats?await BarcodeDetector.getSupportedFormats():wanted,formats=wanted.filter(x=>supported.includes(x));return new BarcodeDetector(formats.length?{formats}:undefined)}catch{return null}}
async function startBarcode(){await stopBarcode();if(!navigator.mediaDevices?.getUserMedia){setBarcodeStatus('Live camera is blocked in this in-app browser. Open the planner in Safari or the Home Screen app, then retry. Photo barcode scanning can still be used here.');return}let native=await nativeBarcodeDetector();if(native){try{let v=document.createElement('video');v.playsInline=true;v.muted=true;v.style.width='100%';v.style.maxHeight='260px';v.style.objectFit='cover';$('#barcodeReader').appendChild(v);nativeBarcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=nativeBarcodeStream;await v.play();setBarcodeStatus('Camera ready. Center the full UPC/EAN barcode and hold steady.');nativeBarcodeTimer=setInterval(async()=>{try{let r=await native.detect(v),code=r?.[0]?.rawValue;if(code){await stopBarcode();lookupBarcode(code)}}catch{}},300);return}catch{await stopBarcode()}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load. Check internet and retry.');return}try{barcodeScanner=new Html5Qrcode('barcodeReader');await barcodeScanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:140},formatsToSupport:window.Html5QrcodeSupportedFormats?[Html5QrcodeSupportedFormats.EAN_13,Html5QrcodeSupportedFormats.EAN_8,Html5QrcodeSupportedFormats.UPC_A,Html5QrcodeSupportedFormats.UPC_E]:undefined},txt=>lookupBarcode(txt),()=>{});setBarcodeStatus('Camera ready. Center the full barcode in the box and hold steady.')}catch(e){setBarcodeStatus('Live scan could not start. Use Safari/Home Screen or scan a barcode photo.') }}
async function stopBarcode(){if(nativeBarcodeTimer){clearInterval(nativeBarcodeTimer);nativeBarcodeTimer=null}if(nativeBarcodeStream){nativeBarcodeStream.getTracks().forEach(t=>t.stop());nativeBarcodeStream=null}if(barcodeScanner){try{if(barcodeScanner.isScanning)await barcodeScanner.stop();await barcodeScanner.clear()}catch{}barcodeScanner=null}if($('#barcodeReader'))$('#barcodeReader').innerHTML=''}
async function scanBarcodePhoto(file){if(!file)return;await stopBarcode();setBarcodeStatus('Reading barcode from photo…');let native=await nativeBarcodeDetector();if(native){try{let bmp=await createImageBitmap(file),r=await native.detect(bmp),code=r?.[0]?.rawValue;bmp.close?.();if(code){$('#barcodePhoto').value='';return lookupBarcode(code)}}catch{}}
 if(!(await ensureScanner())){setBarcodeStatus('Barcode scanner fallback could not load.');$('#barcodePhoto').value='';return}try{barcodeScanner=new Html5Qrcode('barcodeReader');let txt=await barcodeScanner.scanFile(file,true);await lookupBarcode(txt)}catch{setBarcodeStatus('No UPC/EAN barcode could be read. Retake the photo closer, sharp, and with the entire barcode visible.')}finally{try{await barcodeScanner?.clear()}catch{}barcodeScanner=null;$('#barcodePhoto').value=''}}
function renderRecentFoods(){let a=recentFoods();$('#recentFoods').innerHTML=a.slice(0,12).map((x,i)=>`<button data-recent="${i}">${esc(x.name)}</button>`).join('');$$('[data-recent]').forEach(b=>b.onclick=()=>setFoodBase(a[+b.dataset.recent]))}
function renderSavedFoods(){let q=($('#savedFoodSearch')?.value||'').toLowerCase(),a=myFoods().filter(x=>!q||x.name.toLowerCase().includes(q));$('#savedFoodResults').innerHTML=a.length?a.map((x,i)=>`<button class="result" data-saved="${i}"><span class="ph">★</span><span><b>${esc(x.name)}</b><small>${esc(x.source||'Saved')} · ${Math.round(x.defaultGrams||100)} g</small></span><strong>${Math.round(x.per100.cal*(x.defaultGrams||100)/100)} kcal</strong></button>`).join(''):'<p class="muted">No saved foods yet.</p>';$$('[data-saved]').forEach(b=>b.onclick=()=>setFoodBase(a[+b.dataset.saved]))}
function renderRecipes(){let a=recipes();$('#recipeResults').innerHTML=a.length?a.map((r,i)=>`<button class="result" data-recipe="${i}"><span class="ph">🥣</span><span><b>${esc(r.name)}</b><small>${r.items.length} foods · one-tap log</small></span><strong>${Math.round(r.items.reduce((z,x)=>z+foodTotals(x).cal,0))} kcal</strong></button>`).join(''):'<p class="muted">No saved recipes yet.</p>';$$('[data-recipe]').forEach(b=>b.onclick=()=>{let r=a[+b.dataset.recipe],k=$('diaryDate').value,meal=foodState.meal||'Breakfast',items=r.items.map(x=>({...structuredClone(x),id:uid('food'),meal}));saveDiary(k,[...diary(k),...items]);closeModal('foodDialog');toast('Recipe logged')})}
