// v18 workout library: movement guidance + demonstration links ----------------
(function(){
const LIB=[
['Barbell Back Squat','Legs','Barbell','Quads, glutes, adductors','Brace before unracking. Sit between the hips while knees track over toes. Keep the whole foot planted and drive the floor away.','Losing brace; heels lifting; knees collapsing inward.'],
['Hack Squat','Legs','Hack squat machine','Quads, glutes','Set shoulders and back firmly on the pad. Place feet where you can keep heels down. Lower under control to your comfortable depth, then drive through the whole foot.','Hips rolling off pad; bouncing at the bottom; locking knees aggressively.'],
['Leg Press','Legs','Leg press','Quads, glutes','Set the seat so the pelvis stays against the pad at depth. Keep feet planted, lower with control and press without snapping the knees straight.','Lower back rounding; shallow uncontrolled reps; hands pushing on knees.'],
['Romanian Deadlift','Legs','Barbell or dumbbells','Hamstrings, glutes, erectors','Soft knees, brace, then push hips backward while keeping the load close. Stop when hamstrings are loaded without losing spinal position; stand by driving hips forward.','Turning it into a squat; load drifting forward; chasing floor depth.'],
['Bulgarian Split Squat','Legs','Dumbbells or bodyweight','Quads, glutes','Use a stance long enough to keep the front foot planted. Lower the back knee toward the floor while controlling the front knee, then drive through the front leg.','Too narrow a stance; pushing mainly from rear foot; losing balance by rushing.'],
['Leg Extension','Legs','Leg extension machine','Quadriceps','Align the machine pivot with the knee, pad above the ankle, and keep hips against the seat. Extend smoothly and lower under control.','Seat misalignment; kicking with momentum; excessive load.'],
['Seated Leg Curl','Legs','Leg curl machine','Hamstrings','Align knee with the machine pivot, secure the thigh pad, curl through a comfortable range and control the return.','Hips lifting; rushing the eccentric; poor machine alignment.'],
['Standing Calf Raise','Legs','Calf machine or dumbbells','Gastrocnemius, soleus','Use a stable support. Lower the heel under control, pause in the stretch, rise onto the ball of the foot and squeeze.','Bouncing; rolling ankles outward; shortening the range.'],
['Barbell Bench Press','Chest','Barbell bench','Chest, triceps, front delts','Plant feet, set shoulder blades back/down, keep wrists stacked and lower the bar under control to the lower-mid chest. Press up and slightly back.','Elbows flared excessively; shoulders rolling forward; bouncing bar.'],
['Incline Dumbbell Press','Chest','Dumbbells + incline bench','Upper chest, triceps, front delts','Use a modest incline, set shoulder blades, lower dumbbells beside the upper chest with forearms near vertical, then press without clanking them together.','Bench too steep; shoulders shrugging; excessive depth without control.'],
['Machine Chest Press','Chest','Chest press machine','Chest, triceps','Adjust seat so handles align around mid-chest. Keep torso and shoulder blades supported, press smoothly and control the return.','Seat too high/low; shoulders reaching forward; slamming the stack.'],
['Cable Fly','Chest','Cable station','Chest','Use a split stance and soft elbows. Bring upper arms across the body in an arc, squeeze the chest, then return only as far as you can control.','Turning it into a press; over-stretching shoulder; using momentum.'],
['Lat Pulldown','Back','Cable pulldown','Lats, upper back, biceps','Secure thighs, lean back slightly, pull elbows down toward your sides while bringing the bar toward upper chest, then reach up under control.','Pulling behind neck; excessive body swing; curling with arms only.'],
['Seated Cable Row','Back','Cable row','Mid-back, lats, biceps','Brace torso, initiate by drawing shoulder blades and elbows back, pull toward lower ribs, then allow a controlled reach without collapsing.','Rocking torso; shrugging; yanking the handle.'],
['Chest-Supported Row','Back','Machine or incline bench','Mid-back, lats, rear delts','Keep chest supported and neck neutral. Drive elbows back/down and pause briefly before lowering fully.','Lifting chest off pad; shrugging; shortening the eccentric.'],
['Pull-Up','Back','Pull-up bar','Lats, upper back, biceps','Start from a controlled hang, brace, pull elbows toward ribs until chin clears comfortably, then lower to full control.','Kipping unintentionally; craning neck; dropping from top.'],
['Dumbbell Shoulder Press','Shoulders','Dumbbells','Delts, triceps','Brace torso, begin with forearms near vertical and press overhead while keeping ribs controlled. Lower to a comfortable shoulder position.','Overarching low back; flaring ribs; forcing painful depth.'],
['Cable Lateral Raise','Shoulders','Cable station','Side delts','Stand stable with a soft elbow. Raise the arm in the scapular plane to around shoulder height, then lower slowly.','Shrugging; swinging torso; going too heavy.'],
['Face Pull','Shoulders','Cable + rope','Rear delts, external rotators, upper back','Set rope around face height. Pull toward the forehead while separating the rope and rotating hands back; control the return.','Low cable angle; lumbar lean; turning it into a row.'],
['Triceps Pressdown','Arms','Cable station','Triceps','Keep upper arms near your sides and extend the elbows fully without moving the shoulders much. Return under control.','Elbows drifting forward; torso bouncing; wrists collapsing.'],
['Overhead Cable Triceps Extension','Arms','Cable station','Triceps long head','Brace, keep upper arms relatively fixed and bend/extend at the elbows through a comfortable overhead range.','Ribs flaring; elbows wandering; excessive load.'],
['Dumbbell Curl','Arms','Dumbbells','Biceps','Stand tall, keep upper arms quiet, curl without swinging and lower until elbows are comfortably extended.','Hip drive; shoulders rolling forward; dropping the eccentric.'],
['Hammer Curl','Arms','Dumbbells','Brachialis, brachioradialis, biceps','Keep palms facing each other, elbows near sides and curl smoothly without leaning back.','Swinging; elbows traveling far forward; wrist bending.'],
['Cable Crunch','Core','Cable station','Abdominals','Set cable above head, keep hips relatively fixed and curl ribs toward pelvis. Return without letting the stack yank you upright.','Hinging mostly at hips; pulling with arms; excessive load.'],
['Plank','Core','Bodyweight','Abdominals, trunk','Stack elbows under shoulders, squeeze glutes, brace as if preparing for a punch and keep ribs/pelvis controlled.','Sagging hips; holding breath; shrugging into shoulders.']
].map((x,i)=>({id:'ex'+(i+1),name:x[0],category:x[1],equipment:x[2],muscles:x[3],how:x[4],mistakes:x[5],video:`https://www.youtube.com/results?search_query=${encodeURIComponent(x[0]+' proper form exercise demonstration')}`}));
window.EXERCISE_LIBRARY_V18=LIB;
function card(x){return `<article class="exerciseCard18"><div class="exerciseIcon18">${x.category==='Legs'?'🦵':x.category==='Chest'?'🏋️':x.category==='Back'?'🔙':x.category==='Shoulders'?'💪':x.category==='Arms'?'💪':'◎'}</div><div><h3>${esc(x.name)}</h3><p>${esc(x.muscles)} · ${esc(x.equipment)}</p><details><summary>How to perform</summary><p>${esc(x.how)}</p><b>Common mistakes</b><p>${esc(x.mistakes)}</p><a class="demoLink18" href="${x.video}" target="_blank" rel="noopener">▶ Find video demonstration</a></details></div></article>`}
function renderLibrary18(){let q=($('#librarySearch18')?.value||'').toLowerCase(),cat=$('#libraryCat18')?.value||'',a=LIB.filter(x=>(!cat||x.category===cat)&&(!q||[x.name,x.category,x.equipment,x.muscles].join(' ').toLowerCase().includes(q)));$('#libraryResults18').innerHTML=a.map(card).join('')||'<p class="muted">No movements match that search.</p>'}
function installLibrary18(){let app=$('#appRoot'),more=$('#page-more');if(app&&more&&!$('#page-library')){let s=document.createElement('section');s.id='page-library';s.className='page';s.innerHTML='<div class="pageHead"><div><small>Movement guide</small><h2>Workout Library</h2></div></div><div class="libraryTools18"><input id="librarySearch18" placeholder="Search exercise, muscle or equipment"><select id="libraryCat18"><option value="">All</option><option>Legs</option><option>Chest</option><option>Back</option><option>Shoulders</option><option>Arms</option><option>Core</option></select></div><div id="libraryResults18"></div>';app.insertBefore(s,more);$('#librarySearch18').oninput=renderLibrary18;$('#libraryCat18').onchange=renderLibrary18;renderLibrary18()}let cards=$('#page-more .menuCards');if(cards&&!$('#libraryMenu18')){let b=document.createElement('button');b.id='libraryMenu18';b.innerHTML='<span>🎬</span><div><b>Workout library</b><small>Technique, mistakes & video demonstrations</small></div><i>›</i>';b.onclick=()=>page('library');cards.prepend(b)}let st=document.createElement('style');if(!$('#libraryStyle18')){st.id='libraryStyle18';st.textContent='.libraryTools18{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:12px}.libraryTools18 input,.libraryTools18 select{min-height:44px}.exerciseCard18{display:grid;grid-template-columns:42px 1fr;gap:10px;padding:13px;margin:9px 0;border:1px solid var(--line);border-radius:15px;background:var(--card)}.exerciseIcon18{font-size:22px}.exerciseCard18 h3{margin:0 0 3px}.exerciseCard18 p{margin:4px 0;color:var(--muted)}.exerciseCard18 summary{font-weight:800;margin-top:7px;cursor:pointer}.demoLink18{display:inline-block;margin-top:8px;font-weight:800}.pageHead h2{margin-top:2px}@media(max-width:480px){.libraryTools18{grid-template-columns:1fr}}';document.head.appendChild(st)}}
installLibrary18();document.addEventListener('DOMContentLoaded',()=>setTimeout(installLibrary18,0));
})();
