// Reminders / calendar export ------------------------------------------------
function notificationSettings(){return{workout:true,schedule:true,protein:false,...jget(K.notification,{})}}
function saveNotificationSettings(x){jset(K.notification,x)}
async function requestNotificationPermission(){if(!('Notification'in window))return'unsupported';let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();return p}
async function showPlannerNotification(title,body){let p=await requestNotificationPermission();if(p!=='granted')return false;let reg=await navigator.serviceWorker?.getRegistration?.();if(reg?.showNotification)await reg.showNotification(title,{body,icon:'../work-gym-planner-v16/icons/icon-192.png',badge:'../work-gym-planner-v16/icons/icon-192.png',tag:'wgp-'+title});else new Notification(title,{body});return true}
function maybeNotifyOnLaunch(){let n=notificationSettings(),today=dkey(),notes=[];if(n.schedule&&workState(today).kind==='unknown')notes.push(`${profile()?.variable?.name||'Variable work'} is still unknown today.`);if(n.workout&&isScheduled(today)&&!completedOn(today))notes.push(`${WORKOUTS[projectedWorkoutIndex(today)].name} is planned today.`);if(n.protein){let t=target(today),x=totals(today);if(x.cal>500&&x.p<t.p*.7&&new Date().getHours()>=18)notes.push(`${Math.round(t.p-x.p)} g protein remains today.`)}if(notes.length&&typeof Notification!=='undefined'&&Notification.permission==='granted')showPlannerNotification('Work + Gym Planner',notes.join(' '))}
function icsEscape(s){return String(s).replace(/\\/g,'\\\\').replace(/,/g,'\\,').replace(/;/g,'\\;').replace(/\n/g,'\\n')}
function exportWorkoutCalendar(){let start=dkey(),end=addDays(start,84),dates=canonicalScheduleThrough(end).filter(k=>k>=start&&k<=end),stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Work and Workout//Planner 23//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];for(const k of dates){let wi=projectedWorkoutIndex(k),w=WORKOUTS[wi],d=k.replace(/-/g,''),uidv=`wgp-${k}-${wi}@workandworkout.com`;lines.push('BEGIN:VEVENT',`UID:${uidv}`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${d}`,`DTEND;VALUE=DATE:${addDays(k,1).replace(/-/g,'')}`,`SUMMARY:${icsEscape(w.name+' · Work + Workout')}`,`DESCRIPTION:${icsEscape(w.focus+' | '+workText(k)+' | Open the planner for recovery-adjusted sets and RIR.')}`,'BEGIN:VALARM','TRIGGER:-PT12H','ACTION:DISPLAY',`DESCRIPTION:${icsEscape(w.name+' tomorrow')}`,'END:VALARM','END:VEVENT')}lines.push('END:VCALENDAR');downloadBlob(new Blob([lines.join('\r\n')],{type:'text/calendar'}),`work-and-workout-plan-${dkey()}.ics`)}
function renderReminderSettings(){let s=notificationSettings(),box=$('#reminderSettings');if(!box)return;box.innerHTML=`<label class="check"><input id="notifyWorkout" type="checkbox" ${s.workout?'checked':''}> Workout reminders when the app opens</label><label class="check"><input id="notifySchedule" type="checkbox" ${s.schedule?'checked':''}> Unknown work-schedule alerts</label><label class="check"><input id="notifyProtein" type="checkbox" ${s.protein?'checked':''}> Evening protein reminder when the app opens</label><div class="twoButtons"><button id="enableNotifications">Enable/test notification</button><button id="exportWorkoutICS">Add 12 weeks to Calendar</button></div><p class="muted">iPhone web apps cannot reliably schedule background local notifications without a push server. Calendar export adds real iOS Calendar alerts and works without keeping this app open.</p>`;$('#notifyWorkout').onchange=saveReminderForm;$('#notifySchedule').onchange=saveReminderForm;$('#notifyProtein').onchange=saveReminderForm;$('#enableNotifications').onclick=async()=>{let ok=await showPlannerNotification('Notifications enabled','Planner alerts are ready when the app is opened.');if(!ok)toast('Notifications were not enabled')};$('#exportWorkoutICS').onclick=exportWorkoutCalendar}
function saveReminderForm(){saveNotificationSettings({workout:$('#notifyWorkout').checked,schedule:$('#notifySchedule').checked,protein:$('#notifyProtein').checked})}
