// Nutrition / diary ---------------------------------------------------------
function nutritionDefaults(){return{gymCal:2200,restCal:2000,protein:150,fat:70,fiber:30,sodium:2300,satFat:20,water:96,goalWeight:0,goalBf:0,planStart:dkey()}}
function nutrition(){return{...nutritionDefaults(),...jget(K.nutrition,{})}}
function saveNutritionObj(x){jset(K.nutrition,x)}
function target(k){let n=nutrition(),past=k<=dkey(),gym=!!completedOn(k)||(past?!!snapshots()[k]?.planned:isScheduled(k)),cal=gym?+n.gymCal:+n.restCal,p=+n.protein,f=+n.fat,c=Math.max(0,Math.round((cal-p*4-f*9)/4));return{cal,p,c,f,fiber:+n.fiber,sodium:+n.sodium,satFat:+n.satFat,water:+n.water,gym}}
function diary(k){return jget(K.diary+k,[])}function saveDiary(k,a){jset(K.diary+k,a);renderDiary()}
function foodTotals(x){let q=(+x.grams||0)/100,p=x.per100||{};return{cal:(+p.cal||0)*q,p:(+p.p||0)*q,c:(+p.c||0)*q,f:(+p.f||0)*q,fiber:(+p.fiber||0)*q,satFat:(+p.satFat||0)*q,sodium:(+p.sodium||0)*q}}
function totals(k){return diary(k).reduce((a,x)=>{let t=foodTotals(x);for(const z of Object.keys(a))a[z]+=t[z]||0;return a},{cal:0,p:0,c:0,f:0,fiber:0,satFat:0,sodium:0})}
function mealTotals(k,meal){return diary(k).filter(x=>x.meal===meal).reduce((a,x)=>{let t=foodTotals(x);a.cal+=t.cal;a.p+=t.p;return a},{cal:0,p:0})}
function bodyLog(){return jget(K.body,{})}function saveBodyLog(x){jset(K.body,x)}
function loggedDates(){let out=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith(K.diary)&&diary(k.slice(K.diary.length)).length)out.push(k.slice(K.diary.length))}return out.sort()}
function adherenceFor(start,end){let dates=[],ok=0;for(let k=start;k<=end;k=addDays(k,1)){let t=totals(k).cal;if(t>0){dates.push(k);let g=target(k).cal;if(Math.abs(t-g)/g<=.10)ok++}}return{logged:dates.length,onTarget:ok,rate:dates.length?ok/dates.length:0}}
function weightValues(start,end){let b=bodyLog(),a=[];for(let k=start;k<=end;k=addDays(k,1))if(+b[k]?.weight)a.push(+b[k].weight);return a}
function avgWeight(start,end){let a=weightValues(start,end);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function latestMetricBefore(metric,before,days=21){let b=bodyLog(),best=null;for(const [k,x] of Object.entries(b)){if(k<=before&&diffDays(before,k)<=days&&+x[metric]&&(best==null||k>best.k))best={k,v:+x[metric]}}return best}
function bodyRecommendation(){let today=dkey(),curStart=addDays(today,-6),prevStart=addDays(today,-13),prevEnd=addDays(today,-7),curA=adherenceFor(curStart,today),prevA=adherenceFor(prevStart,prevEnd),cw=avgWeight(curStart,today),pw=avgWeight(prevStart,prevEnd),curW=weightValues(curStart,today),prevW=weightValues(prevStart,prevEnd),loggedEnough=curA.logged>=5&&prevA.logged>=5&&curW.length>=3&&prevW.length>=3&&cw&&pw,ad=(curA.rate+prevA.rate)/2,loss=loggedEnough?(pw-cw)/pw*100:null,waistNow=latestMetricBefore('waist',today,10),waistPrev=latestMetricBefore('waist',prevEnd,14),text='Log at least 5 calorie days and 3+ morning weights in each of two consecutive weeks before changing calories.',delta=0;
 if(loggedEnough){if(waistNow&&waistPrev&&waistPrev.v-waistNow.v>=.25&&Math.abs(loss)<.15){text='Weight is fairly stable but waist is down at least 0.25 in. Hold calories — body composition is improving.'}else if(ad<.8){text=`Logging/on-target adherence is ${Math.round(ad*100)}%. Hold calories and improve consistency before changing the target.`}else if(loss<.15){text='Weight loss is below the target range with good adherence. Reduce gym-day and recovery calories by 100.';delta=-100}else if(loss>.75){text='Weight is falling faster than 0.75% per week. Add 100 calories to gym-day and recovery targets.';delta=100}else{text='Weight trend is in the target range. Keep calories unchanged.'}}
 return{text,delta,adherence:ad,loss,cw,pw,curA,prevA}}

// v16 nutrition analytics ----------------------------------------------------
function averageIntake(start,end){let vals=[];for(let k=start;k<=end;k=addDays(k,1)){let t=totals(k);if(t.cal>0)vals.push({k,...t,target:target(k)})}if(!vals.length)return null;let avg=f=>vals.reduce((a,x)=>a+(+x[f]||0),0)/vals.length;return{days:vals.length,cal:avg('cal'),p:avg('p'),fiber:avg('fiber'),satFat:avg('satFat'),sodium:avg('sodium'),rows:vals}}
function proteinAdherence(start,end){let logged=0,hit=0,total=0;for(let k=start;k<=end;k=addDays(k,1)){let t=totals(k);if(t.cal>0){logged++;let goal=target(k).p;total+=Math.min(1,t.p/Math.max(1,goal));if(t.p>=goal*.9)hit++}}return{logged,hit,rate:logged?total/logged:0,daysHitRate:logged?hit/logged:0}}
function weightTrend(days=14,end=dkey()){let b=bodyLog(),start=addDays(end,-days+1),pts=[];for(let k=start;k<=end;k=addDays(k,1))if(+b[k]?.weight)pts.push({k,v:+b[k].weight});if(pts.length<3)return{points:pts,change:null,perWeek:null};let n=pts.length,xs=pts.map(p=>diffDays(p.k,pts[0].k)),ys=pts.map(p=>p.v),mx=xs.reduce((a,b)=>a+b,0)/n,my=ys.reduce((a,b)=>a+b,0)/n,num=xs.reduce((a,x,i)=>a+(x-mx)*(ys[i]-my),0),den=xs.reduce((a,x)=>a+(x-mx)**2,0)||1,slope=num/den;return{points:pts,change:slope*(xs.at(-1)-xs[0]),perWeek:slope*7,slope}}
function maintenanceEstimate(days=14,end=dkey()){let start=addDays(end,-days+1),food=averageIntake(start,end),trend=weightTrend(days,end);if(!food||food.days<8||trend.points.length<5||trend.perWeek==null)return null;let dailyWeightChange=trend.perWeek/7,tdee=food.cal-dailyWeightChange*3500;return{tdee:Math.round(tdee/25)*25,avgCalories:Math.round(food.cal),days:food.days,weightPerWeek:trend.perWeek}}
function nutritionAnalytics(end=dkey()){let a7=averageIntake(addDays(end,-6),end),a14=averageIntake(addDays(end,-13),end),p14=proteinAdherence(addDays(end,-13),end),w7=weightTrend(7,end),w14=weightTrend(14,end),w28=weightTrend(28,end),maint=maintenanceEstimate(14,end);return{a7,a14,p14,w7,w14,w28,maint}}
function nutritionCoachSummary(end=dkey()){let a=nutritionAnalytics(end),parts=[];if(a.a14)parts.push(`14-day intake averages ${Math.round(a.a14.cal)} kcal across ${a.a14.days} logged days`);if(a.p14.logged)parts.push(`protein adherence ${Math.round(a.p14.rate*100)}%`);if(a.w14.perWeek!=null)parts.push(`weight trend ${a.w14.perWeek>0?'+':''}${a.w14.perWeek.toFixed(2)} lb/week`);if(a.maint)parts.push(`estimated maintenance ~${a.maint.tdee} kcal/day`);return parts.length?parts.join(' · '):'Log food and morning weight consistently to unlock maintenance and trend estimates.'}
