// v18 personalized onboarding and deterministic schedule-aware plan builder -----
APP_VERSION='18.2.0';
window.WGC18=window.WGC18||{};
(function(A){
 const ONBOARD_KEY=PREFIX+'onboarding-v18';
 const DRAFT_KEY='wgc-ob-draft';
 const DAYS=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
 const DAY_LONG=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
 let step=0,lastPlan=null,draft=null;
 function m(t){let [h,mm]=String(t||'').split(':').map(Number);return Number.isFinite(h)?h*60+(mm||0):null}
 function tm(min){min=((Math.round(min)%1440)+1440)%1440;return String(Math.floor(min/60)).padStart(2,'0')+':'+String(min%60).padStart(2,'0')}
 function addBlock(a,start,end,label){if(start==null||end==null)return;if(end===start){a.push({start:0,end:1440,label});return}while(start<0){start+=1440;end+=1440}while(start>=1440){start-=1440;end-=1440}if(end>start&&end<=1440)a.push({start,end,label});else if(end>1440){a.push({start,end:1440,label});a.push({start:0,end:end-1440,label})}else if(end<=start){a.push({start,end:1440,label});a.push({start:0,end,label})}}
 function freeWindows(blocks,minLen){let b=blocks.map(x=>({start:Math.max(0,x.start),end:Math.min(1440,x.end),label:x.label})).filter(x=>x.end>x.start).sort((x,y)=>x.start-y.start),merged=[];for(const x of b){let p=merged.at(-1);if(p&&x.start<=p.end)p.end=Math.max(p.end,x.end);else merged.push({...x})}let out=[],cursor=0;for(const x of merged){if(x.start-cursor>=minLen)out.push({start:cursor,end:x.start});cursor=Math.max(cursor,x.end)}if(1440-cursor>=minLen)out.push({start:cursor,end:1440});return out}
 function checked(name){let mounted=$$(`[name="${name}"]`);if(mounted.length)return mounted.filter(x=>x.checked).map(x=>+x.value);return(draft?.checks?.[name]||[]).map(Number)}
 function parseCommitments(text){let out=[];for(const raw of String(text||'').split(/\n+/)){let line=raw.trim();if(!line)continue;let mt=line.match(/^(Sun|Mon|Tue|Wed|Thu|Fri|Sat)(?:day)?\s+(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})(?:\s+(.+))?$/i);if(!mt)continue;let d=DAYS.findIndex(x=>x.toLowerCase()===mt[1].slice(0,3).toLowerCase());out.push({day:d,start:mt[2],end:mt[3],label:mt[4]||'Commitment'})}return out}
 function val(id,f=''){let e=$('#'+id);if(e)return e.value;return draft?.values&&Object.prototype.hasOwnProperty.call(draft.values,id)?draft.values[id]:f}
 function isChecked(id){let e=$('#'+id);return e?e.checked:!!draft?.checks?.[id]}
 function num(id,f=0){let n=+val(id);return Number.isFinite(n)&&n>0?n:f}
 function answers(){preserve();let food=val('obFoods').split(',').map(x=>x.trim()).filter(Boolean).slice(0,30),cuisines=val('obCuisines').split(',').map(x=>x.trim()).filter(Boolean).slice(0,20);return{
  basics:{name:val('obName').trim(),age:num('obAge'),sex:val('obSex','neutral'),heightFt:num('obHeightFt'),heightIn:num('obHeightIn'),weight:num('obWeight'),bodyFat:num('obBodyFat'),goal:val('obGoal','recomp'),goalWeight:num('obGoalWeight'),goalBodyFat:num('obGoalBf'),activity:val('obActivity','moderate'),sleepHours:num('obSleepHours',7.5),bedtime:val('obBedtime','23:00')},
  work:{primaryName:val('obJob1Name').trim()||'Primary job',primaryDays:checked('obJob1Day'),primaryStart:val('obJob1Start'),primaryEnd:val('obJob1End'),primaryCommute:num('obJob1Commute',0),secondaryEnabled:isChecked('obJob2Enabled'),secondaryName:val('obJob2Name').trim()||'Secondary job',secondaryDays:checked('obJob2Day'),secondaryStart:val('obJob2Start'),secondaryEnd:val('obJob2End'),secondaryCommute:num('obJob2Commute',0),commitments:parseCommitments(val('obCommitments'))},
  training:{days:clamp(num('obTrainingDays',3),2,4),duration:clamp(num('obDuration',60),30,120),experience:val('obExperience','intermediate'),equipment:val('obEquipment','full'),preferred:val('obPreferred','flexible'),limitations:val('obLimitations').trim()},
  nutrition:{foods:food,cuisines,restrictions:val('obRestrictions').trim(),meals:clamp(num('obMeals',3),2,6),budget:val('obBudget','moderate'),cook:val('obCook','moderate')}
 }}
 function metabolic(a){let b=a.basics,wkg=b.weight*.45359237,cm=(b.heightFt*12+b.heightIn)*2.54,bmr;if(b.bodyFat>0&&b.bodyFat<60)bmr=370+21.6*wkg*(1-b.bodyFat/100);else{let sex=b.sex==='male'?5:b.sex==='female'?-161:-78;bmr=10*wkg+6.25*cm-5*(b.age||35)+sex}let factor={low:1.35,moderate:1.5,high:1.65}[b.activity]||1.5,tdee=Math.max(1200,bmr*factor),delta={fat_loss:-400,recomp:-150,muscle_gain:200,maintain:0}[b.goal]??-150,avg=b.goal==='fat_loss'?Math.max(1400,tdee*.8,tdee+delta):Math.max(1400,tdee+delta);avg=Math.round(avg/50)*50;let protein=Math.round(Math.max(100,Math.min(b.weight||180,(b.weight||180)*.9))/5)*5,fat=Math.round(Math.max(50,(b.weight||180)*.3)/5)*5;return{bmr:Math.round(bmr),tdee:Math.round(tdee),averageCalories:avg,gymCalories:avg+75,recoveryCalories:Math.max(1200,avg-75),protein,fat,fiber:30}}
 function availability(a){let w=a.work,t=a.training,b=a.basics,out=[];for(let d=0;d<7;d++){let blocks=[],jobs=0,bed=m(b.bedtime)||1380,wake=(bed+b.sleepHours*60)%1440;addBlock(blocks,bed,bed+b.sleepHours*60,'Sleep');if(w.primaryDays.includes(d)&&w.primaryStart&&w.primaryEnd){jobs++;let s=m(w.primaryStart),e=m(w.primaryEnd);if(e<=s)e+=1440;addBlock(blocks,s-w.primaryCommute,e+w.primaryCommute,'Primary work + commute')}if(w.secondaryEnabled&&w.secondaryDays.includes(d)&&w.secondaryStart&&w.secondaryEnd){jobs++;let s=m(w.secondaryStart),e=m(w.secondaryEnd);if(e<=s)e+=1440;addBlock(blocks,s-w.secondaryCommute,e+w.secondaryCommute,'Secondary work + commute')}for(const c of w.commitments.filter(x=>x.day===d)){let s=m(c.start),e=m(c.end);if(e<=s)e+=1440;addBlock(blocks,s,e,c.label)}let windows=freeWindows(blocks,t.duration+15).filter(x=>x.end-x.start>=t.duration+15),best=null;for(const x of windows){let mid=(x.start+x.end)/2,score=(jobs===0?12:jobs===1?6:-2)+Math.min(4,(x.end-x.start-t.duration)/30);if(t.preferred==='morning'&&mid<720)score+=5;if(t.preferred==='afternoon'&&mid>=720&&mid<1020)score+=5;if(t.preferred==='evening'&&mid>=1020)score+=5;if(t.preferred==='flexible')score+=2;let start=clamp(x.start+Math.min(15,Math.max(0,(x.end-x.start-t.duration)/2)),x.start,x.end-t.duration);if(!best||score>best.score)best={day:d,start:Math.round(start/5)*5,end:Math.round((start+t.duration)/5)*5,score,jobs,window:x}}out.push({day:d,jobs,blocks,windows,best})}return out}
 function chooseTraining(a,av){let ranked=av.filter(x=>x.best).map(x=>({...x.best,day:x.day})).sort((x,y)=>y.score-x.score),picked=[];for(const c of ranked){if(picked.length>=a.training.days)break;if(picked.every(p=>{let gap=Math.abs(p.day-c.day);gap=Math.min(gap,7-gap);return gap>1}))picked.push(c)}for(const c of ranked){if(picked.length>=a.training.days)break;if(!picked.some(p=>p.day===c.day))picked.push(c)}return picked.sort((x,y)=>x.day-y.day)}
 function dateForWeekday(base,day,week=0){let d=date(base),delta=(day-d.getDay()+7)%7;d.setDate(d.getDate()+delta+week*7);return dkey(d)}
 function buildPlan(a){let av=availability(a),workouts=chooseTraining(a,av),nut=metabolic(a),familiar=[...a.nutrition.foods,...a.nutrition.cuisines].slice(0,12);return{version:18,createdAt:new Date().toISOString(),availability:av.map(x=>({day:x.day,jobs:x.jobs,free:x.windows.map(w=>({start:tm(w.start),end:tm(w.end)})),best:x.best?{start:tm(x.best.start),end:tm(x.best.end),score:x.best.score}:null})),training:{daysPerWeek:a.training.days,duration:a.training.duration,experience:a.training.experience,equipment:a.training.equipment,preferred:a.training.preferred,limitations:a.training.limitations,days:workouts.map((x,i)=>({weekday:x.day,dayName:DAY_LONG[x.day],start:tm(x.start),end:tm(x.end),workout:WORKOUTS[i%WORKOUTS.length]?.name||`Workout ${i+1}`,reason:x.jobs===0?'Best recovery window on a work-free day':x.jobs===1?'Fits around one work shift and commute':'Available around your commitments'}))},nutrition:{...nut,goal:a.basics.goal,goalWeight:a.basics.goalWeight||null,goalBodyFat:a.basics.goalBodyFat||null,familiarFoods:familiar,restrictions:a.nutrition.restrictions,meals:a.nutrition.meals,budget:a.nutrition.budget,cooking:a.nutrition.cook,sampleIdeas:familiar.length?Array.from({length:Math.min(a.nutrition.meals,familiar.length)},(_,i)=>`Meal ${i+1}: build around ${familiar[i]} + a protein source + produce/fiber`):['Choose familiar staple foods, then pair each meal with a protein source and fruit/vegetables.']}}}
 function saveRecurringSecondary(a){if(!a.work.secondaryEnabled)return;let now=new Date();for(let off=0;off<3;off++){let d=new Date(now.getFullYear(),now.getMonth()+off,1),ym=ymk(d),days=daysInMonth(ym),map={};for(let n=1;n<=days;n++){let k=`${ym}-${String(n).padStart(2,'0')}`;map[n]=a.work.secondaryDays.includes(date(k).getDay())?'X':'D'}jset(K.bellevue+ym,map)}}
 function applyPlan(a,p){let old=profile(),pr=old?structuredClone(old):(typeof genericProfileTemplate==='function'?genericProfileTemplate():blankProfile()),anchor=monOf(dkey()),pattern=[1,2,3,4,5,6,0].map(day=>a.work.primaryDays.includes(day)?1:0);pr.name=a.basics.name||pr.name||'User';pr.sleepTarget=a.basics.sleepHours;pr.heightIn=a.basics.heightFt*12+a.basics.heightIn;pr.trainingDaysPerWeek=a.training.days;pr.singleJobTraining=true;pr.equipmentMode=a.training.equipment;pr.fixed={enabled:a.work.primaryDays.length>0,name:a.work.primaryName,anchor,pattern,start:a.work.primaryStart,end:a.work.primaryEnd,commuteMin:a.work.primaryCommute};pr.variable={enabled:a.work.secondaryEnabled,name:a.work.secondaryName,start:a.work.secondaryStart,end:a.work.secondaryEnd,commuteMin:a.work.secondaryCommute};saveProfileObj(pr);saveRecurringSecondary(a);let n=nutrition();n={...n,gymCal:p.nutrition.gymCalories,restCal:p.nutrition.recoveryCalories,protein:p.nutrition.protein,fat:p.nutrition.fat,fiber:p.nutrition.fiber,goalWeight:a.basics.goalWeight||n.goalWeight||0,goalBf:a.basics.goalBodyFat||n.goalBf||0,planStart:dkey()};saveNutritionObj(n);let o=overrides();for(let wk=0;wk<4;wk++)for(const x of p.training.days){let k=dateForWeekday(dkey(),x.weekday,wk);o[k]={action:'train',createdAt:new Date().toISOString(),source:'onboarding-v18'}}saveOverrides(o);jset(ONBOARD_KEY,{answers:a,plan:p,updatedAt:new Date().toISOString()});renderAll();A.queueSync?.()}
 function dayChecks(name,selected=[1,2,3,4,5]){return `<div class="obDays">${DAYS.map((d,i)=>`<label><input type="checkbox" name="${name}" value="${i}" ${selected.includes(i)?'checked':''}><span>${d}</span></label>`).join('')}</div>`}
 function modal(){if($('#onboardingV18'))return;document.body.insertAdjacentHTML('beforeend',`<div id="onboardingV18" class="modal" role="dialog" aria-modal="true" aria-labelledby="obTitle"><div class="sheet largeSheet onboardingSheet"><div class="sheetHandle"></div><div class="sheetHead"><div><small id="obStepLabel">Step 1 of 5</small><h2 id="obTitle">Build your plan</h2></div><button id="obClose">Later</button></div><div class="obProgress"><i id="obProgressFill"></i></div><div id="obBody"></div><p id="obStatus" class="statusText"></p><div class="sheetActions"><button id="obBack">Back</button><button id="obNext" class="primary">Continue</button></div></div></div>`);$('#obClose').onclick=()=>{preserve();closeModal('onboardingV18')};$('#obBack').onclick=()=>{preserve();step=Math.max(0,step-1);render()};$('#obNext').onclick=next;$('#onboardingV18').addEventListener('click',e=>{if(e.target.id==='onboardingV18'){preserve();closeModal('onboardingV18')}})}
 const screens=[
  ()=>`<div class="obIntro"><span class="obHero">✨</span><h3>Tell us about you and your goal</h3><p>We use this to estimate training volume and nutrition targets. You can change everything later.</p></div><div class="formGrid"><label class="span2">Name<input id="obName" autocomplete="name" value="${esc(profile()?.name||'')}"></label><label>Age<input id="obAge" type="number" min="16" max="100"></label><label>Calorie equation setting<select id="obSex"><option value="neutral">Neutral estimate</option><option value="male">Male</option><option value="female">Female</option></select></label><label>Height ft<input id="obHeightFt" type="number" min="3" max="8"></label><label>Height in<input id="obHeightIn" type="number" min="0" max="11.9" step="0.1"></label><label>Current weight (lb)<input id="obWeight" type="number" min="70" max="600" step="0.1"></label><label>Body fat % (optional)<input id="obBodyFat" type="number" min="3" max="60" step="0.1"></label><label>Goal<select id="obGoal"><option value="recomp">Body recomposition</option><option value="fat_loss">Lose body fat</option><option value="muscle_gain">Build muscle</option><option value="maintain">Maintain</option></select></label><label>Goal weight (optional)<input id="obGoalWeight" type="number" step="0.1"></label><label>Goal body fat % (optional)<input id="obGoalBf" type="number" step="0.1"></label><label>Daily activity<select id="obActivity"><option value="low">Mostly seated</option><option value="moderate" selected>Moderately active</option><option value="high">Very active</option></select></label></div>`,
  ()=>`<div class="obIntro"><span class="obHero">🗓️</span><h3>When are you working?</h3><p>We block work and commute before choosing gym windows.</p></div><label>Primary job name<input id="obJob1Name" value="${esc(profile()?.fixed?.name||'Work')}"></label><h4>Primary work days</h4>${dayChecks('obJob1Day')}<div class="formGrid"><label>Shift start<input id="obJob1Start" type="time" value="${esc(profile()?.fixed?.start||'09:00')}"></label><label>Shift end<input id="obJob1End" type="time" value="${esc(profile()?.fixed?.end||'17:00')}"></label><label>Commute each way (min)<input id="obJob1Commute" type="number" value="${profile()?.fixed?.commuteMin??30}"></label><label>Sleep target (hours)<input id="obSleepHours" type="number" step="0.5" value="${profile()?.sleepTarget||7.5}"></label><label>Typical bedtime<input id="obBedtime" type="time" value="23:00"></label></div><label class="check"><input id="obJob2Enabled" type="checkbox" ${profile()?.variable?.enabled?'checked':''}> I also have a second / variable job</label><div id="obJob2Box"><label>Second job name<input id="obJob2Name" value="${esc(profile()?.variable?.name||'Second job')}"></label><h4>Second-job days if they usually repeat</h4>${dayChecks('obJob2Day',[])}<div class="formGrid"><label>Shift start<input id="obJob2Start" type="time" value="${esc(profile()?.variable?.start||'')}"></label><label>Shift end<input id="obJob2End" type="time" value="${esc(profile()?.variable?.end||'')}"></label><label>Commute each way (min)<input id="obJob2Commute" type="number" value="${profile()?.variable?.commuteMin??30}"></label></div></div>`,
  ()=>`<div class="obIntro"><span class="obHero">⏱️</span><h3>What else needs to fit?</h3><p>Add recurring classes, family time, outings, church, appointments or anything that makes a time unavailable.</p></div><label>Recurring commitments<textarea id="obCommitments" rows="7" placeholder="Tue 18:00-20:00 class&#10;Fri 19:00-23:00 outing&#10;Sun 09:00-12:00 church"></textarea></label><p class="muted">Use one line per recurring block: <b>Day start-end label</b>. Example: Sat 18:00-22:00 family.</p>`,
  ()=>`<div class="obIntro"><span class="obHero">🏋️</span><h3>How do you want to train?</h3><p>We will choose the best available days, then use your workout rotation and equipment alternatives.</p></div><div class="formGrid"><label>Training days / week<select id="obTrainingDays"><option>2</option><option selected>3</option><option>4</option></select></label><label>Session length<select id="obDuration"><option>30</option><option>45</option><option selected>60</option><option>75</option><option>90</option></select></label><label>Experience<select id="obExperience"><option value="beginner">Beginner</option><option value="intermediate" selected>Intermediate</option><option value="advanced">Advanced</option></select></label><label>Equipment<select id="obEquipment"><option value="full">Full commercial gym</option><option value="basic">Basic gym</option><option value="home">Home / minimal</option></select></label><label>Preferred time<select id="obPreferred"><option value="flexible">Flexible</option><option value="morning">Morning</option><option value="afternoon">Afternoon</option><option value="evening">Evening</option></select></label><label class="span2">Injuries, limitations or movements to avoid<textarea id="obLimitations" rows="3" placeholder="Optional"></textarea></label></div>`,
  ()=>`<div class="obIntro"><span class="obHero">🥘</span><h3>What foods feel normal to you?</h3><p>Your suggested nutrition plan should look like food you would actually eat.</p></div><div class="formGrid"><label class="span2">Foods you already like / eat<input id="obFoods" placeholder="eggs, oats, jollof rice, chicken, salmon, plantain, Greek yogurt"></label><label class="span2">Cuisines you know and enjoy<input id="obCuisines" placeholder="Ghanaian, West African, Caribbean, Mediterranean"></label><label class="span2">Restrictions / allergies / foods you avoid<textarea id="obRestrictions" rows="2"></textarea></label><label>Meals per day<select id="obMeals"><option>2</option><option selected>3</option><option>4</option><option>5</option></select></label><label>Food budget<select id="obBudget"><option value="low">Budget-conscious</option><option value="moderate" selected>Moderate</option><option value="flexible">Flexible</option></select></label><label>Cooking time<select id="obCook"><option value="low">Very little</option><option value="moderate" selected>Some cooking</option><option value="high">I enjoy cooking</option></select></label></div>`
 ];
 function preserve(){draft=draft&&draft.version===1?draft:{version:1,values:{},checks:{}};let controls=$$('#obBody input,#obBody select,#obBody textarea'),names=new Set;for(const e of controls){if(e.type==='checkbox'){if(e.id)draft.checks[e.id]=e.checked;if(e.name)names.add(e.name)}else if(e.id)draft.values[e.id]=e.value}for(const name of names)draft.checks[name]=controls.filter(e=>e.name===name&&e.checked).map(e=>e.value);try{sessionStorage.setItem(DRAFT_KEY,JSON.stringify(draft))}catch{}return draft}
 function restoreDraft(){if(!draft)try{let saved=JSON.parse(sessionStorage.getItem(DRAFT_KEY)||'null');if(saved?.version===1&&saved.values&&saved.checks)draft=saved}catch{}if(!draft)return;for(const[id,value]of Object.entries(draft.values)){let e=$('#'+id);if(e)e.value=value}for(const[id,value]of Object.entries(draft.checks)){let e=$('#'+id);if(e&&e.type==='checkbox')e.checked=!!value;for(const box of $$(`[name="${id}"]`))box.checked=Array.isArray(value)&&value.includes(box.value)}}
 function clearDraft(){draft=null;try{sessionStorage.removeItem(DRAFT_KEY)}catch{}}
 function render(){modal();$('#obStepLabel').textContent=`Step ${step+1} of ${screens.length}`;$('#obProgressFill').style.width=`${(step+1)/screens.length*100}%`;$('#obBody').innerHTML=screens[step]();restoreDraft();$('#obStatus').textContent='';$('#obBack').classList.remove('hidden');$('#obBack').disabled=step===0;$('#obNext').onclick=next;$('#obNext').textContent=step===screens.length-1?'Build my plan':'Continue';if(step===1){let cb=$('#obJob2Enabled'),box=$('#obJob2Box');let f=()=>box.classList.toggle('hidden',!cb.checked);cb.onchange=f;f()}}
 async function next(){preserve();if(step<screens.length-1){step++;render();return}let a=answers();if(!a.basics.name||!a.basics.weight||!a.basics.heightFt)return $('#obStatus').textContent='Add your name, height and weight so the plan can be calculated.';$('#obNext').disabled=true;$('#obStatus').textContent='Finding realistic workout windows and building your plan…';try{let p=buildPlan(a);if(A.session&&A.config?.aiConfigured){try{let j=await A.authedFetch('onboarding',{method:'POST',body:JSON.stringify({answers:a,deterministicPlan:p})});if(j.plan)p=j.plan}catch(e){recordDiagnostic?.('ai-onboarding',e)}}lastPlan=p;showPlan(a,p)}catch(e){$('#obStatus').textContent=e.message}finally{$('#obNext').disabled=false}}
 function showPlan(a,p){let tp=p.training||{},np=p.nutrition||{},ai=p.ai||{};$('#obBody').innerHTML=`<div class="obIntro"><span class="obHero">✅</span><h3>Your starting plan is ready</h3><p>${esc(ai.summary||'Built around your work, commute, sleep, commitments, equipment and goal.')}</p></div><div class="obPlanCard"><h4>Best workout windows</h4>${(tp.days||[]).map(x=>`<div class="obPlanRow"><div><b>${esc(x.dayName)} · ${esc(x.workout)}</b><small>${esc(x.reason||'')}</small></div><strong>${esc(x.start)}–${esc(x.end)}</strong></div>`).join('')||'<p>No reliable workout windows were found. Adjust work, commitments or session length.</p>'}</div><div class="obPlanCard"><h4>Nutrition starting targets</h4><div class="obTargetGrid"><span><b>${Math.round(np.gymCalories||0)}</b><small>gym kcal</small></span><span><b>${Math.round(np.recoveryCalories||0)}</b><small>rest kcal</small></span><span><b>${Math.round(np.protein||0)}g</b><small>protein</small></span><span><b>${Math.round(np.fiber||0)}g</b><small>fiber</small></span></div><p>${esc(ai.nutrition?.rationale||`Starting estimate: maintenance about ${np.tdee||'—'} kcal/day. Targets should be adjusted from real weight trend and adherence.`)}</p>${ai.nutrition?.sampleDay?.length?`<div class="sampleMeals">${ai.nutrition.sampleDay.map(x=>`<div><b>${esc(x.meal)}</b><span>${esc((x.foods||[]).join(' · '))}</span><small>${esc(x.note||'')}</small></div>`).join('')}</div>`:`<p><b>Familiar-food ideas:</b> ${esc((np.sampleIdeas||[]).join(' • '))}</p>`}</div><p class="muted">This is a starting plan, not medical care. The app will refine calories and training from your actual logs.</p>`;$('#obStepLabel').textContent='Plan preview';$('#obProgressFill').style.width='100%';$('#obBack').classList.add('hidden');$('#obNext').textContent='Use this plan';$('#obNext').onclick=()=>{applyPlan(a,p);clearDraft();closeModal('onboardingV18');toast('Personalized plan applied');A.pushState?.({quiet:true}).catch(()=>{})};$('#obStatus').textContent='' }
 A.openOnboarding=function(){if(A.config?.cloudConfigured&&!A.session){$('#accountStatus')&&( $('#accountStatus').textContent='Create an account or sign in first, then onboarding will save your plan to your account.');renderAccountUI?.();openModal('accountDialog');return}step=0;modal();render();openModal('onboardingV18')};A.buildDeterministicPlan=buildPlan;A.onboardingAnswers=answers;
 function install(){modal();let cards=$('#page-more .menuCards');if(cards&&!$('#openOnboardingV18')){let b=document.createElement('button');b.id='openOnboardingV18';b.innerHTML='<span>✨</span><div><b>Personalized plan</b><small>Work, commute, commitments, workouts & familiar foods</small></div><i>›</i>';cards.insertBefore(b,cards.firstChild);b.onclick=A.openOnboarding}setTimeout(()=>{if(!profile()&&!$('.modal.open')&&(!A.config?.cloudConfigured||A.session))A.openOnboarding()},350)}
 install();document.addEventListener('DOMContentLoaded',()=>setTimeout(install,100));
})(window.WGC18);
(function(){let st=document.createElement('style');st.textContent=`.onboardingSheet{max-width:720px}.obProgress{height:5px;background:var(--line);border-radius:999px;overflow:hidden;margin-bottom:14px}.obProgress i{display:block;height:100%;background:#3b82f6;transition:width .25s}.obIntro{text-align:center;margin:3px 0 16px}.obHero{font-size:30px}.obIntro h3{margin:7px 0 4px}.obIntro p{font-size:10px;color:var(--muted);margin:0 auto;max-width:480px}.obDays{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin:7px 0 12px}.obDays label{position:relative}.obDays input{position:absolute;opacity:0}.obDays span{display:grid;place-items:center;padding:9px 3px;border:1px solid var(--line);border-radius:9px;font-size:9px;font-weight:800}.obDays input:checked+span{background:#2563eb;color:white;border-color:#2563eb}.obPlanCard{border:1px solid var(--line);background:var(--card);border-radius:13px;padding:12px;margin:9px 0}.obPlanCard h4{margin:0 0 8px}.obPlanRow{display:flex;justify-content:space-between;gap:10px;padding:8px 0;border-top:1px solid var(--line)}.obPlanRow:first-of-type{border-top:0}.obPlanRow b,.obPlanRow small{display:block}.obPlanRow small{color:var(--muted);font-size:8px;margin-top:2px}.obPlanRow strong{font-size:10px;color:#60a5fa;white-space:nowrap}.obTargetGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.obTargetGrid span{background:var(--chip);padding:9px;border-radius:9px;text-align:center}.obTargetGrid b,.obTargetGrid small{display:block}.obTargetGrid small{font-size:8px;color:var(--muted)}.sampleMeals{display:grid;gap:6px}.sampleMeals>div{background:var(--chip);border-radius:9px;padding:8px}.sampleMeals b,.sampleMeals span,.sampleMeals small{display:block}.sampleMeals span{font-size:9px;margin:3px 0}.sampleMeals small{font-size:8px;color:var(--muted)}@media(max-width:480px){.obDays{grid-template-columns:repeat(4,1fr)}.obTargetGrid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(st)})();
