// v16 DOM additions. Runs during document parsing before DOMContentLoaded.
(function setupV16Shell(){
 const cal=document.getElementById('page-calendar');
 if(cal&&!document.getElementById('todayDashboard')){
   const wrap=document.createElement('div');wrap.innerHTML='<div id="todayDashboard"></div><div id="healthSummary" class="healthSummary card"></div>';
   cal.insertBefore(wrap.firstElementChild,cal.firstChild);cal.insertBefore(wrap.firstElementChild,cal.children[1]||null);
 }
 const cards=document.querySelector('#page-more .menuCards');
 if(cards&&!cards.querySelector('[data-open="health"]')){
   const backup=cards.querySelector('[data-open="backup"]');
   const box=document.createElement('div');box.innerHTML=`<button data-open="health"><span>❤️</span><div><b>Health & recovery</b><small>Apple Health import, sleep, steps, resting HR</small></div><i>›</i></button><button data-open="reminders"><span>🔔</span><div><b>Reminders & Calendar</b><small>Workout alerts and iOS Calendar export</small></div><i>›</i></button><button data-open="cloud"><span>☁️</span><div><b>Private cloud sync</b><small>Encrypted WebDAV / Nextcloud sync</small></div><i>›</i></button>`;
   [...box.children].forEach(x=>cards.insertBefore(x,backup));
 }
 const modalHTML=`
 <div id="healthDialog" class="modal" role="dialog" aria-modal="true" aria-labelledby="healthTitle"><div class="sheet"><div class="sheetHandle"></div><div class="sheetHead"><h2 id="healthTitle">Health & recovery</h2><button data-close="healthDialog">Done</button></div>
  <div class="card noMargin"><h3>Apple Health import</h3><p>Export your Health data on iPhone, unzip it in Files, then choose <b>export.xml</b>. The file is parsed locally on this device.</p><label class="captureBtn">Choose Apple Health export.xml<input id="healthXml" type="file" accept="text/xml,.xml"></label><p id="healthImportStatus" class="statusText"></p></div>
  <div class="card"><h3>CSV import</h3><p>CSV columns can include date, weight, steps, sleep, and resting HR.</p><label class="captureBtn">Choose health CSV<input id="healthCsv" type="file" accept="text/csv,.csv"></label></div>
  <div class="card"><h3>Today / manual recovery</h3><div class="formGrid"><label>Date<input id="healthDate" type="date"></label><label>Sleep (hours)<input id="healthSleep" type="number" step="0.1"></label><label>Steps<input id="healthSteps" type="number" step="1"></label><label>Resting HR<input id="healthRhr" type="number" step="1"></label></div><button id="saveHealthManual" class="primary wideBtn">Save recovery data</button></div></div></div>
 <div id="remindersDialog" class="modal" role="dialog" aria-modal="true" aria-labelledby="remindersTitle"><div class="sheet"><div class="sheetHandle"></div><div class="sheetHead"><h2 id="remindersTitle">Reminders & Calendar</h2><button data-close="remindersDialog">Done</button></div><div id="reminderSettings" class="card noMargin"></div></div></div>
 <div id="cloudDialog" class="modal" role="dialog" aria-modal="true" aria-labelledby="cloudTitle"><div class="sheet"><div class="sheetHandle"></div><div class="sheetHead"><h2 id="cloudTitle">Private cloud sync</h2><button data-close="cloudDialog">Done</button></div><div class="introBox"><b>End-to-end encrypted sync for a WebDAV-compatible private cloud.</b><p>Works with services such as Nextcloud/ownCloud when the server allows browser CORS. The planner encrypts the backup before upload. This is optional.</p></div><div class="formGrid"><label class="span2">Full HTTPS WebDAV file URL<input id="cloudUrl" placeholder="https://cloud.example.com/remote.php/dav/files/user/work-gym.wgp.json"></label><label>Username<input id="cloudUser" autocomplete="username"></label><label>Password / app token<input id="cloudPassword" type="password" autocomplete="current-password"></label><label class="span2">Encryption passphrase<input id="cloudPassphrase" type="password" autocomplete="new-password" placeholder="Required on every device"></label></div><label class="check"><input id="cloudAuto" type="checkbox"> Auto-upload when this app goes into the background during the current session</label><div class="twoButtons"><button id="cloudPull">Pull from cloud</button><button id="cloudPush" class="primary">Push to cloud</button></div><p id="cloudStatus" class="statusText"></p></div></div>`;
 if(!document.getElementById('healthDialog'))document.body.insertAdjacentHTML('beforeend',modalHTML);
 const old=document.getElementById('backupDialog');if(old){old.outerHTML=`<div id="backupDialog" class="modal" role="dialog" aria-modal="true" aria-labelledby="backupTitle"><div class="sheet"><div class="sheetHandle"></div><div class="sheetHead"><h2 id="backupTitle">Data & backup</h2><button data-close="backupDialog">Done</button></div><div class="card noMargin"><h3>Secure backup</h3><p>Create an AES-256 encrypted backup. On iPhone, Share can save it directly to iCloud Drive or another private Files location.</p><input id="backupPass" class="fullInput" type="password" placeholder="Backup passphrase (6+ characters)"><div class="twoButtons"><button id="exportEncrypted" class="primary">Encrypted download</button><button id="shareEncrypted">Share / save to Files</button></div><p id="backupStatus" class="statusText"></p></div><div class="card"><h3>Plain backup</h3><button id="exportData" class="wideBtn">Export plain JSON</button></div><div class="card"><h3>Restore / migrate</h3><label class="captureBtn">Choose backup file<input id="importFile" type="file" accept="application/json,.json"></label><p id="importStatus" class="statusText"></p><button id="restoreSnapshot" class="wideBtn">Restore last automatic local snapshot</button></div><div class="card"><h3>Diagnostics</h3><button id="exportDiagnostics" class="wideBtn">Export diagnostics</button></div><div class="card dangerZone"><h3>Delete local data</h3><input id="deleteConfirm" class="fullInput" placeholder="Type DELETE"><button id="deleteAllData" class="danger wideBtn">Delete all planner data</button></div></div></div>`}
 const about=document.querySelector('#aboutDialog .card');if(about)about.innerHTML='<p><b>Version:</b> 16.0.0</p><p>v16 combines work schedule, completed training, load/reps/RIR, nutrition adherence, weight trend and optional Health imports into adaptive coaching.</p><p>Apple Health files are parsed locally. Direct HealthKit access is not available to Safari/PWA apps. Background iPhone reminders require push infrastructure, so v16 also provides iOS Calendar export.</p>';
})();
