const CACHE='wgp-v30.1.31-readiness62';
const SHELL=['./','./index.html','./manifest.webmanifest','./v16.css','./base-patch.js','./workout-plan.js','./nutrition-core.js','./food-portions-v50.js','./health.js','./coach.js','./today.js','./calendar.js','./training-a.js','./training-b.js','./diary-a.js','./diary-b.js','./progress.js','./schedule.js','./data.js','./cloud.js','./notifications.js','./pwa-patch.js','./shell.js','./init.js','./icons/icon-180.png','./icons/icon.svg','../work-gym-planner-v15/base.css','../work-gym-planner-v15/training.css','../work-gym-planner-v15/responsive.css','../work-gym-planner-v15/base.js','../work-gym-planner-v15/work-model.js','../work-gym-planner-v15/profile.js','../work-gym-planner-v15/nutrition-ui.js','../work-gym-planner-v15/ui.js','../work-gym-planner-v15/pwa.js','../work-gym-planner-v16/vendor/pdfjs/pdf.min.mjs','../work-gym-planner-v16/vendor/pdfjs/pdf.worker.min.mjs','../work-gym-planner-v16/vendor/tesseract/tesseract.min.js','../work-gym-planner-v16/vendor/tesseract/worker.min.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-lstm.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-lstm.wasm','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-simd-lstm.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-simd-lstm.wasm','../work-gym-planner-v16/vendor/html5-qrcode/html5-qrcode.min.js'];
SHELL.push('../shared/v31-roster.js','./icons/brand-mark.svg','./premium-v18.css','./landing-v29.css','./home-v27.css','./nutrition-v27.css','./adaptive-planner-v24.css','./schedule-platform-v25.css','./app-v29.css','./app-v30.css','./calendar-premium-v42.css','./health-consent-v35.js','./landing-v29.js','./app-v29.js','./app-v30.js','./calendar-premium-v42.js');
SHELL.push('../shared/usage-counts-v45.js');
SHELL.push('./roster-scan-v48.js','./roster-scan-v48.css');
SHELL.push('../shared/work-pay-v58.js','../work-gym-planner-v16/work-pay-v58.js','../work-gym-planner-v16/work-pay-v58.css');
const OPTIONAL_SHELL=SHELL.filter(url=>url.includes('/vendor/'));
const REQUIRED_SHELL=SHELL.filter(url=>!OPTIONAL_SHELL.includes(url));
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(async c=>{
 await c.addAll(REQUIRED_SHELL);
}).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
function navigationSafeResponse(response){return response?.redirected&&response.ok?new Response(response.body,{status:response.status,statusText:response.statusText,headers:response.headers}):response}
function isAuthCallback(url){return ['auth','code','token_hash','access_token','refresh_token','error','error_code','error_description'].some(key=>url.searchParams.has(key))}
async function cacheMatch(request){const cache=await caches.open(CACHE);return navigationSafeResponse((await cache.match(request))||(await cache.match(request,{ignoreSearch:true})))}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin||u.pathname.startsWith('/api/')||e.request.headers.has('Authorization'))return;if(isAuthCallback(u))return;e.respondWith((async()=>{const cached=await cacheMatch(e.request);if(cached)return cached;try{const r=navigationSafeResponse(await fetch(e.request));if(r.ok){const copy=r.clone();await caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{})}return r}catch(error){if(e.request.mode==='navigate'){const shell=await cacheMatch('./index.html');if(shell)return shell}throw error}})())});
