const CACHE='wgp-v30.1.24-public';
const SHELL=['./','./index.html','./manifest.webmanifest','./v16.css','./base-patch.js','./workout-plan.js','./nutrition-core.js','./health.js','./coach.js','./today.js','./calendar.js','./training-a.js','./training-b.js','./diary-a.js','./diary-b.js','./progress.js','./schedule.js','./data.js','./cloud.js','./notifications.js','./pwa-patch.js','./shell.js','./init.js','./icons/icon-180.png','./icons/icon.svg','../work-gym-planner-v15/base.css','../work-gym-planner-v15/training.css','../work-gym-planner-v15/responsive.css','../work-gym-planner-v15/base.js','../work-gym-planner-v15/work-model.js','../work-gym-planner-v15/profile.js','../work-gym-planner-v15/nutrition-ui.js','../work-gym-planner-v15/ui.js','../work-gym-planner-v15/pwa.js','../work-gym-planner-v16/vendor/pdfjs/pdf.min.mjs','../work-gym-planner-v16/vendor/pdfjs/pdf.worker.min.mjs','../work-gym-planner-v16/vendor/tesseract/tesseract.min.js','../work-gym-planner-v16/vendor/tesseract/worker.min.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-lstm.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-lstm.wasm','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-simd-lstm.js','../work-gym-planner-v16/vendor/tesseract-core/tesseract-core-simd-lstm.wasm','../work-gym-planner-v16/vendor/html5-qrcode/html5-qrcode.min.js'];
SHELL.push('../shared/v31-roster.js','./icons/brand-mark.svg','./premium-v18.css','./landing-v29.css','./home-v27.css','./nutrition-v27.css','./adaptive-planner-v24.css','./schedule-platform-v25.css','./app-v29.css','./app-v30.css','./landing-v29.js','./app-v29.js','./app-v30.js');
const OPTIONAL_SHELL=SHELL.filter(url=>url.includes('/vendor/'));
const REQUIRED_SHELL=SHELL.filter(url=>!OPTIONAL_SHELL.includes(url));
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(async c=>{
 await c.addAll(REQUIRED_SHELL);
 await Promise.allSettled(OPTIONAL_SHELL.map(url=>c.add(url)));
}).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url);if(u.origin!==location.origin||u.pathname.startsWith('/api/')||e.request.headers.has('Authorization'))return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){let q=r.clone();caches.open(CACHE).then(c=>c.put(e.request,q)).catch(()=>{})}return r}).catch(()=>caches.match(e.request).then(r=>r||(e.request.mode==='navigate'?caches.match('./index.html'):undefined))))});
