// v16.3 Interactive Home dashboard ------------------------------------------
const HOME_ICONS={
 menu:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',
 brand:'<svg viewBox="0 0 24 24"><path d="M4 7v10m3-12v14m3-7h4m0-7v14m3-12v10m3-7v4M7 12h10"/><path d="m8 18 3-3 2 2 4-5"/></svg>',
 work:'<svg viewBox="0 0 24 24"><path d="M9 6V4.8A1.8 1.8 0 0 1 10.8 3h2.4A1.8 1.8 0 0 1 15 4.8V6M4 7h16v12H4zM4 11h16M10 11v2h4v-2"/></svg>',
 training:'<svg viewBox="0 0 24 24"><path d="M3 9v6m3-8v10m3-5h6m0-5v10m3-8v6m3-4v2M6 12h12"/></svg>',
 fire:'<svg viewBox="0 0 24 24"><path d="M13.5 3.5c.6 3-2.4 4.2-1.2 7.1.7 1.6 2.6 1.9 3.2.2.4-1.2-.1-2.4-.6-3.2 3.5 2 5 5.1 4 8.4-1 3.5-4.1 5.5-7.2 5.5-4.5 0-7.3-2.9-6.7-6.8.5-3.4 3.2-5 5.4-7.6.8-.9 1.7-2.1 1.7-3.6.7.4 1 .7 1.4 1Z"/></svg>',
 target:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><path d="M12 2v3m10 7h-3M12 22v-3M2 12h3"/></svg>',
 bed:'<svg viewBox="0 0 24 24"><path d="M3 19v-8m18 8v-5a2 2 0 0 0-2-2H9a3 3 0 0 0-3 3v4M3 17h18M6 12V8h5a2 2 0 0 1 2 2v2"/></svg>',
 steps:'<svg viewBox="0 0 24 24"><path d="M8 4c1.4 0 2.4 1.1 2.2 2.4L9.7 10c-.2 1.2-.9 2.1-2 2.6L5.3 14c-1.4.8-3.2-.1-3.3-1.7-.1-1 .5-1.9 1.4-2.3l1.4-.7.8-3.1C6 4.9 6.8 4 8 4Zm8.2 7c1.4 0 2.4 1.1 2.2 2.4l-.5 3.6c-.2 1.2-.9 2.1-2 2.6L13.5 21c-1.4.8-3.2-.1-3.3-1.7-.1-1 .5-1.9 1.4-2.3l1.4-.7.8-3.1c.4-1.3 1.2-2.2 2.4-2.2Z"/></svg>',
 heart:'<svg viewBox="0 0 24 24"><path d="M12 20s-8-4.8-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 9c0 6.2-8 11-8 11Z"/></svg>',
 bolt:'<svg viewBox="0 0 24 24"><path d="m13.5 2-7 11h5l-1 9 7-12h-5z"/></svg>',
 apple:'<svg viewBox="0 0 24 24"><path d="M12 7c1.6-2.5 4.8-2.6 6.5-.7 1.7 1.9 1.6 5.1.5 7.7-1.7 4.1-4.1 7-6.2 7-1.1 0-1.7-.7-2.8-.7S8.2 21 7.1 21C5 21 2.7 18.1 1 14c-1.1-2.6-1.2-5.8.5-7.7C3.2 4.4 6.4 4.5 8 7c1.2-.7 2.8-.7 4 0Zm.2-2.2c.2-2 1.7-3.6 3.6-3.8.1 2-1.3 3.8-3.6 3.8Z"/></svg>',
 scale:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M8 9a5 5 0 0 1 8 0l-4 3zM12 12v4"/></svg>',
 body:'<svg viewBox="0 0 24 24"><circle cx="12" cy="4.5" r="2.2"/><path d="M8 10c1.2-1.4 2.5-2.1 4-2.1s2.8.7 4 2.1l1.5 4-2.3 1-.7-2.1V21h-5v-8.1L8.8 15l-2.3-1z"/></svg>',
 barcode:'<svg viewBox="0 0 24 24"><path d="M4 5v14M7 5v14m3-14v14m4-14v14m3-14v14m3-14v14M2 3v4m0 10v4m20-18v4m0 10v4"/></svg>',
 chevron:'<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>'
};
function nextPlannedWorkout(after=dkey()){let dates=canonicalScheduleThrough(addDays(after,35)).filter(k=>k>=after);for(const k of dates){if(completedOn(k))continue;return{k,wi:projectedWorkoutIndex(k)}}return null}
function homeGreeting(){let h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':'Good evening'}
function homeTime(t){if(!t)return'';let [h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM',hh=h%12||12;return`${hh}:${String(m||0).padStart(2,'0')} ${ap}`}
function shiftText(on,start,end){return on&&start&&end?`${homeTime(start)} – ${homeTime(end)}`:on?'Working':'Off'}
function readinessColor(score){return score>=80?'#34d058':score>=65?'#5bd66f':score>=50?'#f6b73c':'#ff6b6b'}
function workLoadLabel(s){return s.kind==='both'?'High Load':s.kind==='one'?'Work Day':s.kind==='unknown'?'Needs Review':'Recovery Opportunity'}
function todayTrainingInfo(k){let comp=completedOn(k),scheduled=isScheduled(k),wi=comp?.workoutIndex??(scheduled?projectedWorkoutIndex(k):null),next=nextPlannedWorkout(addDays(k,wi!=null?1:0));if(wi!=null)return{title:WORKOUTS[wi].name,sub:comp?'Completed':`Week ${phaseInfo(k).week} · ${phaseInfo(k).name}`,date:k,wi,completed:!!comp};if(next)return{title:'Recovery Day',sub:`Next: ${WORKOUTS[next.wi].name}`,date:next.k,wi:next.wi,next:true};return{title:'Recovery Day',sub:'No workout scheduled',date:null,wi:null}}
function dashboardWorkRows(k,s){let p=profile(),rows=[];if(p?.variable?.enabled){let code=variableCode(k),on=code==='X';rows.push({name:p.variable.name||'Variable job',value:code==='?'?'Schedule unknown':shiftText(on,p.variable.start,p.variable.end),state:code==='?'?'unknown':on?'work':'off'})}if(p?.fixed?.enabled){let on=fixedWork(k);rows.push({name:p.fixed.name||'Fixed job',value:shiftText(on,p.fixed.start,p.fixed.end),state:on?'work':'off'})}return rows}
function renderTodayDashboard(){
 let root=$('#todayDashboard');if(!root||!profile())return;let k=dkey(),p=profile(),s=workState(k),r=recoveryReadiness(k),n=target(k),t=totals(k),training=todayTrainingInfo(k),calPct=clamp(Math.round(t.cal/Math.max(1,n.cal)*100),0,100),proteinPct=clamp(Math.round(t.p/Math.max(1,n.p)*100),0,100),carbPct=clamp(Math.round(t.c/Math.max(1,n.c)*100),0,100),fatPct=clamp(Math.round(t.f/Math.max(1,n.f)*100),0,100),left=Math.max(0,Math.round(n.cal-t.cal)),pLeft=Math.max(0,Math.round(n.p-t.p)),color=readinessColor(r.score),rows=dashboardWorkRows(k,s),initial=(p.name||'U').trim().charAt(0).toUpperCase();
 let recoveryMsg=r.score>=80?'Recovery looks strong. You can follow the planned training prescription.':r.score>=65?'Recovery is good. Train as planned and respect the prescribed RIR.':r.score>=50?'Recovery is moderate. Keep the session controlled and avoid unnecessary failure work.':'Recovery is low. Consider moving heavy training or using the fatigue-adjusted prescription.';
 root.innerHTML=`<div class="homeDash">
  <header class="homeHeader"><button class="homeBrand" id="homeMenuBtn" aria-label="Open menu"><span class="brandMark">${HOME_ICONS.brand}</span><span class="brandCopy"><b>WORK / GYM</b><small>COACH</small></span></button><div class="homeHello"><h1>${esc(homeGreeting())}, ${esc(p.name||'there')}</h1><p>${fmt(k,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p></div><button class="homeAvatar" id="homeProfileBtn" aria-label="Open profile">${esc(initial)}</button></header>
  <div class="homeSummaryGrid">
   <button class="homeSummary workCard" id="homeWorkCard"><span class="homeIcon green">${HOME_ICONS.work}</span><small>Work Today</small><b>${esc(s.kind==='both'?'Both Jobs':s.kind==='one'?workText(k):s.kind==='unknown'?'Review Schedule':'Off Both')}</b><em>${esc(workLoadLabel(s))}</em></button>
   <button class="homeSummary trainingCard" id="homeTrainingCard"><span class="homeIcon blue">${HOME_ICONS.training}</span><small>Training</small><b>${esc(training.title)}</b><em>${esc(training.sub)}</em></button>
   <button class="homeSummary calorieCard" id="homeCaloriesCard"><span class="homeIcon orange">${HOME_ICONS.fire}</span><small>Calories</small><b>${Math.round(t.cal).toLocaleString()} / ${n.cal.toLocaleString()}</b><em>${left.toLocaleString()} left</em></button>
   <button class="homeSummary proteinCard" id="homeProteinCard"><span class="homeIcon purple">${HOME_ICONS.target}</span><small>Protein</small><b>${Math.round(t.p)} / ${n.p}g</b><em>${pLeft}g left</em></button>
  </div>
  <button class="homePanel readinessPanel" id="homeRecoveryCard" style="--ready:${r.score*3.6}deg;--readyColor:${color}"><div class="homeRing"><div><b>${r.score}%</b><small>${esc(r.band)}</small></div></div><div class="readinessBody"><div class="homePanelHead"><div><h2>Recovery Readiness</h2><p>${esc(recoveryMsg)}</p></div>${HOME_ICONS.chevron}</div><div class="recoveryMetrics"><span><i class="metricIcon green">${HOME_ICONS.bed}</i><b>${r.sleep?r.sleep.toFixed(1)+'h':'—'}</b><small>Sleep</small></span><span><i class="metricIcon blue">${HOME_ICONS.steps}</i><b>${r.steps?Math.round(r.steps).toLocaleString():'—'}</b><small>Steps</small></span><span><i class="metricIcon red">${HOME_ICONS.heart}</i><b>${r.rhr?Math.round(r.rhr):'—'}</b><small>RHR</small></span><span><i class="metricIcon yellow">${HOME_ICONS.bolt}</i><b>${esc(r.band)}</b><small>Recovery</small></span></div></div></button>
  <section class="homePanel planPanel"><div class="homePanelHead"><h2>Today's Plan</h2><button id="homeFullPlan">View Full Plan ${HOME_ICONS.chevron}</button></div><div class="homePlanGrid"><div class="workPlan"><h3>${HOME_ICONS.work} Work Schedule</h3>${rows.map(x=>`<div class="homePlanRow"><span>${esc(x.name)}</span><b class="${x.state}">${esc(x.value)}</b></div>`).join('')||'<div class="homePlanRow"><span>Work</span><b class="off">Off</b></div>'}<div class="loadTag ${s.kind}">${s.kind==='both'?'High Workload Day':s.kind==='unknown'?'Schedule Needs Review':s.kind==='off'?'Full Recovery Day':'Single-Job Day'}</div></div><div class="trainingPlan"><h3>${HOME_ICONS.training} Training</h3><b class="planWorkout">${esc(training.title)}</b><p>${training.title==='Recovery Day'?'Focus on mobility, steps, nutrition and good sleep.':training.completed?'Workout logged. Recovery and nutrition now drive the next recommendation.':'Follow the adaptive set, rep and RIR targets for today.'}</p><button id="homeNextWorkout">${training.title==='Recovery Day'?'View Next Workout':'Open Workout'} ${HOME_ICONS.chevron}</button></div></div></section>
  <section class="homePanel nutritionPanel"><h2>Nutrition Progress</h2><div class="homeNutritionGrid"><div class="nutritionRing" style="--nutrition:${calPct*3.6}deg"><div><b>${calPct}%</b><small>Calories</small></div></div><div class="homeMacros"><div class="homeMacro"><label><span><i class="macroIcon orange">${HOME_ICONS.fire}</i>Calories</span><b>${Math.round(t.cal).toLocaleString()} / ${n.cal.toLocaleString()} kcal</b></label><div><i class="greenFill" style="width:${calPct}%"></i></div></div><div class="homeMacro"><label><span><i class="macroIcon green">${HOME_ICONS.training}</i>Protein</span><b>${Math.round(t.p)} / ${n.p} g</b></label><div><i class="greenFill" style="width:${proteinPct}%"></i></div></div><div class="homeMacro"><label><span><i class="macroIcon blue">${HOME_ICONS.apple}</i>Carbs</span><b>${Math.round(t.c)} / ${Math.round(n.c)} g</b></label><div><i class="blueFill" style="width:${carbPct}%"></i></div></div><div class="homeMacro"><label><span><i class="macroIcon yellow">${HOME_ICONS.target}</i>Fat</span><b>${Math.round(t.f)} / ${Math.round(n.f)} g</b></label><div><i class="orangeFill" style="width:${fatPct}%"></i></div></div><button class="homeAddFood" id="homeAddFood">Add Food <span>＋</span></button></div></div></section>
  <section class="homePanel quickPanel"><h2>Quick Actions</h2><div class="quickGrid"><button id="quickWorkout"><i class="green">${HOME_ICONS.training}</i><span>Log Workout</span></button><button id="quickFood"><i class="green">${HOME_ICONS.apple}</i><span>Add Food</span></button><button id="quickWeight"><i class="purple">${HOME_ICONS.scale}</i><span>Weigh In</span></button><button id="quickBody"><i class="blue">${HOME_ICONS.body}</i><span>Body Stats</span></button><button id="quickBarcode"><i class="orange">${HOME_ICONS.barcode}</i><span>Scan Barcode</span></button></div></section>
 </div>`;
 $('#homeMenuBtn').onclick=()=>page('more');$('#homeProfileBtn').onclick=()=>{fillProfileForm();openModal('profileDialog')};$('#homeWorkCard').onclick=()=>page('calendar');$('#homeCaloriesCard').onclick=$('#homeProteinCard').onclick=()=>page('diary');$('#homeTrainingCard').onclick=()=>training.date?openTrainingDate(training.date):page('training');$('#homeRecoveryCard').onclick=()=>{fillHealthForm?.();openModal('healthDialog')};$('#homeFullPlan').onclick=()=>page('calendar');$('#homeNextWorkout').onclick=()=>training.date?openTrainingDate(training.date):page('training');
 const addFood=()=>{page('diary');setTimeout(()=>openFood('Breakfast'),80)};$('#homeAddFood').onclick=addFood;$('#quickFood').onclick=addFood;$('#quickBarcode').onclick=()=>{page('diary');setTimeout(()=>{openFood('Breakfast');foodTab('scan')},80)};$('#quickWorkout').onclick=()=>training.date?openTrainingDate(training.date):page('training');$('#quickWeight').onclick=()=>{page('progress');setTimeout(()=>$('#checkWeight')?.focus(),120)};$('#quickBody').onclick=()=>{page('progress');setTimeout(()=>$('#checkWaist')?.focus(),120)};
}
