// Training ------------------------------------------------------------------
function trainingDatesAround(){let today=dkey(),start=addDays(today,-90),end=addDays(today,120),a=canonicalScheduleThrough(end).filter(x=>x>=start&&x<=end),h=workoutHistory().filter(x=>x.date>=start&&x.date<=end).map(x=>x.date),o=Object.entries(overrides()).filter(([,v])=>v.action==='train').map(([k])=>k);return [...new Set([...a,...h,...o])].sort()}
function initialTrainingDate(){let today=dkey(),dates=trainingDatesAround();if(completedOn(today)||dates.includes(today))return today;return dates.find(k=>k>today)||today}
function prevTraining(k){let a=trainingDatesAround().filter(x=>x<k);return a[a.length-1]||k}function nextTraining(k){return trainingDatesAround().find(x=>x>k)||k}
function openTrainingDate(k){trainingDate=k;page('training');renderTraining()}
function sessionDraft(k,wi){let ds=drafts();if(ds[k]&&ds[k].workoutIndex===wi)return ds[k];let done=completedOn(k);if(done)return structuredClone(done);let w=WORKOUTS[wi];let ex=w.ex.map(meta=>{let last=exposures(meta.name,k)[0],guess=last?.sets?.find(s=>+s.w)?.w||'',count=typeof prescribedSets==='function'?prescribedSets(meta,k):meta.sets;return{name:meta.name,sets:Array.from({length:count},()=>({w:guess,r:'',rir:''}))}});return{id:uid('session'),date:k,workoutIndex:wi,completed:false,phase:typeof phaseInfo==='function'?phaseInfo(k):null,exercises:ex}}
function exposures(name,before='9999-12-31'){return workoutHistory().filter(s=>s.completed&&s.date<before).sort((a,b)=>b.date.localeCompare(a.date)).map(s=>({session:s,ex:(s.exercises||[]).find(e=>e.name===name)})).filter(x=>x.ex)}
function e1rm(ex){return Math.max(0,...(ex?.sets||[]).map(s=>(+s.w||0)*(1+(+s.r||0)/30)))}
function sessionVolume(s){return(s.exercises||[]).reduce((sum,e)=>sum+(e.sets||[]).reduce((a,z)=>a+(+z.w||0)*(+z.r||0),0),0)}
function avgRIR(ex){let a=(ex.sets||[]).filter(s=>s.rir!==''&&s.rir!=null&&!Number.isNaN(+s.rir));return a.length?a.reduce((z,s)=>z+(+s.rir),0)/a.length:null}
function exerciseAdvice(meta,current,before){let sets=(current?.sets||[]).filter(s=>+s.r>0),min=sets.length?Math.min(...sets.map(s=>+s.r)):0,avgr=sets.length?sets.reduce((a,s)=>a+(+s.r),0)/sets.length:0,rir=avgRIR(current),maxW=Math.max(0,...sets.map(s=>+s.w||0)),prev=exposures(meta.name,before),p1=prev[0]?.ex,p2=prev[1]?.ex;
 let expected=(current?.sets||[]).length||meta.sets;if(sets.length<expected)return `Complete all ${expected} prescribed working sets before increasing load.`;
 let curE=e1rm(current),p1e=e1rm(p1),p2e=e1rm(p2);
 if(p1&&p2&&curE>0&&p1e>0&&p2e>0&&curE<p1e*.96&&p1e<p2e*.97&&(rir==null||rir<=1))return 'Fatigue flag: performance has declined across 3 distinct exposures. Reduce load 5–10% or remove one set next time, then rebuild.';
 if(rir!=null&&rir<.75)return 'Effort was too close to failure overall. Hold the load next time and aim for about 1–2 RIR on compounds.';
 if(min>=meta.hi&&(rir==null||rir>=1)){if(meta.inc>0)return `Progress: add ${meta.inc} lb next time and restart near ${meta.lo} reps.`;return 'Progress by making the movement harder or adding reps with clean form.'}
 if(min>=meta.lo)return `Keep ${maxW||'the same'}${maxW?' lb':''} and add about 1 rep where possible until every set reaches ${meta.hi}.`;
 return `Repeat or reduce the load 5–10% until every set reaches at least ${meta.lo} reps with controlled form.`}
function collectTrainingInputs(k,wi){let s=sessionDraft(k,wi),w=WORKOUTS[wi];s.exercises=w.ex.map((meta,ei)=>{let count=s.exercises[ei]?.sets?.length||meta.sets;return{name:meta.name,sets:Array.from({length:count},(_,si)=>({w:$(`[data-e="${ei}"][data-s="${si}"][data-f="w"]`)?.value||'',r:$(`[data-e="${ei}"][data-s="${si}"][data-f="r"]`)?.value||'',rir:$(`[data-e="${ei}"][data-s="${si}"][data-f="rir"]`)?.value||''}))}});return s}
function saveTrainingDraft(){if(!trainingDate)return;let wi=completedOn(trainingDate)?.workoutIndex??projectedWorkoutIndex(trainingDate),s=collectTrainingInputs(trainingDate,wi),d=drafts();d[trainingDate]=s;saveDrafts(d)}
function completeTraining(){let wi=completedOn(trainingDate)?.workoutIndex??projectedWorkoutIndex(trainingDate),s=collectTrainingInputs(trainingDate,wi),performed=s.exercises.some(ex=>ex.sets.some(set=>+set.r>0));if(!performed){toast('Log at least one completed set before finishing the workout');return}s.completed=true;s.completedAt=new Date().toISOString();s.phase=typeof phaseInfo==='function'?phaseInfo(trainingDate):null;s.readiness=typeof recoveryReadiness==='function'?recoveryReadiness(trainingDate):null;let h=workoutHistory().filter(x=>x.date!==trainingDate);h.push(s);saveHistory(h.sort((a,b)=>a.date.localeCompare(b.date)));let d=drafts();delete d[trainingDate];saveDrafts(d);freezePastSnapshots();toast('Workout saved + analyzed');renderAll();renderTraining()}
function trainingAdherence(){freezePastSnapshots();let s=snapshots(),today=dkey(),start=addDays(today,-27),planned=Object.keys(s).filter(k=>k>=start&&k<=today&&s[k].planned),done=workoutHistory().filter(x=>x.completed&&x.date>=start&&x.date<=today);return{planned:planned.length,done:done.length,rate:planned.length?Math.round(done.length/planned.length*100):0}}
function weeklyTrainingStats(){let h=workoutHistory().filter(x=>x.completed),weeks=[];for(let w=5;w>=0;w--){let end=addDays(dkey(),-w*7),start=addDays(end,-6),ss=h.filter(x=>x.date>=start&&x.date<=end),vol=ss.reduce((a,s)=>a+sessionVolume(s),0),hard=ss.reduce((a,s)=>a+(s.exercises||[]).reduce((q,e)=>q+(e.sets||[]).filter(z=>+z.r>0&&(z.rir===''||+z.rir<=3)).length,0),0);weeks.push({label:fmt(end,{month:'short',day:'numeric'}),vol,hard})}return weeks}
