// v18 exercise library. Demonstration URLs intentionally point to searches/reference pages;
// do not copy third-party video assets into the commercial app without a license.
const V18_EXERCISES=[
 ['Barbell Back Squat','Legs','Barbell','Quads, glutes','Brace, sit between the hips, keep the whole foot planted, drive up through mid-foot.','Knees collapsing inward; heels lifting; losing trunk brace.','barbell back squat exercise demonstration'],
 ['Hack Squat','Legs','Hack squat machine','Quads, glutes','Set shoulders/back firmly on pads, feet where knees track comfortably, lower under control, drive through whole foot.','Hips lifting from pad; bouncing at bottom; locking knees aggressively.','hack squat machine exercise demonstration'],
 ['Leg Press','Legs','Leg press','Quads, glutes','Set seat so pelvis stays down, lower sled until comfortable depth, press without snapping knees locked.','Lower back rounding; shallow uncontrolled reps; knees caving.','leg press exercise demonstration'],
 ['Romanian Deadlift','Legs','Barbell or dumbbells','Hamstrings, glutes','Soft knees, push hips back, keep load close, stop when hamstrings limit further hip hinge.','Turning it into a squat; rounding low back; load drifting forward.','romanian deadlift exercise demonstration'],
 ['Leg Curl','Legs','Leg curl machine','Hamstrings','Align knee with machine pivot, keep hips against pad, curl smoothly and control the return.','Hips lifting; using momentum; shortening the eccentric.','leg curl machine exercise demonstration'],
 ['Leg Extension','Legs','Leg extension machine','Quadriceps','Align knee with pivot, pad above ankle, extend smoothly, pause, lower under control.','Kicking with momentum; poor pivot alignment; excessive load.','leg extension machine exercise demonstration'],
 ['Standing Calf Raise','Legs','Calf raise','Calves','Use full comfortable stretch, rise onto balls of feet, pause at top, lower slowly.','Bouncing; tiny range; rolling ankles outward.','standing calf raise exercise demonstration'],
 ['Flat Barbell Bench Press','Chest','Barbell bench','Chest, triceps, front delts','Eyes under bar, shoulder blades set, feet planted, lower to lower-mid chest, press up and slightly back.','Elbows excessively flared; shoulders rolling forward; bouncing bar.','barbell bench press exercise demonstration'],
 ['Incline Dumbbell Press','Chest','Dumbbells + bench','Upper chest, triceps','Use a moderate incline, shoulder blades set, lower dumbbells beside upper chest, press without clanking.','Bench too steep; losing shoulder position; excessive range.','incline dumbbell press exercise demonstration'],
 ['Machine Chest Press','Chest','Chest press machine','Chest, triceps','Adjust seat so handles align around mid-chest, keep back supported, press and return under control.','Seat too high/low; shrugging; weight stack slamming.','machine chest press exercise demonstration'],
 ['Cable Fly','Chest','Cable station','Chest','Soft elbows, ribs controlled, bring arms together in an arc, return until chest is comfortably stretched.','Turning into a press; over-stretching shoulders; swinging.','cable fly exercise demonstration'],
 ['Lat Pulldown','Back','Cable pulldown','Lats, upper back, biceps','Set thigh pad, slight lean, pull elbows toward ribs/hips, control bar overhead.','Pulling behind neck; excessive swinging; shrugging.','lat pulldown exercise demonstration'],
 ['Seated Cable Row','Back','Cable row','Mid-back, lats','Sit tall, brace, drive elbows back without overextending spine, control reach forward.','Rocking torso; shrugging; jerking the stack.','seated cable row exercise demonstration'],
 ['Chest-Supported Row','Back','Machine or incline bench','Upper back, lats','Keep chest supported, pull elbows toward hips/ribs, pause, lower fully under control.','Lifting chest; shrugging; shortening range.','chest supported row exercise demonstration'],
 ['Pull-Up','Back','Pull-up bar','Lats, upper back, biceps','Start controlled, pull chest toward bar by driving elbows down, lower to a comfortable full hang.','Kipping unintentionally; craning neck; dropping from top.','pull up exercise demonstration'],
 ['Dumbbell Shoulder Press','Shoulders','Dumbbells','Delts, triceps','Brace torso, start dumbbells near shoulder level, press overhead without excessive back arch.','Overarching low back; flared unstable wrists; bouncing.','dumbbell shoulder press exercise demonstration'],
 ['Cable Lateral Raise','Shoulders','Cable station','Side delts','Lead with elbow, raise arm to roughly shoulder level, keep traps relaxed, lower slowly.','Shrugging; swinging; internally rotating aggressively.','cable lateral raise exercise demonstration'],
 ['Face Pull','Shoulders','Cable rope','Rear delts, upper back','Pull rope toward forehead with elbows high enough for comfortable external rotation, squeeze upper back.','Too much load; leaning far back; pulling to chest.','face pull exercise demonstration'],
 ['Cable Triceps Pressdown','Arms','Cable station','Triceps','Pin upper arms near sides, extend elbows fully under control, return without shoulders rolling forward.','Elbows drifting; torso swinging; partial reps.','triceps pressdown exercise demonstration'],
 ['Dumbbell Curl','Arms','Dumbbells','Biceps','Keep upper arm mostly still, curl without swinging, squeeze, lower slowly.','Hip drive; elbows racing forward; dropping eccentric.','dumbbell biceps curl exercise demonstration'],
 ['Cable Curl','Arms','Cable station','Biceps','Stand braced, keep elbows stable, curl through comfortable range and control return.','Shoulder swing; wrists collapsing; stack slamming.','cable curl exercise demonstration'],
 ['Plank','Core','Bodyweight','Abs, trunk','Stack shoulders, squeeze glutes, keep ribs/pelvis controlled and breathe behind the brace.','Hips sagging; hips too high; holding breath.','plank exercise demonstration'],
 ['Cable Crunch','Core','Cable station','Abs','Flex trunk by bringing ribs toward pelvis while hips stay relatively fixed, return slowly.','Turning into hip hinge; pulling with arms; excessive load.','cable crunch exercise demonstration'],
 ['Hip Thrust','Glutes','Barbell or machine','Glutes','Upper back supported, chin tucked, drive hips up until torso is level, squeeze glutes without hyperextending back.','Overarching; feet too far/close; bouncing.','hip thrust exercise demonstration']
].map((x,i)=>({id:'ex'+(i+1),name:x[0],category:x[1],equipment:x[2],muscles:x[3],how:x[4],mistakes:x[5],videoQuery:x[6]}));
function v18VideoUrl(e){return 'https://www.youtube.com/results?search_query='+encodeURIComponent(e.videoQuery)}
function v18RenderLibrary(){let q=($('#v18LibrarySearch')?.value||'').toLowerCase(),cat=$('#v18LibraryCategory')?.value||'',a=V18_EXERCISES.filter(e=>(!q||[e.name,e.category,e.equipment,e.muscles].join(' ').toLowerCase().includes(q))&&(!cat||e.category===cat));$('#v18LibraryList').innerHTML=a.map(e=>`<article class="v18Exercise"><div><b>${esc(e.name)}</b><small>${esc(e.category)} · ${esc(e.equipment)} · ${esc(e.muscles)}</small></div><button data-v18ex="${e.id}">Guide</button></article>`).join('')||'<p class="muted">No matching movements.</p>';$$('[data-v18ex]').forEach(b=>b.onclick=()=>v18OpenExercise(b.dataset.v18ex))}
function v18OpenExercise(id){let e=V18_EXERCISES.find(x=>x.id===id);if(!e)return;$('#v18ExerciseDetail').innerHTML=`<h2>${esc(e.name)}</h2><p><b>Equipment:</b> ${esc(e.equipment)}<br><b>Primary muscles:</b> ${esc(e.muscles)}</p><h3>How to perform it</h3><p>${esc(e.how)}</p><h3>Common mistakes</h3><p>${esc(e.mistakes)}</p><a class="v18VideoBtn" target="_blank" rel="noopener noreferrer" href="${v18VideoUrl(e)}">Watch demonstration videos ↗</a>`;openModal('v18ExerciseDialog')}
