// Work + Gym Coach v18: accounts, AI onboarding, schedule fitting, library and coach.
var V18={config:null,session:null,user:null,threadId:null,plan:null};
const V18_SESSION=PREFIX+'auth-v18',V18_ONBOARD=PREFIX+'onboarding-v18';
function v18Api(path){let base=(window.WGC_API_BASE||'').replace(/\/$/,'');return base+'/api/v18/'+path}
async function v18JSON(url,opt={}){let r=await fetch(url,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
async function v18Config(){if(V18.config)return V18.config;try{V18.config=await v18JSON(v18Api('config'))}catch{V18.config={cloudConfigured:false,aiConfigured:false}}return V18.config}
function v18Session(){if(V18.session)return V18.session;V18.session=jget(V18_SESSION,null);return V18.session}
function v18AuthHeaders(){let s=v18Session();return s?.access_token?{Authorization:'Bearer '+s.access_token}:{}}
function v18SaveSession(s){V18.session=s||null;if(s)jset(V18_SESSION,s);else localStorage.removeItem(V18_SESSION);v18RenderAccount()}
async function v18Refresh(){let s=v18Session(),c=await v18Config();if(!s?.refresh_token||!c.cloudConfigured)return null;let j=await v18JSON(`${c.supabaseUrl}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:c.supabaseAnonKey},body:JSON.stringify({refresh_token:s.refresh_token})});v18SaveSession(j);return j}
async function v18Authed(path,opt={}){let go=()=>v18JSON(v18Api(path),{...opt,headers:{...v18AuthHeaders(),...(opt.headers||{})}});try{return await go()}catch(e){if(/expired|sign in/i.test(e.message)&&v18Session()?.refresh_token){await v18Refresh();return go()}throw e}}
async function v18Auth(mode,email,password){let c=await v18Config();if(!c.cloudConfigured)throw Error('Accounts are being connected to the cloud backend. Try again after the owner finishes cloud setup.');let endpoint=mode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password',body={email,password};let j=await v18JSON(c.supabaseUrl+endpoint,{method:'POST',headers:{apikey:c.supabaseAnonKey},body:JSON.stringify(body)});if(mode==='signup'&&!j.access_token)return{needsEmail:true};v18SaveSession(j);V18.user=j.user||null;await v18PullAccount(false);return j}
function v18SignOut(){v18SaveSession(null);V18.user=null;toast('Signed out')}
function v18StorageSnapshot(){let storage={};for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k&&k.startsWith(PREFIX)&&k!==V18_SESSION)storage[k]=localStorage.getItem(k)}return{schemaVersion:18,exportedAt:new Date().toISOString(),storage}}
function v18RestoreSnapshot(state){let storage=state?.storage||{};for(const[k,v]of Object.entries(storage))if(k.startsWith(PREFIX)&&k!==V18_SESSION)localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));renderAll();fillProfileForm?.()}
async function v18Migrate(){if(!v18Session())throw Error('Sign in first.');let snap=v18StorageSnapshot();await v18Authed('state',{method:'PUT',body:JSON.stringify({state:snap})});toast('This device is now saved to your account');v18RenderAccount()}
async function v18PullAccount(ask=true){if(!v18Session())throw Error('Sign in first.');let j=await v18Authed('state');if(!j.state)return null;if(ask&&!confirm('Replace this device’s Work + Gym Coach data with the data saved in your account?'))return null;v18RestoreSnapshot(j.state);toast('Account data restored');return j.state}
async function v18DeleteAccount(){if(!v18Session())throw Error('Sign in first.');if(!confirm('Permanently delete your Work + Gym Coach account and cloud data? This cannot be undone.'))return;await v18Authed('account',{method:'DELETE'});v18SignOut();toast('Account deleted')}
function minutes(t){let[a,b]=String(t||'00:00').split(':').map(Number);return(a||0)*60+(b||0)}
function timeText(m){m=(m+1440)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function v18WindowScore(w){let hour=w.start/60,s=w.duration>=75?12:w.duration>=55?9:6;if(hour>=9&&hour<=19)s+=3;if(hour<6||hour>22)s-=5;return s}
function v18FreeWindowsForDay(day,a){let sleep=+a.sleepHours||7.5,need=+a.workoutMinutes||60,buffer=+a.commuteMinutes||0,blocks=[];let ds=a.daySchedules?.[day]||{};if(ds.workStart&&ds.workEnd){let st=minutes(ds.workStart),en=minutes(ds.workEnd);if(en<=st)en+=1440;blocks.push([st-buffer,en+buffer])}for(const b of(ds.commitments||[])){let st=minutes(b.start),en=minutes(b.end);if(en<=st)en+=1440;blocks.push([st,en])}let bed=minutes(a.bedTime||'23:00'),wake=minutes(a.wakeTime||'07:00');if(wake<bed){blocks.push([0,wake],[bed,1440])}else blocks.push([bed,wake]);blocks.sort((x,y)=>x[0]-y[0]);let merged=[];for(const b of blocks){let last=merged.at(-1);if(last&&b[0]<=last[1])last[1]=Math.max(last[1],b[1]);else merged.push([...b])}let cur=0,w=[];for(const b of [...merged,[1440,1440]]){if(b[0]-cur>=need)w.push({day,start:cur,end:b[0],duration:b[0]-cur});cur=Math.max(cur,b[1])}return w.filter(x=>x.start>=wake&&x.end<=bed).sort((x,y)=>v18WindowScore(y)-v18WindowScore(x))}
function v18EstimateCalories(a){let kg=+a.weightKg||(+a.weightLb||170)*.453592,cm=+a.heightCm||(+a.heightIn||68)*2.54,age=+a.age||30,sex=a.sex==='female'?'female':'male',bmr=sex==='female'?10*kg+6.25*cm-5*age-161:10*kg+6.25*cm-5*age+5,factor={low:1.35,moderate:1.5,high:1.65}[a.activity]||1.45,tdee=Math.round(bmr*factor),goal=a.goal||'recomp',delta=goal==='lose'?-Math.min(500,Math.round(tdee*.18)):goal==='gain'?Math.min(300,Math.round(tdee*.10)):goal==='recomp'?-Math.min(250,Math.round(tdee*.08)):0,cal=Math.max(sex==='female'?1300:1500,tdee+delta),protein=Math.round(kg*(goal==='gain'||goal==='recomp'?1.8:1.6)),fat=Math.round(Math.max(45,kg*.7)),carbs=Math.max(0,Math.round((cal-protein*4-fat*9)/4));return{calories:Math.round(cal/10)*10,protein,fat,carbs,fiber:Math.max(25,Math.round(cal/1000*14)),tdeeEstimate:tdee}}
function v18BuildPlan(a){let days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],windows=days.flatMap(d=>v18FreeWindowsForDay(d,a).slice(0,2)).sort((x,y)=>v18WindowScore(y)-v18WindowScore(x)),want=clamp(+a.trainingDays||3,2,4),chosen=[];for(const w of windows){let di=days.indexOf(w.day);if(chosen.some(x=>Math.abs(days.indexOf(x.day)-di)<=1))continue;chosen.push(w);if(chosen.length===want)break}for(const w of windows){if(chosen.length===want)break;if(!chosen.some(x=>x.day===w.day))chosen.push(w)}chosen.sort((x,y)=>days.indexOf(x.day)-days.indexOf(y.day));let split=want===2?['Full Body A','Full Body B']:want===3?['Upper','Lower','Full Body']:['Upper A','Lower A','Upper B','Lower B'];let nutrition=v18EstimateCalories(a);return{availability:chosen.map((w,i)=>({...w,startText:timeText(w.start),endText:timeText(w.start+(+a.workoutMinutes||60)),workout:split[i]||`Workout ${i+1}`})),nutrition,foods:String(a.familiarFoods||'').split(',').map(x=>x.trim()).filter(Boolean),generatedAt:new Date().toISOString()}}
async function v18SubmitOnboarding(){let f=$('#v18OnboardForm'),fd=new FormData(f),a=Object.fromEntries(fd.entries());a.trainingDays=+a.trainingDays;a.workoutMinutes=+a.workoutMinutes;a.commuteMinutes=+a.commuteMinutes;a.age=+a.age;a.weightLb=+a.weightLb;a.heightIn=+a.heightIn;a.daySchedules={};for(const d of ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']){let on=fd.get('work'+d)==='on';a.daySchedules[d]={workStart:on?fd.get('start'+d):'',workEnd:on?fd.get('end'+d):'',commitments:[]}}let base=v18BuildPlan(a);jset(V18_ONBOARD,a);V18.plan=base;v18ShowPlan(base);if(v18Session()){try{let j=await v18Authed('onboarding',{method:'POST',body:JSON.stringify({answers:a,deterministicPlan:base})});V18.plan=j.plan;v18ShowPlan(j.plan)}catch(e){toast('Base plan saved locally; AI refinement unavailable')}}}
function v18ShowPlan(p){let el=$('#v18PlanPreview');if(!el)return;let n=p?.nutrition||{},slots=p?.availability||[],ai=p?.ai||{};el.innerHTML=`<div class="v18PlanCard"><h3>Your suggested week</h3>${slots.map(x=>`<p><b>${esc(x.day)} · ${esc(x.workout)}</b><br>${esc(x.startText)}–${esc(x.endText)} · ${Math.round(x.duration)} min free window</p>`).join('')||'<p>Add more schedule details so I can find training windows.</p>'}<h3>Nutrition starting target</h3><p><b>${Math.round(n.calories||0)} kcal · ${Math.round(n.protein||0)} g protein</b><br>${Math.round(n.carbs||0)} g carbs · ${Math.round(n.fat||0)} g fat · ${Math.round(n.fiber||0)} g fiber</p>${ai.summary?`<h3>Coach summary</h3><p>${esc(ai.summary)}</p>`:''}${ai.nutrition?.sampleDay?'<h3>Familiar-food sample</h3>'+ai.nutrition.sampleDay.map(m=>`<p><b>${esc(m.meal)}</b><br>${(m.foods||[]).map(esc).join(' · ')}</p>`).join(''):''}</div>`}
async function v18CoachAsk(mode='coach'){let input=$('#v18CoachInput'),msg=input?.value.trim()||'',file=$('#v18EquipmentPhoto')?.files?.[0],imageDataUrl=null;if(file)imageDataUrl=await new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});if(!msg&&!imageDataUrl)return;if(!v18Session())return toast('Sign in to use the AI coach');let log=$('#v18ChatLog');log.insertAdjacentHTML('beforeend',`<div class="v18Msg user">${esc(msg||'Equipment photo')}</div><div class="v18Msg ai pending">Thinking…</div>`);input.value='';try{let j=await v18Authed('coach',{method:'POST',body:JSON.stringify({message:msg,mode:imageDataUrl?'equipment':mode,imageDataUrl,threadId:V18.threadId})});V18.threadId=j.threadId;log.querySelector('.pending:last-of-type')?.remove();log.insertAdjacentHTML('beforeend',`<div class="v18Msg ai">${esc(j.answer).replace(/\n/g,'<br>')}</div>`);if($('#v18EquipmentPhoto'))$('#v18EquipmentPhoto').value=''}catch(e){log.querySelector('.pending:last-of-type')?.remove();toast(e.message)}log.scrollTop=log.scrollHeight}
function v18RenderAccount(){let s=v18Session(),box=$('#v18AccountState');if(!box)return;if(s)box.innerHTML=`<p><b>Signed in</b><br>${esc(s.user?.email||'Your account')}</p><div class="twoButtons"><button id="v18Migrate">Save this device to account</button><button id="v18Pull">Restore from account</button></div><button id="v18SignOut" class="wideBtn">Sign out</button><button id="v18DeleteAccount" class="danger wideBtn">Delete account</button>`;else box.innerHTML='<p>Sign in to sync your plan and history across devices and use the AI coach.</p>';$('#v18Migrate')?.addEventListener('click',()=>v18Migrate().catch(e=>toast(e.message)));$('#v18Pull')?.addEventListener('click',()=>v18PullAccount(true).catch(e=>toast(e.message)));$('#v18SignOut')?.addEventListener('click',v18SignOut);$('#v18DeleteAccount')?.addEventListener('click',()=>v18DeleteAccount().catch(e=>toast(e.message)))}
