const $=id=>document.getElementById(id),DAY=864e5,MEALS=['Breakfast','Lunch','Dinner','Snacks'];
const NYU0=new Date('2026-08-17T12:00:00'),BEL={
'2026-08':{1:'D',2:'D',3:'X',4:'X',5:'X',6:'X',7:'X',8:'D',9:'D',10:'X',11:'D',12:'X',13:'X',14:'X',15:'X',16:'X',17:'X',18:'D',19:'X',20:'X',21:'X',22:'D',23:'D',24:'X',25:'X',26:'D',27:'X',28:'X',29:'X',30:'X',31:'X'},
'2026-09':{1:'X',2:'X',3:'X',4:'X',5:'D',6:'X',7:'H',8:'D',9:'X',10:'X',11:'X',12:'D',13:'D',14:'X',15:'X',16:'X',17:'X',18:'D',19:'X',20:'X',21:'X',22:'X',23:'D',24:'X',25:'X',26:'X',27:'D',28:'D',29:'X',30:'X'}};
const WK=[
['Lower A','Quad-focused heavy day',[['Hack Squat','4×6–8'],['Romanian Deadlift','3×6–8'],['Leg Press','3×10–12'],['Seated Leg Curl','3×10–12'],['Leg Extension','2×12–15'],['Standing Calf Raise','3×10–15'],['Cable Crunch','3×12–15']]],
['Upper A','Chest + back heavy',[['Incline Dumbbell Press','4×6–8'],['Chest-Supported Row','4×6–8'],['Lat Pulldown','3×8–10'],['Machine Chest Press','3×8–10'],['Cable Lateral Raise','3×12–20'],['Rope Pressdown','3×10–15'],['Preacher Curl','3×10–15']]],
['Lower B','Glutes + hamstrings',[['Smith Machine Squat','3×8–10'],['Hip Thrust','3×8–10'],['Bulgarian Split Squat','3×8–10/leg'],['Lying Leg Curl','3×10–12'],['Leg Extension','2×12–15'],['Seated Calf Raise','3×12–15'],['Hanging Knee Raise','3×10–15']]],
['Upper B','Shoulders + back + arms',[['Flat Bench/Machine Press','3×6–8'],['Neutral-Grip Lat Pulldown','3×8–10'],['DB Shoulder Press','3×8–10'],['Seated Cable Row','3×8–12'],['Incline Cable Fly','2×12–15'],['Lateral Raise','4×12–20'],['Incline DB Curl','3×10–12'],['Overhead Cable Triceps','3×10–12']]]];
function dkey(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function ymk(y,m){return`${y}-${String(m+1).padStart(2,'0')}`}
function date(k){return new Date(k+'T12:00:00')}
function nyu(k){let n=Math.round((date(k)-NYU0)/DAY),c=((n%14)+14)%14;return[0,1,3,4,5,6,8,9,10,11].includes(c)}
function offwk(k){let d=date(k),dow=d.getDay(),n=Math.round((d-NYU0)/DAY),c=((n%14)+14)%14;return(dow===0||dow===6)&&(c===12||c===13)}
function bmap(ym){try{return JSON.parse(localStorage.getItem('bellevue-'+ym)||localStorage.getItem('b-'+ym)||'null')||BEL[ym]||{}}catch{return BEL[ym]||{}}}
function bcode(k){return bmap(k.slice(0,7))[+k.slice(8)]||''}function bw(k){return bcode(k)==='X'}function load(k){return(nyu(k)?1:0)+(bw(k)?1:0)}
function prev(k){let d=date(k);d.setDate(d.getDate()-1);return dkey(d)}
function slots(y,m){let days=new Date(y,m+1,0).getDate(),weeks={};for(let n=1;n<=days;n++){let k=dkey(new Date(y,m,n)),d=date(k),mon=new Date(d);mon.setDate(d.getDate()-((d.getDay()+6)%7));let w=dkey(mon);(weeks[w]??=[]).push({n,k,score:(load(k)===0?10:load(k)===1?5:-20)+(load(prev(k))===0?4:0)+(offwk(k)?3:0)});}let out=[];Object.values(weeks).forEach(a=>{a.sort((x,y)=>y.score-x.score);let c=[];for(let x of a){if(x.score<0)continue;if(c.every(z=>Math.abs(z.n-x.n)>1)){c.push(x);if(c.length===3)break}}if(c.length<3)for(let x of a){if(x.score<0||c.some(z=>z.n===x.n))continue;c.push(x);if(c.length===3)break}let opt=a.find(x=>x.score>=5&&!c.some(z=>z.n===x.n)&&c.every(z=>Math.abs(z.n-x.n)>1));out.push(...c.map(x=>x.k));if(opt)out.push(opt.k)});return[...new Set(out)].sort()}
function plan(y,m){let out={},rot=0;for(let yy=2026;yy<=y;yy++)for(let mm=(yy===2026?7:0);mm<=(yy===y?m:11);mm++)for(let k of slots(yy,mm)){if(yy===y&&mm===m)out[k]=rot%4;rot++}return out}
let view=new Date(),selected=dkey();
function goals(){let d={gym:2300,rest:2100,protein:180,fat:70,water:96,goalWeight:180,goalBf:12,start:dkey()};try{return{...d,...JSON.parse(localStorage.getItem('nutrition-settings')||'{}')}}catch{return d}}
function target(k){let d=date(k),p=plan(d.getFullYear(),d.getMonth()),g=goals(),gym=p[k]!=null,cal=gym?+g.gym:+g.rest,pr=+g.protein,fa=+g.fat,carb=Math.max(0,Math.round((cal-pr*4-fa*9)/4));return{gym,cal,pr,fa,carb}}
function renderCal(){let y=view.getFullYear(),m=view.getMonth(),p=plan(y,m),days=new Date(y,m+1,0).getDate(),first=(new Date(y,m,1).getDay()+6)%7;$('monthTitle').textContent=new Date(y,m,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});let h='';for(let i=0;i<first;i++)h+='<button class="day empty"></button>';for(let n=1;n<=days;n++){let k=dkey(new Date(y,m,n)),both=nyu(k)&&bw(k),gym=p[k]!=null,ow=offwk(k),cls=`day${both?' both':''}${ow?' offwk':''}${k===selected?' selected':''}${k===dkey()?' today':''}`,dots=`<i class="dot ${both?'red':''}"></i>${gym?'<i class="dot green"></i>':''}${ow?'<i class="dot yellow"></i>':''}`;h+=`<button class="${cls}" data-k="${k}"><span class="num">${n}</span><span class="dots">${dots}</span><span class="kcal">${target(k).cal}</span></button>`}$('monthGrid').innerHTML=h;document.querySelectorAll('.day[data-k]').forEach(b=>b.onclick=()=>{selected=b.dataset.k;renderCal();renderDay()});renderDay()}
function renderDay(){let k=selected,d=date(k),p=plan(d.getFullYear(),d.getMonth()),wi=p[k],work=nyu(k)&&bw(k)?'Both NYU and Bellevue':nyu(k)?'NYU':bw(k)?'Bellevue':'Off both',tr=wi!=null?WK[wi][0]:'Recovery / no planned lifting',t=target(k);$('dayDetail').innerHTML=`<h2>${d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</h2><p><b>Work:</b> ${work}</p><p><b>Training:</b> ${tr}</p><p><b>Calories:</b> ${t.cal} kcal · ${t.pr}g protein</p>`}
function diary(k){try{return JSON.parse(localStorage.getItem('food-diary-'+k)||'[]')}catch{return[]}}function saveDiary(k,a){localStorage.setItem('food-diary-'+k,JSON.stringify(a));syncNut(k)}function totals(k){return diary(k).reduce((a,x)=>(a.cal+=+x.cal||0,a.p+=+x.p||0,a.c+=+x.c||0,a.f+=+x.f||0,a),{cal:0,p:0,c:0,f:0})}function syncNut(k){let old={};try{old=JSON.parse(localStorage.getItem('nutrition-log-'+k)||'{}')}catch{}let t=totals(k);localStorage.setItem('nutrition-log-'+k,JSON.stringify({...old,calories:Math.round(t.cal),protein:Math.round(t.p)}))}
function renderDiary(){let k=$('diaryDate').value||dkey(),t=target(k),a=totals(k);$('remainKcal').textContent=Math.round(t.cal-a.cal);$('goalKcal').textContent=t.cal;$('foodKcal').textContent=Math.round(a.cal);$('pText').textContent=`${Math.round(a.p)} / ${t.pr} g`;$('cText').textContent=`${Math.round(a.c)} / ${t.carb} g`;$('fText').textContent=`${Math.round(a.f)} / ${t.fa} g`;$('pBar').value=Math.min(100,a.p/t.pr*100);$('cBar').value=Math.min(100,a.c/t.carb*100);$('fBar').value=Math.min(100,a.f/t.fa*100);let items=diary(k),h='';MEALS.forEach(m=>{let ar=items.filter(x=>x.meal===m),sum=ar.reduce((s,x)=>s+(+x.cal||0),0);h+=`<div class="meal"><div class="mealhead"><h3>${m} <small>${Math.round(sum)} kcal</small></h3><button class="addFoodBtn" data-meal="${m}">+ Add Food</button></div>${ar.length?ar.map(x=>`<div class="foodrow" data-id="${x.id}"><div><div class="foodname">${esc(x.name)}</div><div class="foodsub">${esc(x.serving||'1 serving')} · P ${n1(x.p)} · C ${n1(x.c)} · F ${n1(x.f)}</div></div><div class="foodcal">${Math.round(x.cal)}</div></div>`).join(''):'<div class="emptymeal">No foods logged</div>'}</div>`});$('meals').innerHTML=h;document.querySelectorAll('.addFoodBtn').forEach(b=>b.onclick=()=>openFood(b.dataset.meal));document.querySelectorAll('.foodrow').forEach(r=>r.onclick=()=>editFood(r.dataset.id));let w=+(localStorage.getItem('water-'+k)||0);$('waterOz').textContent=w;$('waterGoal').textContent=goals().water}
function n1(v){v=+v||0;return v%1?v.toFixed(1):v}function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function logData(){let out=[];for(let i=0;i<localStorage.length;i++){let k=localStorage.key(i);if(k?.startsWith('nutrition-log-')){try{let x=JSON.parse(localStorage.getItem(k));out.push({k:k.slice(14),...x})}catch{}}}return out.sort((a,b)=>a.k.localeCompare(b.k))}
function renderProgress(){let a=logData(),last=a[a.length-1]||{},cut=d=>a.filter(x=>(date(dkey())-date(x.k))/DAY<=d),cur=cut(6).filter(x=>+x.weight),prev=a.filter(x=>{let age=(date(dkey())-date(x.k))/DAY;return age>=7&&age<=13&&+x.weight}),avg=v=>v.length?v.reduce((s,x)=>s+(+x.weight),0)/v.length:null,c=avg(cur),p=avg(prev);$('avgWeight').textContent=c?c.toFixed(1)+' lb':'—';$('weekTrend').textContent=c&&p?`${c-p>=0?'+':''}${(c-p).toFixed(1)} lb`:'—';$('latestWaist').textContent=last.waist?last.waist+' in':'—';$('latestBf').textContent=last.bf?last.bf+'%':'—';let pts=a.filter(x=>+x.weight).slice(-28),svg=$('weightChart');if(pts.length<2)svg.innerHTML='<text x="300" y="95" text-anchor="middle" fill="#6b7280">Log at least 2 weights</text>';else{let vals=pts.map(x=>+x.weight),lo=Math.min(...vals)-1,hi=Math.max(...vals)+1,x=i=>20+i/(pts.length-1)*560,y=v=>20+(hi-v)/(hi-lo)*130;svg.innerHTML=`<polyline fill="none" stroke="#2563eb" stroke-width="4" points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}"/>`+vals.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="4" fill="#2563eb"/>`).join('')};let rec='Log at least 3 morning weights in each of two consecutive weeks before changing calories.';if(cur.length>=3&&prev.length>=3){let pct=-(c-p)/p*100;if(pct<.15)rec='Trend is flat. If adherence has been good, reduce gym and recovery calories by 100.';else if(pct>.75)rec='Weight is falling quickly. Add 100 calories to gym and recovery days.';else rec='Progress is in range. Keep calories unchanged.'}$('recommendation').innerHTML=`<h3>Adaptive calorie guidance</h3><p>${rec}</p>`}
function renderTraining(){$('workoutList').innerHTML=WK.map((w,i)=>`<div class="workoutcard"><h3>Workout ${i+1} · ${w[0]}</h3><div class="focus">${w[1]}</div>${w[2].map((e,j)=>{let id=`w${i}e${j}`,last=localStorage.getItem('lift-'+id)||'';return`<div class="exercise"><b>${e[0]}</b><div class="rx">${e[1]} · compounds 1–2 RIR, isolation 0–1 RIR final set</div><div class="logline"><input id="wt${id}" placeholder="weight" value="${esc(last.split('|')[0]||'')}"><input id="rp${id}" placeholder="reps" value="${esc(last.split('|')[1]||'')}"><button data-lift="${id}">Save</button></div></div>`}).join('')}</div>`).join('');document.querySelectorAll('[data-lift]').forEach(b=>b.onclick=()=>{let id=b.dataset.lift;localStorage.setItem('lift-'+id,$('wt'+id).value+'|'+$('rp'+id).value);b.textContent='Saved'})}
function fillGoals(){let g=goals(),map={gymCal:'gym',restCal:'rest',proteinGoal:'protein',fatGoal:'fat',waterSet:'water',goalWeight:'goalWeight',goalBf:'goalBf',planStart:'start'};for(let id in map)$(id).value=g[map[id]]}
function renderB(){let v=$('bMonth').value||dkey().slice(0,7);$('bMonth').value=v;let[y,m]=v.split('-').map(Number),days=new Date(y,m,0).getDate(),map=bmap(v),h='';for(let n=1;n<=days;n++){let c=map[n]||'';h+=`<button data-day="${n}" class="${c.toLowerCase()}">${n}<br>${c||'·'}</button>`}$('bReview').innerHTML=h;document.querySelectorAll('#bReview button').forEach(b=>b.onclick=()=>{let cur=bmap(v),n=+b.dataset.day,seq=['','X','D','H'],next=seq[(seq.indexOf(cur[n]||'')+1)%4];if(next)cur[n]=next;else delete cur[n];localStorage.setItem('bellevue-'+v,JSON.stringify(cur));renderB()})}
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='diary')renderDiary();if(id==='progress')renderProgress();if(id==='training')renderTraining();if(id==='more'){fillGoals();renderB()}}
function init(){let now=new Date();view=new Date(now.getFullYear(),now.getMonth(),1);selected=dkey(now);$('todayText').textContent=now.toLocaleDateString(undefined,{month:'short',day:'numeric'});$('diaryDate').value=$('progDate').value=dkey();$('bMonth').value=dkey().slice(0,7);document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>page(b.dataset.page));$('prevMonth').onclick=()=>{view.setMonth(view.getMonth()-1);renderCal()};$('nextMonth').onclick=()=>{view.setMonth(view.getMonth()+1);renderCal()};$('diaryPrev').onclick=()=>shiftDiary(-1);$('diaryNext').onclick=()=>shiftDiary(1);$('diaryDate').onchange=renderDiary;$('waterPlus').onclick=()=>{let k=$('diaryDate').value;localStorage.setItem('water-'+k,String(+(localStorage.getItem('water-'+k)||0)+8));renderDiary()};$('waterMinus').onclick=()=>{let k=$('diaryDate').value;localStorage.setItem('water-'+k,String(Math.max(0,+(localStorage.getItem('water-'+k)||0)-8)));renderDiary()};$('saveProgress').onclick=()=>{let k=$('progDate').value,old={};try{old=JSON.parse(localStorage.getItem('nutrition-log-'+k)||'{}')}catch{}localStorage.setItem('nutrition-log-'+k,JSON.stringify({...old,weight:$('progWeight').value,bf:$('progBf').value,waist:$('progWaist').value}));renderProgress()};$('saveGoals').onclick=()=>{let g={gym:+$('gymCal').value,rest:+$('restCal').value,protein:+$('proteinGoal').value,fat:+$('fatGoal').value,water:+$('waterSet').value,goalWeight:+$('goalWeight').value,goalBf:+$('goalBf').value,start:$('planStart').value};localStorage.setItem('nutrition-settings',JSON.stringify(g));renderCal();renderDiary();alert('Goals saved')};$('bMonth').onchange=renderB;$('saveBellevue').onclick=()=>{renderCal();alert('Bellevue month saved')};$('bPhoto').onchange=e=>{let f=e.target.files[0];if(!f)return;$('bPreview').src=URL.createObjectURL(f);$('bPreview').style.display='block'};renderCal();renderDiary();renderTraining();fillGoals();renderB();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function shiftDiary(n){let d=date($('diaryDate').value);d.setDate(d.getDate()+n);$('diaryDate').value=dkey(d);renderDiary()}
window.app={dkey,date,diary,saveDiary,totals,goals,target,renderDiary,esc,n1,MEALS};addEventListener('DOMContentLoaded',init);