let foodEditId=null,baseFood=null,mealPick='Breakfast',stream=null,scanTimer=null,zxControls=null,zxReader=null,scanBusy=false;
const F=id=>document.getElementById(id),A=window.app;
function myFoods(){try{return JSON.parse(localStorage.getItem('my-foods')||'[]')}catch{return[]}}
function setMyFoods(a){localStorage.setItem('my-foods',JSON.stringify(a.slice(0,250)))}
function recent(){try{return JSON.parse(localStorage.getItem('recent-foods')||'[]')}catch{return[]}}
function setRecent(x){let a=recent().filter(y=>y.name!==x.name||y.code!==x.code);a.unshift(x);localStorage.setItem('recent-foods',JSON.stringify(a.slice(0,20)))}
function status(t){if(F('scanStatus'))F('scanStatus').textContent=t}
function clearForm(){foodEditId=null;baseFood=null;['foodName','servingText','foodCalories','foodProtein','foodCarbs','foodFat'].forEach(id=>F(id).value='');F('servings').value=1;F('saveMyFood').checked=false;F('deleteFood').classList.add('hidden');F('pickedProduct').innerHTML=''}
function openFood(meal='Breakfast'){mealPick=meal;clearForm();F('foodMeal').value=meal;F('foodModal').classList.add('open');tab('search');renderRecent();renderSaved()}
function editFood(id){let k=F('diaryDate').value,x=A.diary(k).find(z=>String(z.id)===String(id));if(!x)return;foodEditId=id;baseFood={...x,baseCal:x.cal,baseP:x.p,baseC:x.c,baseF:x.f};F('foodName').value=x.name;F('foodMeal').value=x.meal;F('servingText').value=x.serving||'';F('servings').value=1;F('foodCalories').value=x.cal;F('foodProtein').value=x.p;F('foodCarbs').value=x.c;F('foodFat').value=x.f;F('deleteFood').classList.remove('hidden');F('foodModal').classList.add('open');tab('manual')}
function tab(t){document.querySelectorAll('.foodpane').forEach(x=>x.classList.toggle('active',x.id===({search:'foodSearch',scan:'foodScan',saved:'foodSaved',manual:'foodManual'}[t])));document.querySelectorAll('.foodtabs button').forEach(x=>x.classList.toggle('active',x.dataset.foodtab===t));if(t!=='scan')stopScan()}
function fill(p){baseFood=p;F('foodName').value=p.name||'';F('servingText').value=p.serving||'1 serving';F('servings').value=1;F('foodCalories').value=A.n1(p.cal);F('foodProtein').value=A.n1(p.p);F('foodCarbs').value=A.n1(p.c);F('foodFat').value=A.n1(p.f);F('pickedProduct').innerHTML=`<div class="picked"><b>${A.esc(p.name)}</b>${p.brand?' · '+A.esc(p.brand):''}<br>${A.esc(p.serving||'per serving')} · ${Math.round(p.cal||0)} kcal</div>`;setRecent(p)}
function scale(){if(!baseFood)return;let n=+F('servings').value||1;F('foodCalories').value=A.n1(baseFood.cal*n);F('foodProtein').value=A.n1(baseFood.p*n);F('foodCarbs').value=A.n1(baseFood.c*n);F('foodFat').value=A.n1(baseFood.f*n)}
function normalize(p){let n=p.nutriments||{},serv=p.serving_size||'100 g',factor=1;if(serv&&/([\d.]+)\s*g/i.test(serv))factor=(+serv.match(/([\d.]+)\s*g/i)[1]||100)/100;let per=(k)=>{let v=n[k+'_serving'];if(v==null)v=n[k+'_100g'];return(+v||0)*(n[k+'_serving']!=null?1:factor)};let cal=n['energy-kcal_serving'];if(cal==null)cal=n['energy-kcal_100g']!=null?(+n['energy-kcal_100g']*factor):(+n.energy_serving||+n.energy_100g*factor||0)/4.184;return{code:p.code||'',name:p.product_name||p.generic_name||'Unnamed food',brand:p.brands||'',serving:serv,cal:+cal||0,p:per('proteins'),c:per('carbohydrates'),f:per('fat'),img:p.image_front_small_url||''}}
function resultHtml(p){return`<div class="result" data-product='${A.esc(JSON.stringify(p))}'>${p.img?`<img src="${A.esc(p.img)}">`:'<div class="ph">◉</div>'}<div><div class="rname">${A.esc(p.name)}</div><div class="rsub">${A.esc(p.brand)} · ${A.esc(p.serving)}</div></div><div class="rcal">${Math.round(p.cal)} kcal</div></div>`}
async function search(){let q=F('foodQuery').value.trim();if(!q)return;F('searchResults').innerHTML='<p>Searching…</p>';try{let u='https://world.openfoodfacts.org/cgi/search.pl?search_terms='+encodeURIComponent(q)+'&search_simple=1&action=process&json=1&page_size=20&fields=code,product_name,generic_name,brands,nutriments,serving_size,image_front_small_url',j=await fetch(u).then(r=>r.json()),a=(j.products||[]).map(normalize).filter(x=>x.name&&x.cal>=0);F('searchResults').innerHTML=a.length?a.map(resultHtml).join(''):'<p>No matching foods found.</p>';bindResults()}catch(e){F('searchResults').innerHTML='<p>Food search failed. Check your internet connection.</p>'}}
function bindResults(){document.querySelectorAll('.result[data-product]').forEach(r=>r.onclick=()=>{try{fill(JSON.parse(r.dataset.product))}catch{}})}
async function lookup(code){code=String(code||'').replace(/\D/g,'');if(!code){status('Enter or scan a UPC/EAN barcode.');return}if(scanBusy)return;scanBusy=true;status('Looking up '+code+'…');try{let j=await fetch('https://world.openfoodfacts.org/api/v2/product/'+code+'.json').then(r=>r.json());if(j.status===1&&j.product){let p=normalize({...j.product,code});fill(p);status('✓ Product found. Review the serving and tap Add to diary.');stopScan()}else status('Barcode '+code+' was not found. Try food search or Manual.')}catch(e){status('Product lookup failed. Check your internet connection.')}finally{scanBusy=false}}
function renderRecent(){let a=recent();F('recentFoods').innerHTML=a.map((x,i)=>`<button data-recent="${i}">${A.esc(x.name)}</button>`).join('');document.querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>fill(a[+b.dataset.recent]))}
function renderSaved(){let q=(F('savedSearch')?.value||'').toLowerCase(),a=myFoods().filter(x=>!q||x.name.toLowerCase().includes(q));F('savedResults').innerHTML=a.length?a.map((x,i)=>`<div class="result" data-saved="${i}"><div class="ph">★</div><div><div class="rname">${A.esc(x.name)}</div><div class="rsub">${A.esc(x.serving||'')}</div></div><div class="rcal">${Math.round(x.cal)} kcal</div></div>`).join(''):'<p>No saved foods.</p>';document.querySelectorAll('[data-saved]').forEach(b=>b.onclick=()=>fill(a[+b.dataset.saved]))}
function loadScript(src){return new Promise((resolve,reject)=>{let old=[...document.scripts].find(s=>s.src===src);if(old){if(window.ZXingBrowser)return resolve();old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}let s=document.createElement('script');s.src=src;s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function ensureZXing(){if(window.ZXingBrowser)return true;let urls=['https://unpkg.com/@zxing/browser@0.2.1','https://cdn.jsdelivr.net/npm/@zxing/browser@0.2.1/umd/zxing-browser.min.js'];for(const u of urls){try{await loadScript(u);if(window.ZXingBrowser)return true}catch(e){}}return false}
async function nativeDetector(){if(!('BarcodeDetector' in window))return null;try{let supported=BarcodeDetector.getSupportedFormats?await BarcodeDetector.getSupportedFormats():[];let wanted=['ean_13','ean_8','upc_a','upc_e','code_128'];let formats=supported.length?wanted.filter(x=>supported.includes(x)):wanted;return new BarcodeDetector(formats.length?{formats}:undefined)}catch{return null}}
async function startNative(det){stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});let v=F('scanVideo');v.srcObject=stream;await v.play();status('Point the rear camera at the barcode. Hold steady.');scanTimer=setInterval(async()=>{if(scanBusy)return;try{let r=await det.detect(v);let code=r&&r[0]&&r[0].rawValue;if(code)lookup(code)}catch{}},350)}
async function startZXing(){if(!(await ensureZXing()))throw new Error('scanner library unavailable');zxReader=new ZXingBrowser.BrowserMultiFormatReader();status('Opening camera…');zxControls=await zxReader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},F('scanVideo'),(result,error,controls)=>{if(result&&!scanBusy){let code=result.getText?result.getText():String(result.text||result);if(code){controls.stop();lookup(code)}}});status('Point the rear camera at the barcode. Hold steady.')}
async function startScan(){stopScan();if(!navigator.mediaDevices?.getUserMedia){status('Live camera is unavailable here. Tap “Take barcode photo” instead.');return}F('startScan').disabled=true;try{let det=await nativeDetector();if(det)await startNative(det);else await startZXing()}catch(e){stopScan();status('Live scan could not start. Tap “Take barcode photo” below — that works without live camera access.')}finally{F('startScan').disabled=false}}
function stopScan(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(zxControls){try{zxControls.stop()}catch{}zxControls=null}if(zxReader){try{zxReader.reset&&zxReader.reset()}catch{}zxReader=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(F('scanVideo')){try{F('scanVideo').pause()}catch{}F('scanVideo').srcObject=null}}
function loadImage(file){return new Promise((resolve,reject)=>{let img=new Image(),url=URL.createObjectURL(file);img.onload=()=>resolve({img,url});img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('image load'))};img.src=url})}
async function photoScan(file){if(!file)return;stopScan();status('Scanning photo…');let obj=null;try{obj=await loadImage(file);let code=null,det=await nativeDetector();if(det){try{let r=await det.detect(obj.img);code=r&&r[0]&&r[0].rawValue}catch{}}if(!code){if(!(await ensureZXing()))throw new Error('scanner unavailable');let reader=new ZXingBrowser.BrowserMultiFormatReader();let r=await reader.decodeFromImageElement(obj.img);code=r&&r.getText?r.getText():r&&r.text}if(code){F('barcodeInput').value=code;await lookup(code)}else status('No barcode detected. Move closer, keep the full barcode sharp, and take another photo.')}catch(e){status('Could not read that barcode. Try another photo or enter the UPC/EAN manually.')}finally{if(obj)URL.revokeObjectURL(obj.url);F('barcodePhoto').value=''}}
function saveEntry(){let k=F('diaryDate').value,a=A.diary(k),n=+F('servings').value||1,x={id:foodEditId||Date.now(),name:F('foodName').value.trim()||'Food',meal:F('foodMeal').value,serving:(F('servingText').value||'1 serving')+(n!==1?` × ${n}`:''),cal:+F('foodCalories').value||0,p:+F('foodProtein').value||0,c:+F('foodCarbs').value||0,f:+F('foodFat').value||0};if(foodEditId)a=a.map(z=>String(z.id)===String(foodEditId)?x:z);else a.push(x);A.saveDiary(k,a);if(F('saveMyFood').checked){let m=myFoods().filter(z=>z.name.toLowerCase()!==x.name.toLowerCase());m.unshift({...x,id:undefined,meal:undefined});setMyFoods(m)}F('foodModal').classList.remove('open');A.renderDiary()}
function delEntry(){if(!foodEditId)return;let k=F('diaryDate').value;A.saveDiary(k,A.diary(k).filter(x=>String(x.id)!==String(foodEditId)));F('foodModal').classList.remove('open');A.renderDiary()}
addEventListener('DOMContentLoaded',()=>{window.openFood=openFood;window.editFood=editFood;document.querySelectorAll('.foodtabs button').forEach(b=>b.onclick=()=>tab(b.dataset.foodtab));F('closeFood').onclick=()=>{stopScan();F('foodModal').classList.remove('open')};F('searchFood').onclick=search;F('foodQuery').onkeydown=e=>{if(e.key==='Enter')search()};F('savedSearch').oninput=renderSaved;F('servings').oninput=scale;F('startScan').onclick=startScan;F('stopScan').onclick=()=>{stopScan();status('Scanner stopped.')};F('lookupBarcode').onclick=()=>lookup(F('barcodeInput').value);F('barcodeInput').onkeydown=e=>{if(e.key==='Enter')lookup(F('barcodeInput').value)};F('barcodePhoto').onchange=e=>photoScan(e.target.files[0]);F('addFood').onclick=saveEntry;F('deleteFood').onclick=delEntry});