// v13: robust ZXing photo/live scanning + Safari/in-app detection + USDA fallback
let v13Reader=null,v13Controls=null;
function v13Digits(x){return String(x||'').replace(/\D/g,'')}
function v13Strip0(x){return v13Digits(x).replace(/^0+/,'')}
function v13Code(result){try{return v13Digits(result.getText?result.getText():result.text||result)}catch{return''}}
function v13Stop(){if(v13Controls){try{v13Controls.stop()}catch{}v13Controls=null}if(v13Reader){try{v13Reader.reset&&v13Reader.reset()}catch{}v13Reader=null}try{if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}catch{}let v=F('scanVideo');if(v){try{v.pause()}catch{}try{if(v.srcObject){v.srcObject.getTracks().forEach(t=>t.stop());v.srcObject=null}}catch{}}}
function v13UsdaNutrients(food){let n=food.foodNutrients||[],get=(nums,names)=>{let x=n.find(z=>nums.includes(String(z.nutrientNumber||z.number||''))||names.includes(String(z.nutrientName||z.name||'').toLowerCase()));return +(x?.value??x?.amount??0)||0};return{cal:get(['208','1008'],['energy']),p:get(['203','1003'],['protein']),c:get(['205','1005'],['carbohydrate, by difference','carbohydrate']),f:get(['204','1004'],['total lipid (fat)','total lipid','fat'])}}
function v13NormalizeUsda(food,code){let n=v13UsdaNutrients(food),serv=food.householdServingFullText||((food.servingSize||'')+(food.servingSizeUnit?' '+food.servingSizeUnit:''))||'1 serving';return{code,name:food.description||'Branded food',brand:food.brandName||food.brandOwner||'',serving:serv,cal:n.cal,p:n.p,c:n.c,f:n.f,img:''}}
async function v13OFF(code){let f='code,product_name,generic_name,brands,nutriments,serving_size,image_front_small_url',u='https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'.json?fields='+f+'&lc=en&cc=us',r=await fetch(u,{cache:'no-store'});if(!r.ok)return null;let j=await r.json();return j.status===1&&j.product?normalize({...j.product,code}):null}
async function v13USDA(code){let u='https://api.nal.usda.gov/fdc/v1/foods/search?api_key=DEMO_KEY&dataType=Branded&pageSize=20&query='+encodeURIComponent(code),r=await fetch(u,{cache:'no-store'});if(!r.ok)return null;let j=await r.json(),want=v13Strip0(code),hit=(j.foods||[]).find(x=>v13Strip0(x.gtinUpc)===want);return hit?v13NormalizeUsda(hit,code):null}
async function lookup(code){code=v13Digits(code);if(!code){status('Enter or scan a UPC/EAN barcode.');return}if(scanBusy)return;scanBusy=true;F('barcodeInput').value=code;status('✓ Barcode '+code+' read. Looking up product…');try{let variants=[code,code.length<13?code.padStart(13,'0'):null,code.length===13&&code[0]==='0'?code.slice(1):null].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i),p=null;for(const v of variants){try{p=await v13OFF(v)}catch{}if(p)break}if(!p){for(const v of variants){try{p=await v13USDA(v)}catch{}if(p)break}}if(p){fill(p);try{navigator.vibrate&&navigator.vibrate(60)}catch{}status('✓ Product found. Review the serving and tap Add to diary.');v13Stop()}else{status('✓ Barcode '+code+' was decoded, but no exact product match was found in Open Food Facts or USDA. Search by product name or use Manual.')}}catch(e){status('Barcode was read, but the product lookup failed. Check your internet connection and try again.')}finally{scanBusy=false}}
async function startScan(){v13Stop();if(!navigator.mediaDevices?.getUserMedia){status('Live scanning is blocked in this in-app browser. Tap the Safari compass icon at the bottom-right, open this page in Safari, then retry Live scan. Photo scan can still be used here.');return}if(!window.ZXingBrowser){status('Barcode scanner library did not load. Refresh once while online, or use Take barcode photo.');return}F('startScan').disabled=true;try{v13Reader=new ZXingBrowser.BrowserMultiFormatReader();status('Opening rear camera…');v13Controls=await v13Reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},F('scanVideo'),(result,error,controls)=>{let c=v13Code(result);if(c&&!scanBusy){try{controls.stop()}catch{}lookup(c)}});status('Camera ready. Center the full barcode across the green line and hold steady.')}catch(e){v13Stop();status(e&&e.name==='NotAllowedError'?'Camera permission is blocked for this site. Open in Safari and allow Camera access, or use Take barcode photo.':'Live scan could not start here. Open this page in Safari using the compass icon, or use Take barcode photo.')}finally{F('startScan').disabled=false}}
function stopScan(){v13Stop();status('Scanner stopped.')}
function v13Canvas(img,rot=0){let iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,s=Math.min(1,2200/Math.max(iw,ih)),w=Math.max(100,Math.round(iw*s)),h=Math.max(100,Math.round(ih*s)),c=document.createElement('canvas'),ctx=c.getContext('2d');if(rot%180){c.width=h;c.height=w;ctx.translate(c.width/2,c.height/2);ctx.rotate(rot*Math.PI/180);ctx.drawImage(img,-w/2,-h/2,w,h)}else{c.width=w;c.height=h;ctx.translate(c.width/2,c.height/2);ctx.rotate(rot*Math.PI/180);ctx.drawImage(img,-w/2,-h/2,w,h)}return c}
async function v13DecodeImage(img){if(window.ZXingBrowser){let reader=new ZXingBrowser.BrowserMultiFormatReader();for(const rot of [0,90,270,180]){try{let r=await reader.decodeFromCanvas(v13Canvas(img,rot)),c=v13Code(r);if(c)return c}catch{}}}try{let c=v13Canvas(img,0),ctx=c.getContext('2d'),im=ctx.getImageData(0,0,c.width,c.height);if(typeof v12decode==='function')return v12decode(im.data,c.width,c.height,false)}catch{}return null}
async function photoScan(file){if(!file)return;v13Stop();status('Reading barcode from photo…');let img=new Image(),url=URL.createObjectURL(file);try{await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});let code=await v13DecodeImage(img);if(code){F('barcodeInput').value=code;status('✓ Barcode '+code+' read from photo. Looking up product…');await lookup(code)}else{status('No barcode could be decoded. Retake the photo closer so the barcode fills most of the frame, with every bar sharp and visible.')}}catch(e){status('Could not process that photo. Try another photo or enter the UPC/EAN manually.')}finally{URL.revokeObjectURL(url);F('barcodePhoto').value=''}}
addEventListener('DOMContentLoaded',()=>{if(!navigator.mediaDevices?.getUserMedia){F('startScan').textContent='Open in Safari for live scan';F('scanStatus').textContent='This in-app browser does not expose the camera. Tap the Safari compass icon at bottom-right for Live scan, or use Take barcode photo here.'}F('startScan').onclick=startScan;F('stopScan').onclick=stopScan;F('barcodePhoto').onchange=e=>photoScan(e.target.files[0]);F('lookupBarcode').onclick=()=>lookup(F('barcodeInput').value);});
