// v12 local UPC/EAN scanner override: no BarcodeDetector/ZXing dependency.
var scanCanvas=null,scanCtx=null;
const V12L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'],V12G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'],V12R=['1110010','1100110','1101100','1000010','1011100','1001110','1010000','1000100','1001000','1110100'],V12P=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];
function v12ham(a,b){let d=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])d++;return d}
function v12best(g,a){let bi=-1,bd=99;for(let i=0;i<10;i++){let d=v12ham(g,a[i]);if(d<bd){bd=d;bi=i}}return[bi,bd]}
function v12c13(c){if(!/^\d{13}$/.test(c))return false;let s=0;for(let i=0;i<12;i++)s+=(+c[i])*(i%2?3:1);return(10-s%10)%10===+c[12]}
function v12c8(c){if(!/^\d{8}$/.test(c))return false;let s=0;for(let i=0;i<7;i++)s+=(+c[i])*(i%2?1:3);return(10-s%10)%10===+c[7]}
function v12mods(bits){if(bits.length===95){if(v12ham(bits.slice(0,3),'101')>1||v12ham(bits.slice(45,50),'01010')>1||v12ham(bits.slice(92),'101')>1)return null;let l='',p='',sc=0;for(let i=0;i<6;i++){let g=bits.slice(3+i*7,10+i*7),a=v12best(g,V12L),b=v12best(g,V12G);if(a[1]<=b[1]){l+=a[0];p+='L';sc+=a[1]}else{l+=b[0];p+='G';sc+=b[1]}}let f=V12P.indexOf(p);if(f<0)return null;let r='';for(let i=0;i<6;i++){let q=v12best(bits.slice(50+i*7,57+i*7),V12R);r+=q[0];sc+=q[1]}let c=String(f)+l+r;if(sc<=10&&v12c13(c))return{code:c,score:sc}}if(bits.length===67){if(v12ham(bits.slice(0,3),'101')>1||v12ham(bits.slice(31,36),'01010')>1||v12ham(bits.slice(64),'101')>1)return null;let c='',sc=0;for(let i=0;i<4;i++){let q=v12best(bits.slice(3+i*7,10+i*7),V12L);c+=q[0];sc+=q[1]}for(let i=0;i<4;i++){let q=v12best(bits.slice(36+i*7,43+i*7),V12R);c+=q[0];sc+=q[1]}if(sc<=7&&v12c8(c))return{code:c,score:sc}}return null}
function v12otsu(g){let h=new Uint32Array(256),sum=0;for(let v of g){v=Math.max(0,Math.min(255,Math.round(v)));h[v]++;sum+=v}let n=g.length,sb=0,wb=0,mx=-1,t=127;for(let i=0;i<256;i++){wb+=h[i];if(!wb)continue;let wf=n-wb;if(!wf)break;sb+=i*h[i];let mb=sb/wb,mf=(sum-sb)/wf,d=wb*wf*(mb-mf)*(mb-mf);if(d>mx){mx=d;t=i}}return t}
function v12runs(g){let t=v12otsu(g),b=new Uint8Array(g.length);for(let i=0;i<g.length;i++)b[i]=g[i]<=t?1:0;let r=[],c=b[0],s=0;for(let i=1;i<=b.length;i++)if(i===b.length||b[i]!==c){r.push({c,s,len:i-s,e:i});if(i<b.length){c=b[i];s=i}}return r}
function v12one(g,nm){if(!g||g.length<nm*2)return null;let r=v12runs(g),st=[],en=[];for(let i=0;i+2<r.length;i++){let a=r[i],b=r[i+1],c=r[i+2];if(a.c!==1||b.c!==0||c.c!==1)continue;let av=(a.len+b.len+c.len)/3,rat=Math.max(a.len,b.len,c.len)/Math.max(1,Math.min(a.len,b.len,c.len));if(rat>2.5)continue;let pre=i>0&&r[i-1].c===0?r[i-1].len:a.s,post=i+3<r.length&&r[i+3].c===0?r[i+3].len:g.length-c.e;if(pre>=1.8*av)st.push({i,x:a.s,av});if(post>=1.8*av)en.push({i,x:c.e,av})}let best=null;for(let s of st)for(let e of en){if(e.i<=s.i+16)continue;let w=e.x-s.x;if(w<nm*.8||w>nm*35)continue;let m=w/nm;if(Math.abs(s.av/m-1)>.75||Math.abs(e.av/m-1)>.75)continue;let a=new Array(nm);for(let k=0;k<nm;k++){let x1=Math.max(0,Math.floor(s.x+(k+.18)*m)),x2=Math.min(g.length,Math.ceil(s.x+(k+.82)*m)),sm=0,q=0;for(let x=x1;x<x2;x++){sm+=g[x];q++}a[k]=q?sm/q:255}let z=[...a].sort((x,y)=>x-y),th=(z[Math.floor(nm*.2)]+z[Math.floor(nm*.8)])/2,bits=a.map(v=>v<=th?'1':'0').join(''),d=v12mods(bits);if(d&&(!best||d.score<best.score))best=d}return best}
function v12line(g){return v12one(g,95)||v12one(g,67)||v12one([...g].reverse(),95)||v12one([...g].reverse(),67)}
function v12gray(d,w,x,y){let i=(y*w+x)*4;return .299*d[i]+.587*d[i+1]+.114*d[i+2]}
function v12h(d,w,h,y){let g=new Array(w),yy=Math.max(1,Math.min(h-2,Math.round(y)));for(let x=0;x<w;x++)g[x]=(v12gray(d,w,x,yy-1)+v12gray(d,w,x,yy)+v12gray(d,w,x,yy+1))/3;return g}
function v12v(d,w,h,x){let g=new Array(h),xx=Math.max(1,Math.min(w-2,Math.round(x)));for(let y=0;y<h;y++)g[y]=(v12gray(d,w,xx-1,y)+v12gray(d,w,xx,y)+v12gray(d,w,xx+1,y))/3;return g}
function v12decode(d,w,h,quick){let hs=quick?[.38,.44,.5,.56,.62]:[.18,.24,.30,.36,.42,.48,.54,.60,.66,.72,.78,.84];for(let f of hs){let q=v12line(v12h(d,w,h,h*f));if(q)return q.code}if(!quick)for(let f of [.22,.30,.38,.46,.54,.62,.70,.78]){let q=v12line(v12v(d,w,h,w*f));if(q)return q.code}return null}
function v12canvas(w,h){if(!scanCanvas){scanCanvas=document.createElement('canvas');scanCtx=scanCanvas.getContext('2d',{willReadFrequently:true})}scanCanvas.width=w;scanCanvas.height=h;return scanCanvas}
async function v12fetchProduct(c){let f='code,product_name,generic_name,brands,nutriments,serving_size,image_front_small_url',u='https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(c)+'.json?fields='+f+'&lc=en&cc=us',r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error('HTTP');return r.json()}
async function lookup(code){code=String(code||'').replace(/\D/g,'');if(!code){status('Enter or scan a UPC/EAN barcode.');return}if(scanBusy)return;scanBusy=true;F('barcodeInput').value=code;status('✓ Barcode read: '+code+'. Looking up product…');try{let vs=[code,code.length<13?code.padStart(13,'0'):null,code.length===13&&code[0]==='0'?code.slice(1):null].filter(Boolean).filter((x,i,a)=>a.indexOf(x)===i),prod=null,used=code;for(let v of vs)try{let j=await v12fetchProduct(v);if(j.status===1&&j.product){prod=j.product;used=v;break}}catch{}if(prod){fill(normalize({...prod,code:used}));try{navigator.vibrate&&navigator.vibrate(60)}catch{}status('✓ Product found. Review the serving and tap Add to diary.');stopScan()}else status('✓ Barcode '+code+' was read correctly, but this product is not in Open Food Facts. Search by name or use Manual.')}catch{status('Barcode read, but product lookup could not connect. Check internet and try again.')}finally{scanBusy=false}}
async function startScan(){stopScan();if(!navigator.mediaDevices?.getUserMedia){status('Live camera is unavailable here. Use “Take barcode photo” instead.');return}F('startScan').disabled=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}});let v=F('scanVideo');v.srcObject=stream;await v.play();status('Camera ready. Center the full barcode across the green line and hold steady.');scanTimer=setInterval(()=>{if(scanBusy||!v.videoWidth)return;try{let w=Math.min(900,v.videoWidth),h=Math.max(240,Math.round(v.videoHeight*w/v.videoWidth));v12canvas(w,h);scanCtx.drawImage(v,0,0,w,h);let im=scanCtx.getImageData(0,0,w,h),c=v12decode(im.data,w,h,true);if(c){status('✓ Barcode '+c+' detected.');lookup(c)}}catch{}},280)}catch(e){stopScan();status(e&&e.name==='NotAllowedError'?'Camera permission is blocked. Allow camera access for this site or use “Take barcode photo”.':'Live camera could not start. Use “Take barcode photo” below.')}finally{F('startScan').disabled=false}}
function stopScan(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}let v=F('scanVideo');if(v){try{v.pause()}catch{}v.srcObject=null}}
async function photoScan(file){if(!file)return;stopScan();status('Reading barcode from photo…');let img=new Image(),url=URL.createObjectURL(file);try{await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});let iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height,s=Math.min(1,1800/Math.max(iw,ih)),w=Math.max(200,Math.round(iw*s)),h=Math.max(200,Math.round(ih*s));v12canvas(w,h);scanCtx.fillStyle='#fff';scanCtx.fillRect(0,0,w,h);scanCtx.drawImage(img,0,0,w,h);let im=scanCtx.getImageData(0,0,w,h),c=v12decode(im.data,w,h,false);if(c){F('barcodeInput').value=c;status('✓ Barcode '+c+' read from photo. Looking up product…');await lookup(c)}else status('No UPC/EAN was readable in that photo. Move closer so the barcode fills most of the picture, keep every bar visible and sharp, and try again.')}catch{status('Could not process that photo. Try another photo or enter the UPC/EAN manually.')}finally{URL.revokeObjectURL(url);F('barcodePhoto').value=''}}
