-- Versioned, append-only proof of explicit health-data consent.
-- Users can read and add only their own events. They cannot rewrite or delete
-- a consent history; deleting the authentication account cascades all events.

create table if not exists public.health_data_consent_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('granted','withdrawn')),
  consent_version text not null,
  policy_version text not null,
  purposes text[] not null default '{}'::text[],
  explicit_statement text not null,
  locale text,
  region text not null default 'global',
  source text not null default 'work-and-workout-app',
  created_at timestamptz not null default now(),
  constraint health_data_consent_grant_has_purpose check (action <> 'granted' or cardinality(purposes) > 0),
  constraint health_data_consent_allowed_purposes check (purposes <@ array['account_cloud_sync','encrypted_webdav_sync','personalized_ai']::text[])
);

create index if not exists health_data_consent_events_user_created_idx
  on public.health_data_consent_events(user_id,created_at desc,id desc);

alter table public.health_data_consent_events enable row level security;

revoke all on table public.health_data_consent_events from public,anon,authenticated;
grant select,insert on table public.health_data_consent_events to authenticated;
grant select,insert,update,delete on table public.health_data_consent_events to service_role;

revoke all on sequence public.health_data_consent_events_id_seq from public,anon,authenticated;
grant usage,select on sequence public.health_data_consent_events_id_seq to authenticated;
grant usage,select,update on sequence public.health_data_consent_events_id_seq to service_role;

drop policy if exists health_data_consent_select_own on public.health_data_consent_events;
create policy health_data_consent_select_own
  on public.health_data_consent_events
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists health_data_consent_insert_own on public.health_data_consent_events;
create policy health_data_consent_insert_own
  on public.health_data_consent_events
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

comment on table public.health_data_consent_events is
  'Append-only user consent and withdrawal receipts for health-data cloud and AI processing.';
